### ISSUE TITLE
Allow user to selectively not apply task to check task

### ISSUE THREAD

**Issue by JLLeitschuh** [JLLeitschuh/ktlint-gradle#105]
Use case is my own.

I'd like to apply this plugin to get the `ktlintApplyToIdea` and `ktlintApplyToIdeaGlobally` task without the `ktlintCheck` task also getting added.

Something like:
```kotlin
ktlint {
    automaticallyAddToCheckTask = false
}
```

**Comment by JLLeitschuh** [comment]
Alternative suggestion that I just thought of (I could be swayed either way on this one):
Create a separate plugin (under the same repository (and maybe even under the same source directory)) that is called something like `ktlint-helpers`. This helpers plugin is automatically applied when you apply the `ktlint` plugin but when you only apply the `ktlint-helpers` plugin you only get the tasks that don't modify the `check` task.

@Tapchicoma, what are your thoughts?

**Comment by Tapchicoma** [comment]
Tough question, you have very specific use-case here.

Regarding option one:
```gradle
ktlint {
    automaticallyAddToCheckTask = false
}
```
Then also there should be a flag for format tasks.

Regarding option two - conceptually I like it more, then the first one. From implementation wise - not sure how to approach it. Like add that `ktlint` plugin depends on `ktlint-helpers` plugin?

Can you archive the same goal by using Gradle property switch?
```gradle
if (project.hasProperty("KtLint")) {
    apply plugin: "org.jlleitschuh.gradle.ktlint"
    ...
}
```
and then whoever is needed this task can run it using following:
```bash
$ ./gradlew -PKtLint ktlintApplyToIdea
```

**Comment by JLLeitschuh** [comment]
That last option you proposed seems very "not gradley". I'm going to take a crack at my second plugin option and see how that works.

**Comment by Tapchicoma** [comment]
@JLLeitschuh do you want to keep this issue opened after `5.0.0` release?

Otherwise, please, close it.
