### ISSUE TITLE
ktlintFormat and ktlintCheck are not working.

### ISSUE THREAD

**Issue by GianfrancoMS** [JLLeitschuh/ktlint-gradle#109]
I'm trying to apply the plugin to an Android project, but ktlintFormat and ktlinCheck are not working.

For example, let's take this simple Kotlin file that contains an activity and it's not well formatted

```
package com.gianfranco.stormy

import android.os.Bundle
import android.support.v7.app.AppCompatActivity

    class MainActivity : AppCompatActivity() {
            override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(     savedInstanceState)

                setContentView(R.layout.activity_main)
    }
}
```

When I run ./gradlew ktlintCheck or ./gradlew ktlintFormat, nothing happens. The output is BUILD SUCCESSFUL. 

The build.gradle for the project can be found [here](https://github.com/GianfrancoMS/Stormy/blob/develop/build.gradle)

I'm using Gradle 4.8.1 and AGP 3.2.0-beta03.

**Comment by JLLeitschuh** [comment]
Are the tasks marked "UP-TO-DATE" thus not executing the format task or are they being run?

**Comment by GianfrancoMS** [comment]
This is the output for ktlintCheck:
```
8:37:06 AM: Executing task 'ktlintCheck'...

Executing tasks: [ktlintCheck]

Configuration on demand is an incubating feature.
> Task :app:ktlintDebugAndroidTestCheck NO-SOURCE
> Task :app:ktlintDebugCheck
> Task :app:ktlintDebugUnitTestCheck NO-SOURCE
> Task :app:ktlintReleaseCheck
> Task :app:ktlintReleaseUnitTestCheck NO-SOURCE
> Task :app:ktlintCheck

BUILD SUCCESSFUL in 2s
2 actionable tasks: 2 executed
8:37:09 AM: Task execution finished 'ktlintCheck'.
```

**Comment by GianfrancoMS** [comment]
And this the output for ktlintFormat:

```
8:35:56 AM: Executing task 'ktlintFormat'...

Executing tasks: [ktlintFormat]

Configuration on demand is an incubating feature.
> Task :app:ktlintDebugAndroidTestFormat
> Task :app:ktlintDebugFormat
> Task :app:ktlintDebugUnitTestFormat
> Task :app:ktlintReleaseFormat
> Task :app:ktlintReleaseUnitTestFormat
> Task :app:ktlintFormat

BUILD SUCCESSFUL in 7s
5 actionable tasks: 5 executed
8:36:04 AM: Task execution finished 'ktlintFormat'.

```

**Comment by JLLeitschuh** [comment]
Can you provide your `build.gradle.kts` scripts?

**Comment by GianfrancoMS** [comment]
I'm not using the Gradle Kotlin DSL, just plain old Groovy.
The build.gradle can be found [here](https://github.com/GianfrancoMS/Stormy/blob/develop/build.gradle)

**Comment by JLLeitschuh** [comment]
Try also applying the plugin in the `allprojects` block.

**Comment by GianfrancoMS** [comment]
I added these lines to my module's build.gradle and ktlintCheck is working now:

```
sourceSets {
    main.java.srcDirs += 'src/main/kotlin'
    main.java.srcDirs += [file("$buildDir/generated/source/kapt/main")]
    test.java.srcDirs += 'src/test/kotlin'
    androidTest.java.srcDirs += 'src/androidTest/kotlin'
}
```

But ktlintFormat is still not working. Any ideas?

**Comment by Tapchicoma** [comment]
@GianfrancoMS I can't find `ktlint-gradle` configuration in your _develop_ branch `build.gradle`.

**Note**, that to use this plugin with android plugin, you should use `classpath` approach, not `plugins {}` config block.

**Comment by GianfrancoMS** [comment]
@Tapchicoma I removed it. I ended up using just ktlint.

**Comment by Tapchicoma** [comment]
@GianfrancoMS can you either try to apply this plugin via `classpath` and report back or just close this issue?
