### ISSUE TITLE
Consider using workers api for check task

### ISSUE THREAD

**Issue by Tapchicoma** [JLLeitschuh/ktlint-gradle#116]
Theoretically this should improve check tasks run time in multimodule project setup:

https://guides.gradle.org/using-the-worker-api/

**Comment by Tapchicoma** [comment]
Also format task can use the same approach after #111 will be implemented.

**Comment by Tapchicoma** [comment]
After investigation, Workers API has no place to be used inside plugin.

**Comment by ZakTaccardi** [comment]
> Workers API has no place to be used inside plugin.

@Tapchicoma what's the reasoning for this? Formatting checks for each module should be executed in parallel imo

**Comment by Tapchicoma** [comment]
At that time it was too too much amount of work using CLI ktlint to merge reports from each worker to one resulting report. Using `ktlint-core` was blocked by having editorconfig handling and idea integration in ktlint cli module.

On the present day - editorconfig handling was moved to `ktlint-core` and I am working on moving idea integration there. After it using workers could be reevaluated again.

**Comment by ZakTaccardi** [comment]
Should we re-open this issue then?

**Comment by Tapchicoma** [comment]
I would consider it as a part of migration to `ktlint-core` issue.
