### ISSUE TITLE
Applying plugin to subprojects doesn't seem to work

### ISSUE THREAD

**Issue by Egorand** [JLLeitschuh/ktlint-gradle#117]
Trying to add ktlint-gradle to [Okio](https://github.com/square/okio) via

```
subprojects {
    apply plugin: "org.jlleitschuh.gradle.ktlint" // Version should be inherited from parent
}
```

which fails with

```
> Cannot add task 'ktlintMainCheck' as a task with that name already exists.
```

Also, it'd be great to have a multi-module example in samples.

**Comment by Tapchicoma** [comment]
Seems `ktlint-gradle` has been already applied to subprojects.

@Egorand can you show how your parent(root) `build.gradle` defines/applies `ktlint-gradle` plugin?

**Comment by Egorand** [comment]
@Tapchicoma I'm adding the classpath dependency in the root Gradle file:

```
dependencies {
  ...
  classpath "gradle.plugin.org.jlleitschuh.gradle:ktlint-gradle:4.1.0"
}
```

and using `subprojects`, as described in README:

```
subprojects {
  ...
  apply plugin: "org.jlleitschuh.gradle.ktlint"
}
```

Right now it fails with:

```
* What went wrong:
A problem occurred configuring project ':okio:js'.
> Cannot add task 'ktlintMainCheck' as a task with that name already exists.
```

The project structure is as follows:

```
include ':okio'
include ':okio:js'
include ':okio:jvm'
include ':okio:native'
```

**Comment by Tapchicoma** [comment]
Interesting, theoretically this approach should work :thinking: 

I will check it and see why it can fail.

BTW lastest plugin version is `5.0.0`

**Comment by Egorand** [comment]
Thanks, I'll try `5.0.0`, `plugins.apply()` and report back

**Comment by Tapchicoma** [comment]
Note that `plugins.apply()` is for kotlin DSL, not sure if it will work in groovy.

Still suspect that plugin is applied second time somewhere.

**Comment by Egorand** [comment]
Looks like I got `5.0.0` working with the same configuration, thanks for the help!

**Comment by Tapchicoma** [comment]
This change in `5.0.0` fixes your issue:
> Removed

>    Does not automatically apply plugin tasks to all sub-projects (it breaks the Gradle plugin model).
