### ISSUE TITLE
Plugin doesn't create tasks in Kotlin/Native modules

### ISSUE THREAD

**Issue by Egorand** [JLLeitschuh/ktlint-gradle#119]
In a multiplatform project that adds the plugin via `subprojects` (here's the [PR](https://github.com/square/okio/pull/502) that adds ktlint), tasks are not being created for the Kotlin/Native module. Running

```
./gradlew :okio:js:ktlintCheck
```

succeeds, while

```
./gradlew :okio:native:ktlintCheck
```

produces

```
* What went wrong:
Task 'ktlintCheck' not found in project ':okio:native'.
```

Looking at the code, I see that the plugin is supposed to work with Kotlin/Native, can try to debug later to see what's going wrong.

**Comment by Tapchicoma** [comment]
The problem that okio applies following native plugin `org.jetbrains.kotlin.platform.native`, while ktlin-gradle plugin supports only `konan` native plugin ("org.jetbrains.kotlin.konan").

According to https://plugins.gradle.org/plugin/org.jetbrains.kotlin.native - your variant is experimental plugin, and ['konan'](https://github.com/JetBrains/kotlin-native/blob/master/GRADLE_PLUGIN.md) is more official one.

But still it is worth to add support for this experimental one.

**Comment by Egorand** [comment]
The difference between `org.jetbrains.kotlin.native` and `org.jetbrains.kotlin.platform.native` seems to be that the former should be used for Native-only projects, and the latter - for Native parts of multiplatform projects, which is our use-case.
