### ISSUE TITLE
Consider removing afterEvaluate

### ISSUE THREAD

**Issue by tasomaniac** [JLLeitschuh/ktlint-gradle#122]
Please consider removing afterEvaluate from the plugin configuration scripts. 

First of all, overusing afterEvaluate is bad for the user. When a plugin uses it, it could potentially result into bigger problems. 

Instead more reactive/live collections should be used to detect the usages in the project and react accordingly. Example is:

```
project.plugins.withId('kotlin') {
    configureKotlinProject()
}
```

Here we are able to configure the project just after the kotlin plugin is applied. 

Second problem I faced is regarding another plugin I contribute which configures other static analysis plugins: https://github.com/novoda/gradle-static-analysis-plugin/issues/129

Because of the `afterEvaluate` usage, I also needed to use `afterEvaluate` in that project and that results into nondeterministic behavior. Depending on the client project I integrate, I started to get task not found problems. I think I can resolve this particular issue in `static-analysis-plugin`.

But still I believe that everything will be nicer without `afterEvaluate`.

**Comment by Tapchicoma** [comment]
Interesting. Will evaluate this proposal :+1:

**Comment by JLLeitschuh** [comment]
I agree, I've been thinking about this myself as well.
We might want to update to supporting Gradle 4.9+ so that we get the nice new deferred configuration.
That would allow us to totally remove the need for the `afterEvaluate`.

**Comment by JLLeitschuh** [comment]
This very much needs to change.
I'm guessing that, as the plugin is currently written, it's incompatible with Gradle 4.9:
https://docs.gradle.org/current/release-notes.html#restricting-cross-configuration-and-lifecycle-hooks-from-lazy-configuration-apis

**Comment by tasomaniac** [comment]
Lazy tasks are even nicer but I am not sure if they are required. 

Using lifecycle callbacks and live collections of plugins and tasks, it might still be possible to remove afterEvaluate

**Comment by tasomaniac** [comment]
Amazing. Thanks for doing this.
