### ISSUE TITLE
Add support for custom reporters.

### ISSUE THREAD

**Issue by Tapchicoma** [JLLeitschuh/ktlint-gradle#125]
See https://github.com/shyiko/ktlint#creating-a-reporter

**Comment by tasomaniac** [comment]
Html reporting would especially be useful.

**Comment by PPetka** [comment]
@Tapchicoma any progress on that? The plugin is great but I am really missing this feature.

**Comment by Tapchicoma** [comment]
@PPetka have some ideas, but it is not in the closest plans.
