### ISSUE TITLE
Compatibility issue with Android tools 3.3.0-alpha11

### ISSUE THREAD

**Issue by tasomaniac** [JLLeitschuh/ktlint-gradle#131]
I just tried the `6.0.0` version of ktlint Gradle plugin with the latest version of Android Gradle plugin. 

The latest version of ktlint removed the `afterEvaluate`
The latest version of AGP introduced lazy task creation. 

When they come together, I got the following error: 

> Cannot add task ‘assembleDebug’ as a task with that name already exists.

<details>
Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$DuplicateTaskException: Cannot add task 'assembleDebug' as a task with that name already exists.
    at org.gradle.api.internal.tasks.DefaultTaskContainer.duplicateTask(DefaultTaskContainer.java:250)
    at org.gradle.api.internal.tasks.DefaultTaskContainer.registerTask(DefaultTaskContainer.java:365)
    at org.gradle.api.internal.tasks.DefaultTaskContainer.register(DefaultTaskContainer.java:345)
    at com.android.build.gradle.internal.tasks.factory.TaskFactoryImpl.register(TaskFactoryImpl.kt:84)
    at com.android.build.gradle.internal.TaskManager.createAnchorAssembleTasks(TaskManager.java:3038)
    at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:814)
    at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
    at com.android.build.gradle.BasePlugin.lambda$createTasks$4(BasePlugin.java:667)
    at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt:37)
    at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt)
</details>

AGP tries to `register` the task but the `assembleDebug` task is already added by `ktlint` Gradle plugin. Not sure if `ktlint` really creates a task named `assembleDebug` but it would worth double-checking. 

Reverting back to `5.0.0` fixes the problem. :+1:

**Comment by Tapchicoma** [comment]
Interesting, will investigate this problem.

**Comment by Tapchicoma** [comment]
@tasomaniac I've set android gradle plugin version to `3.3.0-alpha11` in samples and tried to run `ktlintCheck` - works without a problem. Can you provide more insides how have you applied the plugin?

**Comment by Tapchicoma** [comment]
Though it was on top on current PR #132. Maybe updating Gradle fixed this issue :thinking:

**Comment by Tapchicoma** [comment]
Also I see that minimal supported Gradle version for `3.3.0` is `4.10`.

**Comment by Tapchicoma** [comment]
Tried `6.0.0` version on sample android project - task works. I think there should more conditions on this error to happen.

**Comment by Tapchicoma** [comment]
@janakagamini do you have android build variants in configuration?

**Comment by tasomaniac** [comment]
Here is the project I tried. https://github.com/tasomaniac/OpenLinkWith

It has build flavors. Just by updating the ktlint version, you can reproduce the error.

**Comment by Tapchicoma** [comment]
Android Gradle plugin dynamically creates tasks for flavors and don't provide ways to get flavors (and it configuration) without creating tasks :disappointed: 

Will try to find solution that don't uses `afterEvaluate {}`.

**Comment by tasomaniac** [comment]
I've used `android.applicationVariants.all { }` before. all is dynamic, whenever a new variant is added, you will be notified. It is a great way to prevent afterEvaluate since your code will be called just after the variants are added. 

Do you think that would be useful?

**Comment by JLLeitschuh** [comment]
@tasomaniac What's the type of `applicationVariants`? There might be a better method to use in the newest version of Gradle.

**Comment by tasomaniac** [comment]
I think it is just a collection. This is coming from Android Gradle Plugin. I don't think it has been changed that much.

**Comment by JLLeitschuh** [comment]
@Tapchicoma I think you'll want to prefer `configureEach` instead of `all`. However, that will up our lowest supported version to Gradle 4.9. `configureEach` is the new deferred configuration API.

**Comment by Tapchicoma** [comment]
@JLLeitschuh it can be done in the release after this. New android gradle plugin was relased that has minimal supported gradle version 4.6

**Comment by JLLeitschuh** [comment]
Ah, okay, you can use `all` then. Do we want to have a stated goal of having the same Gradle version compatibility as the lowest supported version of the most recent release of the android gradle plugin?

I'm not an android user so I have no stake in this game.

**Comment by Tapchicoma** [comment]
@JLLeitschuh I'd say let have following:
next android gradle plugin release minimal supported gradle version minus 1 version. 

For example, next `3.3` release has `4.10` as a minimal supported version, so after bumping android gradle to `3.2` we can set minimal supported version to `4.9`

**Comment by JLLeitschuh** [comment]
Sure? Excluding major version bump support like for gradle `5.0`?

**Comment by Tapchicoma** [comment]
Minimal supported version - doesn't mean that we can't support 5.x Gradle versions.

Also I hope next android gradle 3.3 release will be not in half a year.

**Comment by JLLeitschuh** [comment]
I was more saying that if the android plugin's minimum supported version is 5.0, it would make sense to make our minimal support 5.0, not 4.10. Thoughts?

**Comment by tasomaniac** [comment]
Looking at the past, I think there is long time until min supported version will be 5.0. I would say at least a year. Based on past experience. 

Also I would say go for it if it will make your tool easier to maintain. Detekt for example started using lazy task API and immediately made 4.9 or 4.10 as the min supported. 

Since older versions of plugins are compatible with newer versions of the actual KtLint tool, you have the option to be more flexible.

**Comment by Tapchicoma** [comment]
Please try released version `6.1.0` and feel free to reopen this issue.
