### ISSUE TITLE
Not in `check` task

### ISSUE THREAD

**Issue by gladed** [JLLeitschuh/ktlint-gradle#14]
My project has 

```gradle
apply plugin: 'kotlin'
apply plugin: "org.jlleitschuh.gradle.ktlint"
```
and `./gradlew ktlintCheck` works fine.

But `./gradlew check` does not run `ktlint`. I tried adding `check.dependsOn ktlintCheck`  but this results in:
```
> Could not get unknown property 'ktlintCheck' for root project 'xyz' of type org.gradle.api.Project.
```

Is there any way to get this attached to the `check` task?

**Comment by JLLeitschuh** [comment]
In Gradle Kotlin DSL:
```kotlin
tasks.getByName("check").dependsOn(tasks.getByName("ktlintCheck"))
```
In groovy based gradle:
```gradle
check.dependsOn ktlintCheck
```

**Comment by gladed** [comment]
> In Gradle Kotlin DSL:
>
>     tasks.getByName("check").dependsOn(tasks.getByName("ktlintCheck"))

Results in this error: `Task with name 'ktlintCheck' not found in root project 'XYZ'.`

> In groovy based gradle:
>
>     check.dependsOn ktlintCheck

Results in the error in my original issue.

Again, `./gradlew ktlintCheck` on the same project works. Getting same results in Gradle 3.5 and 4.0.2.

**Comment by JLLeitschuh** [comment]
Sorry, try putting this in an `afterEvaluate` block.
This is a bug and should be fixed. I think this may have been introduced in #12

@Tapchicoma can you take a look at this by chance?

**Comment by Tapchicoma** [comment]
@JLLeitschuh sure, will take a look.

**Comment by gladed** [comment]
Confirmed:
```gradle
afterEvaluate {
    check.dependsOn ktlintCheck
}
```
works fine now. Thanks for the workaround!

**Comment by Tapchicoma** [comment]
@JLLeitschuh checked, my changes doesn't affect it.

I think `ktlintCheck` never adds itself as a task that `check` task depends on. But it worth to do it. Will open a PR for it.

**Comment by JLLeitschuh** [comment]
It would be nice if you could access the `ktlintCheck` task without having to use an `afterEvaluate` block too.
