### ISSUE TITLE
Add support for new kotlin multiplatform plugin

### ISSUE THREAD

**Issue by Tapchicoma** [JLLeitschuh/ktlint-gradle#144]
Recently, new gradle multiplatform plugin was released:
https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html
https://plugins.gradle.org/plugin/org.jetbrains.kotlin.multiplatform

Our plugin should add a support for it.

**Comment by JLLeitschuh** [comment]
👍

**Comment by JakeWharton** [comment]
The key here is that you should honor the multiplatform platforms before honoring Android variants.

Right now when the Android plugin is applied to a MPP project you get variant-specific tasks. But like the compile tasks, I would expect to get something like `ktlintCheckJs`, `ktlintDebugCheckAndroid`, and `ktlintReleaseCheckAndroid` instead.

**Comment by Tapchicoma** [comment]
Repo with new plugin usages samples: https://github.com/h0tk3y/k-new-mpp-samples
