### ISSUE TITLE
Semver can't be resolved because Semver pom.xml is missing from JFrog

### ISSUE THREAD

**Issue by JLLeitschuh** [JLLeitschuh/ktlint-gradle#162]
If your root build is just this:
```
plugins {
    id("org.jlleitschuh.gradle.ktlint-idea") version "6.2.1"
}
```

You get the following exception:
```
./gradlew tasks

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'root-dependency-manager'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find net.swiftzer.semver:semver:1.1.0.
     Searched in the following locations:
       - file:/Users/jonathanleitschuh/.gradle/caches/5.0-rc-1/embedded-kotlin-repo-1.3.0-2/repo/net/swiftzer/semver/semver/1.1.0/semver-1.1.0.jar
       - https://plugins.gradle.org/m2/net/swiftzer/semver/semver/1.1.0/semver-1.1.0.pom
     Required by:
         project : > org.jlleitschuh.gradle.ktlint-idea:org.jlleitschuh.gradle.ktlint-idea.gradle.plugin:6.2.1 > gradle.plugin.org.jlleitschuh.gradle:ktlint-gradle:6.2.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

This is because the semver plugin isn't published to the Gradle plugin portal.
We should consider embedding that project's one source file in our build as a vendored dependency.

**Comment by yschimke** [comment]
Linking to the gradle report, they closed out

https://github.com/gradle/gradle/issues/7584

**Comment by flaquir4** [comment]
There is any workarround to solve this while it's fixed?

**Comment by eskatos** [comment]
I would say in order of preference, either:
- get `semver` to be published properly and use the new version
- or, downgrade `semver` to a version that is properly published
- or, use the following dodgy workaround to re-enable artifact metadata inference from artifact files on `gradlePluginPortal()`, for the `plugins {}` block:

```kotlin
// settings.gradle.kts
pluginManagement {
    repositories {
        gradlePluginPortal().apply {
            (this as MavenArtifactRepository).metadataSources {
                mavenPom()
                artifact()
            }
        }
    }
}
```

**Comment by Tapchicoma** [comment]
> get semver to be published properly and use the new version

This PR should address this: https://github.com/swiftzer/semver/pull/3

**Comment by Tapchicoma** [comment]
release `1.1.1` has pom files in bintray: https://bintray.com/swiftzer/maven/semver/1.1.1#files/net%2Fswiftzer%2Fsemver%2Fsemver%2F1.1.1

**Comment by jaredsburrows** [comment]
@JLLeitschuh I am not using the plugins block.

**Comment by JLLeitschuh** [comment]
It's a bug caused by the Gralde Plugin Portal, I should fix the title.

**Comment by Tapchicoma** [comment]
@fractalwrench note that due to Gradle plugin changes, plugin id changed, if you are using `classpath` approach:
```gradle
classpath "org.jlleitschuh.gradle:ktlint-gradle:6.3.1"
```
