### ISSUE TITLE
ClassNotFoundException for ReporterType

### ISSUE THREAD

**Issue by tasomaniac** [JLLeitschuh/ktlint-gradle#165]
Hi, 

With the recent changes, the string definition of reporters list was replaced with an enum type. I tried many many times but I'm getting ClassNotFoundException. The import is also not recognized. 

Would it be possible to change `reporters` from being a list to a data structure. The structure most common with the standard code analysis tools that come with Gradle would be awesome. They use something like

```
reporters {
    xml.enabled = true
}
```

What I'm doing different in my project that I have a separate `static-analysis.gradle` file where I apply ktlint. And then I put this into each subproject. I don't directly configure ktlint directly in `build.gradle` files. 

Maybe that is why I keep having problems. 

I will try to provide an example project.

**Comment by Tapchicoma** [comment]
Hi, this is limitation of Gradle that it can't import in external script files. What you can do it add following in your main project file:
```gradle
ext.ReporterType = org.jlleitschuh.gradle.ktlint.reporter.ReporterType
```

and then in your `static-anlysis.gradle` file following should work:
```gradle
ktlint {
    reporters = [ReporterType.CHECKSTYLE]
}
```

**Comment by tasomaniac** [comment]
Interesting. Will try this. If this works, would be great to add it to docs

**Comment by tasomaniac** [comment]
This works well. Needs to be put after `classpath` in the roor `build.gradle` file
