### ISSUE TITLE
Report file path and backward compatibility

### ISSUE THREAD

**Issue by tasomaniac** [JLLeitschuh/ktlint-gradle#166]
Hi, I noticed that the file path to the reports has changes after version 4.1.0. Don't know when exactly did they change. I couldn't find it in the changelogs. 

Since we use other tools that uses the output to automate things, it was a breaking change for us. 

Would it be possible to support custom report file path? Or an API to access them either through the task or the extension?

Thanks.

**Comment by tasomaniac** [comment]
Sorry, I've actually see that it was mentioned in the changelog in 6.0.0

I've decided to use `ktlintTask.reportOutputFiles` from the task now. Hope it will not be renamed since it is also not marked as `Internal`. 

Closing this for now.

**Comment by Tapchicoma** [comment]
Should not be renamed :+1:

**Comment by tasomaniac** [comment]
Thanks 👍 This worked great.
