### ISSUE TITLE
Tests are missing

### ISSUE THREAD

**Issue by Tapchicoma** [JLLeitschuh/ktlint-gradle#17]
This plugin needs some tests, so it will be easier to add a new features and check already existing behaviour.

@JLLeitschuh you can assign it to me, will try to add them when I will have spare time.

**Comment by JLLeitschuh** [comment]
I know that Junit5 is using something clever for testing their gradle plugin. We should try to use whatever they are using.

Also, if you can drive the tests with Junit5 that would be really cool but not necessary.

**Comment by JLLeitschuh** [comment]
@Tapchicoma Do you want to take the code from @eskatos's PR and drop it in to the repo?

**Comment by JLLeitschuh** [comment]
Closed by c31eae2
