### ISSUE TITLE
Add android variants check and format tasks

### ISSUE THREAD

**Issue by Tapchicoma** [JLLeitschuh/ktlint-gradle#170]
Currently, plugin checks SourceSet for particular android variant, but it doesn't check sources that variant depends on as well.

Need to add special meta tasks for each android variant that will trigger tasks for all dependent variant sources.

**Comment by bitsydarel** [comment]
Any prognostic when this fix will be available?

I'm trying to run variant specific check to speed up the build on CI.
I saw No-source message, I taught it's was a configuration issue from my side.

**Comment by Tapchicoma** [comment]
Tasks with `NO-SOURCE` message has a very small impact on a build time - it means there are no inputs and task execution will be skipped.

Regarding task that runs check for particular variant, should be available in next version (though plans are also bump minimal supported Gradle version to `5.0.0`). Regarding time - can't promise anything.

**Comment by bitsydarel** [comment]
It's seems that flavor specific task currently work but not variant one.

Example if I have flavor a and build type x and y.

Ktlint work for task KtlintA but not for KtlintAx or ktlintAy.

**Comment by bitsydarel** [comment]
Yes you were right, Its only founded issue for the flavor A, executing flavor task and Ktlintmaincheck sounds like a workarounds for my issue. But still strange why cx task does not include the main folder too...

**Comment by tasomaniac** [comment]
It was checking main folder too in 5.1.0 The behavior was changed in version 6.0. At our company, we are using 5.1.0 still. 

I did this change in Novoda's plugin to support both versions in a nice way. Will be available in the next version of that plugin https://github.com/novoda/gradle-static-analysis-plugin/pull/153

**Comment by Tapchicoma** [comment]
Opened new issue for multiplatform: #182 

Currently new mpp plugin kind of messy and there is no straghtforward way to get all sourcesets for target (with dependent sources)

**Comment by tasomaniac** [comment]
I feel like that would be a separate task. Does this plugin support checking other dependencies already?

**Comment by Tapchicoma** [comment]
Currently new MPP plugin is a little mess and it is not straightforward to get all source sets for given target. As for target dependOn source sets - it is not possible :disappointed: 

Anyway, as I said - I've opened separate issue for this.
