### ISSUE TITLE
ktlintApplyToIdea fails on Cannot resolve external dependency

### ISSUE THREAD

**Issue by jakub-tucek** [JLLeitschuh/ktlint-gradle#181]
Hi,

I am having issue with tasks ktlintApplyToIdea and ktlintApplyToIdeaGlobally in my project. Other tasks are running correctly and returns proper result but ktlintApplyToIdea returns:

```
Execution failed for task ':ktlintApplyToIdea'.
> Could not resolve all files for configuration ':ktlint'.
   > Cannot resolve external dependency com.github.shyiko:ktlint:0.29.0 because no repositories are defined.
     Required by:
         project :

```

My configuration of build.gradle.kts in root project:

```
buildscript {
    val kotlinVersion = "1.3.10"

    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
   ....
}
plugins {
    val ktlintPluginVersion = "6.3.1"

    id("com.gradle.build-scan") version "2.0.2"
    id("org.jlleitschuh.gradle.ktlint") version ktlintPluginVersion
}
subprojects {
    apply(plugin = "kotlin")
    apply(plugin = "org.jlleitschuh.gradle.ktlint")
   ....
   tasks {
        configure<KtlintExtension> {
            debug.set(true)
            verbose.set(true)
            android.set(false)
            outputToConsole.set(true)
            reporters.addAll(ReporterType.PLAIN, ReporterType.CHECKSTYLE)
            ignoreFailures.set(true)
            filter {
                exclude("**/generated/**")
                include("**/kotlin/**")
            }
        }
  }
}
```

I am using Gradle 4.10.2 and Gradle 5 with both having same result.
I tried adding ktlint dependency from error to buildscript.dependencies under classpath but I was unsucessful.

Do you know what is wrong? Thank you for answer.

**Comment by jakub-tucek** [comment]
My bad... I added repositories to:
```
allprojects {
   ...
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}
```

and it works great now. Thank you for help & and this project.

**Comment by pkubowicz** [comment]
@JLLeitschuh Your answer is wrong and this is a bug.

Gradle plugins should be isolated from compiling the code and their classpath is defined in `buildscript{}` block. Currently your plugin is polluting the code classpath.

Jakub's project did not have any sources in the root project and there is no sense in defining any repositories for the root project.

**Comment by Tapchicoma** [comment]
ehm, repositories was added only from build scripts, but not for compile code classpath.

**Comment by JLLeitschuh** [comment]
We intentionally don't modify the `buildscript` classpath with the Ktlint dependency. We put it on a custom configuration per-project intentionally so that when `ktlint` is resolved, it's got its own isolated classpath from the rest of Gradle.
