### ISSUE TITLE
Having trouble with ktlint config

### ISSUE THREAD

**Issue by beedub** [JLLeitschuh/ktlint-gradle#184]
Hey there,

I'm newer to Kotlin and Java, so please bear with me.

I'm having trouble getting the `ktlint` config to work with gradle. Specifically I'm trying to get the `filter.exclude` part working so that I can exclude a folder in the root of my project called `generated` to be excluded from ktlint gradle tasks.

The relevant section of `build.gradle` is here:

```
ktlint {
    version = "0.30.0"
    filter {
        exclude("**/generated/**")
    }
    debug = true
    verbose = true
}
```

I'm running the `ktlintCheck` task and not seeing `generated` files excluded. A few things I noticed:

* the version field doesn't seem like it's checked. it looks like it should be based on https://github.com/JLLeitschuh/ktlint-gradle/blob/3a1fb51fbb6f3a94a8c47ad25f3f16a9dc309cc9/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt
* changing `include` to `includee` causes an exception to be raised (so it looks like it's reading that block, atleast)
* the verbose output has no mention of any filtering

Assuming that https://github.com/JLLeitschuh/ktlint-gradle/blob/3a1fb51fbb6f3a94a8c47ad25f3f16a9dc309cc9/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt is the code that's being run, then where are the filtering rules applied? That file has no `include` or `exclude` as far as I can see.

Thanks for any help in advance!

**Comment by Tapchicoma** [comment]
Your config seems valid.

The best if you can provide link to the project. Or, at least, your project structure and `build.gradle` where you applied our plugin.

Also you can look on our sample project, where `filter.exclude` was applied: https://github.com/JLLeitschuh/ktlint-gradle/blob/master/samples/kotlin-ks/build.gradle.kts

> Assuming that /plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt@3a1fb51 is the code that's being run, then where are the filtering rules applied? That file has no include or exclude as far as I can see.

`KtlintCheckTask` extends [SourceTask](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/SourceTask.html) that implements [PatternFilterable](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/util/PatternFilterable.html). Later one adds filtering functionality.

`KtlintBasePlugin` passes to extension [function](https://github.com/JLLeitschuh/ktlint-gradle/blob/f40340a88e5daba0c68be264967b5fd431a4fd54/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintBasePlugin.kt#L18) that applies provided filter to each `KtlintCheckTask`

**Comment by Tapchicoma** [comment]
Feel free to reopen this issue if still have troubles with using this plugin.

**Comment by minseokLim** [comment]
I think it is still happening. Files generated by gradle task are not excluded.
