### ISSUE TITLE
Use Gradle 5.0

### ISSUE THREAD

**Issue by Tapchicoma** [JLLeitschuh/ktlint-gradle#185]
For now blocked by https://github.com/JetBrains/kotlin-native/issues/2440

**Comment by JLLeitschuh** [comment]
So we can't update to Gradle 5.0 internally currently? Can we run some of the tests against Gradle 5.0?

**Comment by Tapchicoma** [comment]
We can update plugin project to Gradle `5.0`, but leave samples on `4.10`.

**Comment by Tapchicoma** [comment]
Fixed via #235
