### ISSUE TITLE
Fail build only after all sources are checked.

### ISSUE THREAD

**Issue by Tapchicoma** [JLLeitschuh/ktlint-gradle#19]
When plugin runs checks it fails the build on first failed check task(for example, test sources) and doesn't run others checks(for example, main sources).

It becomes more inconvenient in multi-module projects.

Plugin should run all check tasks and fail build after all check tasks run if one or more of them are failed.

**Comment by JLLeitschuh** [comment]
I think this is normal for most plugins.
I think that [spotless](https://github.com/diffplug/spotless/tree/master/plugin-gradle) behaves the same way.

**Comment by wolfs** [comment]
How about using `--continue` when running the check tasks? This would cause all of the check tasks to run even if some of them failed.

**Comment by Tapchicoma** [comment]
@wolfs yep, should work. Will update `README.md` with this approach.
