### ISSUE TITLE
ktlintFormat is up-to-date when it shouldn't be

### ISSUE THREAD

**Issue by gabrielittner** [JLLeitschuh/ktlint-gradle#194]
To reproduce:
1. Do a small change that would be fixed by ktlint (e.g. inserting a space before a `,`) 
2. Run `gw ktlintFormat` 
3. The change should be undone now
4. Do the same change you did in 1 again
5. Run `gw ktlintFormat` again
-> The task will be up-to-date and the change still be there

**Comment by JLLeitschuh** [comment]
Diffplug spotless fixed this issue somehow, but I don't know how.

**Comment by gabrielittner** [comment]
I think they don't declare any outputs on their format task which means it's never up-to-date.

**Comment by Tapchicoma** [comment]
I'd say it is a pretty edge-case to run format task that fixes input, then undo changes to the same state before format task.

Personally, I don't think that disabling caching for format task is the solution.

**Comment by gabrielittner** [comment]
According to this comment a task that changes it's inputs should never be up to date https://github.com/diffplug/spotless/pull/45#discussion_r85655753
