### ISSUE TITLE
Non working `ktlint` settings block

### ISSUE THREAD

**Issue by igorwojda** [JLLeitschuh/ktlint-gradle#198]
Hello, 
I have added this config to project level `build.gradle.kts` file

```
ktlint {
    version.set("0.30.0")
    android.set(true)
    debug.set(true)
    verbose.set(true)
    outputToConsole.set(true)
    reporters.set(setOf(ReporterType.PLAIN, ReporterType.CHECKSTYLE))
}
```

However, all of the above settings are somehow ignored.
After clearing Gradle cache (removed `.gradle` in the user home directory) plugin still downloads ktlint "0.29.0" instead of "0.30.0" and none of the above options has any effect (no console output, not html report...). 

I use `7.0.0`, however, I am observing similar behavior in `6.3.1` 

Any ideas how to debug and fix it?

**Comment by igorwojda** [comment]
Simlfied `build.gradle.kts`
```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

buildscript {
    repositories {
        google()
        jcenter()

        //Ktlint Gradle
        maven("https://plugins.gradle.org/m2/")
    }

    dependencies {
        classpath("com.android.tools.build:gradle:3.2.1”)
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.20”)
        classpath("org.jlleitschuh.gradle:ktlint-gradle:7.0.0”)
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

subprojects {
    tasks.withType<Test> {
        maxParallelForks = Runtime.getRuntime().availableProcessors()
    }
}

plugins {
    id(org.jlleitschuh.gradle.ktlint) version “7.0.0”
}

//All kotlin modules
tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}

ktlint {
    version.set(“0.30.0”)
    android.set(true)
}

```

**Comment by Tapchicoma** [comment]
Indeed, from my investigation plugin always uses `0.29.0` version of ktlint.

Thank you for reporting this.

**Comment by Tapchicoma** [comment]
Though other plugin configuration settings works from my tests.

**Comment by Tapchicoma** [comment]
Try add `debug.set(true)` and check console output. It should produce something like this:
```
[DEBUG] Discovered ruleset "standard"
[DEBUG] Discovered reporter "plain"
[DEBUG] Discovered reporter "json"
[DEBUG] Discovered reporter "checkstyle"
[DEBUG] Initializing "plain" reporter with {verbose=true, color=true}
[DEBUG] Initializing "checkstyle" reporter with {verbose=true, color=true}, output=/user/ktlint-gradle/samples/kotlin-ks/build/reports/ktlint/ktlintMainSourceSetCheck.xml
[DEBUG] Initializing "json" reporter with {verbose=true, color=true}, output=/user/ktlint-gradle/samples/kotlin-ks/build/reports/ktlint/ktlintMainSourceSetCheck.json
[DEBUG] Checking /user/ktlint-gradle/samples/kotlin-ks/src/main/kotlin/org/jlleitschuh/gradle/ktlint/sample/kotlin/main.kt
[DEBUG] 1801ms / 1 file(s) / 0 error(s)
```

**Comment by igorwojda** [comment]
I can't see any `[DEBUG]` log lines

Here is new Android project with `rootProject.buildFileName = "build.gradle.kts"` added to `settings.gradle` and with kotlin build script (`build.gradle` -> `build.gradle.kts`) + ktlint-gradle configured. Please open it in Android Studio and run `./gradlew ktlintcheck`
[KtlintTest.zip](https://github.com/JLLeitschuh/ktlint-gradle/files/2828304/KtlintTest.zip)

BTW This version mismatch is very hard to spot. I only spotted if after fix for a bug was not working for me. Ideally, ktlint should add version in the report file, but for now, maybe you could display it in the log or add another grade task to get it?

**Comment by Tapchicoma** [comment]
> BTW  This version mismatch is very hard to spot. I only spotted if after fix  for a bug was not working for me. Ideally, ktlint should add version in  the report file, but for now, maybe you could display it in the log or  add another grade task to get it?

I will a test for this case, so new plugin updates should not break this behaviour.

**Comment by JLLeitschuh** [comment]
@igorwojda Nice find. Thanks for helping us figure out what was wrong.

**Comment by Tapchicoma** [comment]
@igorwojda extracted your `KtintTest.zip` example and run `./gradlew ktlintCheck`:
```
> Task :app:ktlintAndroidTestSourceSetCheck FAILED
/user/tmp/ktlint-test/KtlintTest/app/src/androidTest/java/onepayfx/com/ktlinttest/ExampleInstrumentedTest.kt:9:1: Wildcard import (cannot be auto-corrected)"plain" report written to /user/tmp/ktlint-test/KtlintTest/app/build/reports/ktlint/ktlintAndroidTestSourceSetCheck.txt
```
So ktlint-gradle setup is correct.

**Comment by igorwojda** [comment]
It works, but are you sure setup is correct?
1. `debug.set(true)` so we should see some `[DEBUG]` log lines, but they are not there
2. I we set reporter type `reporters.set(setOf(ReporterType.JSON, ReporterType.CHECKSTYLE))` we shout have report containing JSON, right? but tool only produces plain (`txt`) report (which does not contain JSON)

```
BUILD FAILED in 1s
1 actionable task: 1 executed
➜  KtlintTest ./gradlew ktlintcheck                                                                                                                                                                    -1-

> Task :app:ktlintAndroidTestSourceSetCheck FAILED
/Users/igor/StudioProjects/KtlintTest/app/src/androidTest/java/onepayfx/com/ktlinttest/ExampleInstrumentedTest.kt:9:1: Wildcard import (cannot be auto-corrected)
"plain" report written to /Users/igor/StudioProjects/KtlintTest/app/build/reports/ktlint/ktlintAndroidTestSourceSetCheck.txt
```

**Comment by Tapchicoma** [comment]
@igorwojda I've used your sample project that you have provided.

adding to `app/build.gradle`:
```gradle
ktlint {
    debug = true
}
```
enabled debug messages on `./gradlew ktlintCheck`

**Comment by igorwojda** [comment]
OK @Tapchicoma we are one step closer.

The reason it was not working for me was that I applied configuration to the project root`build.grdale` not module `app` module build.gradle` (README should be more specific about this).

So this is correct behavior indeed. However nowadays the Android projects are following multi-module structure eg.:

```
-root
---app
---feature1
---feature2
---feature3
...
---feature10
```

So I wonder if there is a way to apply ktlint-gradle the configuration to all of the modules or do we have to apply and maintain a configuration in each of the modules separately?
Some plugins allow to use [subproject](https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:subproject_configuration) (or allprojects) configuration in project root `build.gradle` file: 

```
subprojects {
    ktlint {
        debug.set(true)
    }
}
```

However teh above is not working with ktlint 🤔 Is there any way to make it work?

**Comment by Tapchicoma** [comment]
@igorwojda personally, for android projects, I am using something like this:
https://github.com/ultrasonic/ultrasonic/blob/develop/gradle_scripts/android-module-bootstrap.gradle that contains common modules setup. Here you can also add `ktlint-gradle` common configuration. Then in each module you just write: `apply from: ../android-module-bootstrap.gradle` and you are done.

The more generic solution would be - in your provided sample in root `build.gradle.kts` change to following:
```kotlin
subprojects {
    tasks.withType<Test> {
        maxParallelForks = Runtime.getRuntime().availableProcessors()
    }

    plugins.apply("org.jlleitschuh.gradle.ktlint")

    ktlint {
        version.set("0.30.0")
        android.set(true)
        debug.set(true)
        reporters.set(setOf(ReporterType.PLAIN, ReporterType.CHECKSTYLE))
    }
}
```

I would update project README with this approach.
