### ISSUE TITLE
.editorconfig change seems to be ignored

### ISSUE THREAD

**Issue by igorwojda** [JLLeitschuh/ktlint-gradle#209]
I am not sure if this is Ktlintgradle bug or ktlint itself.

I have a mono repo with multiple projects. `.editirconfig` exists in the root of mono repo, but The Android project does not have it's own `.editirconfig` file:

Monorepo root
- `.editirconfig`
    - `android`
    - `iOs`

it looks like changes to `.editirconfig` are ignored (due to cache?). 

Steps 
1. Run ktlint gradle inside Android project `./gradlew ktlintcheck` that should pass
2. Make change in the `.editirconfig` that should make ktlint check fail eg. add `indent_size = 2`
3. Run ktlint 

Result
All checks are OK

Expected results
Some checks should fail

I discovered that by editing one of the files in the Android project (let's say added unwanted space) the check will start failing, so this leads to a conclusion that maybe cache is not invalidated when the `.editirconfig` file is updated.

**Comment by igorwojda** [comment]
Another related problem is that after adding `.editirconfig` file to androdi prject it's content is ignored

Monorepo root
- `.editirconfig`
    - `android`
        - `.editirconfig`
    - `iOs`


This contridicts with `.editirconfig` docs that states:
```
Where are these files stored?
When opening a file, EditorConfig plugins look for a file named .editorconfig in the directory of the opened file and in every parent directory. A search for .editorconfig files will stop if the root filepath is reached or an EditorConfig file with root=true is found.

EditorConfig files are read top to bottom and the most recent rules found take precedence. Properties from matching EditorConfig sections are applied in the order they were read, so properties in closer files take precedence.
```

**Comment by Tapchicoma** [comment]
Interesting, according to this line in the task configuration: https://github.com/JLLeitschuh/ktlint-gradle/blob/0b019e0c0d99c2a34c2ff40fef61a1fefc21eebf/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt#L42 and this test: https://github.com/JLLeitschuh/ktlint-gradle/blob/0b019e0c0d99c2a34c2ff40fef61a1fefc21eebf/plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPluginTest.kt#L149 such issue should not happen.

I will try to recheck using your project layout if it is plugin issue or not.

**Comment by Tapchicoma** [comment]
Indeed I can reproduce this issue - will try to fix it.

**Comment by igorwojda** [comment]
I guess the issue is that in the `Check task should rerun if editorconfig content changed` test there is an assumption that top level `.editorconfig` always exists in the project root.

However editorconfig has it's own "root determination strategy" and can go few folders up above "idea project root"

**Comment by Tapchicoma** [comment]
Issue that `.editorconfig` file in project root is not considered as task input, so any changes to this file doesn't reset "UP-TO-DATE" task state.
