### ISSUE TITLE
Add support for editorconfig path

### ISSUE THREAD

**Issue by philippeagra** [JLLeitschuh/ktlint-gradle#210]
Hello,
it would be cool if we could configure the path of the `.editorconfig` file (using ktlint `--editorconfig` flag) within KtlintExtension.

**Comment by Tapchicoma** [comment]
You want to provide `.editorconfig` file that is placed outside project?

**Comment by philippeagra** [comment]
Indeed, I wanted to use an `.editorconfig` in the build folder (generated by an other plugin) to avoid having the same `.editorconfig` in all my projects. I know i can use a ruleset but i have to implement all the standard rule to avoid using the `.editorconfig` file.
