### ISSUE TITLE
7.1.0 - > 7.2.0

### ISSUE THREAD

**Issue by nwillc20019** [JLLeitschuh/ktlint-gradle#217]
Bumped version from 7.1.0 to 7.2.0 and getting:

No value has been specified for property 'android$ktlint_gradle'.

Am using kotlin jvm.  

Build is here: https://github.com/nwillc/ksvg/blob/master/build.gradle.kts

**Comment by JLLeitschuh** [comment]
Can you include a stack trace by running your build with `--stacktrace`?

**Comment by JLLeitschuh** [comment]
https://gist.github.com/PaulWoitaschek/19a1557166a77048ffbd9e0f88d957bf

**Comment by JLLeitschuh** [comment]
@Tapchicoma I'm guessing that we're not setting the `android` property for the script checker.

https://github.com/JLLeitschuh/ktlint-gradle/blob/477db4da31e9b339e60916d57c404d37553b47a7/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt#L55-L56

**Comment by Tapchicoma** [comment]
@JLLeitschuh yes, for kotlin script tasks android flag is disabled.

**Comment by Tapchicoma** [comment]
@nwillc20019 I've checked version `7.2.1` on ksvg repo - running `ktlintCheck` task completes successfully.
