### ISSUE TITLE
Filter not applied

### ISSUE THREAD

**Issue by derolf** [JLLeitschuh/ktlint-gradle#222]
I set include the following into my `buld.gradle`:

```
    ktlint {
        debug = true
        verbose = true
        filter {
            exclude("**/generated/**")
        }
    }
```

However, the files below generated are STILL checked:

```
$ ./gradlew ktlintCheck

> Task :nano-container:ktlintMainSourceSetCheck FAILED
[DEBUG] Discovered ruleset "standard"
[DEBUG] Discovered reporter "plain"
[DEBUG] Discovered reporter "json"
[DEBUG] Discovered reporter "checkstyle"
[DEBUG] Initializing "plain" reporter with {verbose=true, color=true}
[DEBUG] Initializing "plain" reporter with {verbose=true, color=true}, output=XXX/nano-container/build/reports/ktlint/ktlintMainSourceSetCheck.txt
[DEBUG] Checking XXX/nano-container/build/generated/source/BuildInfo.kt
...
[DEBUG] Discovered .editorconfig (XXX) {indent_size=2}
XXX/nano-container/build/generated/source/BuildInfo.kt:1:1: Wildcard import (cannot be auto-corrected) (no-wildcard-imports)
XXX/nano-container/build/generated/source/BuildInfo.kt:246:14: Missing spacing before "=" (op-spacing)
"plain" report written to XXX/nano-container/build/reports/ktlint/ktlintMainSourceSetCheck.txt
[DEBUG] 879ms / 6 file(s) / 2 error(s)
```

The file `XXX/nano-container/build/generated/source/BuildInfo.kt` should have been ignored.

```
 ./gradlew --version

------------------------------------------------------------
Gradle 5.2.1
------------------------------------------------------------

Build time:   2019-02-08 19:00:10 UTC
Revision:     f02764e074c32ee8851a4e1877dd1fea8ffb7183

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Linux 4.15.0-46-generic amd64

```

**Comment by Tapchicoma** [comment]
@derolf would be nice to provide sample project to reproduce the issue.

Have you applied this filter in `:nano-container` subproject or in the root project build file?

**Comment by derolf** [comment]
My main `build.gradle` looks like this:

```
apply plugin: "org.jlleitschuh.gradle.ktlint-idea"
apply plugin: "org.jlleitschuh.gradle.ktlint"

repositories {
    maven { url "https://plugins.gradle.org/m2/" }
}


subprojects {
    apply plugin: 'java'
    apply plugin: "idea"
    apply plugin: 'kotlin'
    apply plugin: "org.jlleitschuh.gradle.ktlint"

...

    repositories {
        mavenLocal()
        mavenCentral()
        jcenter()
    }


...


    ktlint {
        debug = true
        verbose = true
        filter {
            exclude("**/generated/**")
        }
    }
}

buildscript {
    ext.kotlin_version = '1.3.21'

    repositories {
        maven { url "https://plugins.gradle.org/m2/" }
    }

    dependencies {
...
        classpath "org.jlleitschuh.gradle:ktlint-gradle:7.2.1"
    }

}

```

**Comment by derolf** [comment]
Okay, I think I found the underlying issue.

Actually, `BuildInfo.kt` sits at `build/generated/source/BuildInfo.kt` and is added to the build via:

```
sourceSets.main.java.srcDir new File(buildDir, 'generated/source/')
```

But, if I do ...

```
        filter {
            exclude({println(it.path)})
        }
```

... it just prints `BuildInfo.kt`, so the prefix is stripped from the filename. I guess that string-patterns are applied to the stripped and not absolute path.

Here is the workaround:

```
    ktlint {
        filter {
            exclude({it.file.absolutePath.contains("/generated/")})
        }
    }
```

However that will kick in if there is any "/generated/" in the full path.

**Comment by derolf** [comment]
```
    ktlint {
        filter {
            exclude({projectDir.toURI().relativize(it.file.toURI()).path.contains("/generated/")})
        }
    }
```

This will exclude all files in the project that have `/generated/` in their path relative to the project directory. Worth adding to README?

**Comment by Tapchicoma** [comment]
> it just prints BuildInfo.kt, so the prefix is stripped from the filename.

This is how https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/util/PatternFilterable.html#exclude-groovy.lang.Closure- works. Your `Closure` should also receive intermediate directories.

> This will exclude all files in the project that have /generated/ in their path relative to the project directory. Worth adding to README?

IMHO - no. This issue is pretty specific how you add generate sources. More proper way of adding additional sources would be:
```gradle
sourceSets.main.java.srcDirs "$buildDir/generated/source/"
```

**Comment by adamsmd** [comment]
For anyone else who finds this thread looking for a solution, the Ktlint FAQ has a recommendation: https://pinterest.github.io/ktlint/dev-snapshot/faq/#how-do-i-disable-ktlint-for-generated-code

In short, add the following to your `.editorconfig`, where the path is a relative path:
```EditorConfig
[some/path/to/generated/code/**/*]
ktlint = disabled
```

This may not work for everyone's situation, and I think it is unfortunate that I can't just use the Gradle `filter`, but it was the one thing that worked reliably for me, so I wanted to share in hopes it is useful to others.
