### ISSUE TITLE
Consider breaking inheritance hierarchy from `KtlintCheckTask` and `KtlintFormatTask`

### ISSUE THREAD

**Issue by mkobit** [JLLeitschuh/ktlint-gradle#225]
https://github.com/JLLeitschuh/ktlint-gradle/blob/90b0c63d3e6dac9a46b85a777a287553917fab8d/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintFormatTask.kt#L14-L16

https://github.com/JLLeitschuh/ktlint-gradle/blob/90b0c63d3e6dac9a46b85a777a287553917fab8d/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintCheckTask.kt#L33-L35

When doing something like

```kotlin
withType<KtlintCheckTask> {
  // use task
}
```

It was unexpected for me to also get all of the `KtlintFormatTask` tasks and configure them too.

**Comment by JLLeitschuh** [comment]
Agreed
