### ISSUE TITLE
Always fail task on Ktlint crash

### ISSUE THREAD

**Issue by tasomaniac** [JLLeitschuh/ktlint-gradle#229]
I've noticed that while running any of the `KtlintCheck` tasks, if running ktlint executable fails, the task is not marked as failure. 

Here is an example with incompatibility with Kotlin 1.3.30

```

> Task :project:ktlintMainSourceSetCheck
Exception in thread "main" java.lang.NoSuchFieldError: PROPERTY_DELEGATE
	at com.github.shyiko.ktlint.core.ast.ElementType.<clinit>(ElementType.kt:33)
	at com.github.shyiko.ktlint.ruleset.standard.ChainWrappingRule.<init>(ChainWrappingRule.kt:36)
	at com.github.shyiko.ktlint.ruleset.standard.StandardRuleSetProvider.get(StandardRuleSetProvider.kt:12)
	at com.github.shyiko.ktlint.Main.main(Main.kt:310)
```

The exception is recorded, ktlint actually does not run, but the task is marked as success.

**Comment by Tapchicoma** [comment]
@tasomaniac could it happen that you have enabled `ignoreFailuers` in `ktlint-gradle` extension?

```kotlin
val ignoreFailures: Property<Boolean> = objectFactory.property { set(false) }
```

**Comment by tasomaniac** [comment]
Hmm actually I did and then I have another task of myself that evaluates the `xml` reports.

I wonder if there is a way to differentiate `failures` and `errors` though. I would like to ignore failures resulting from a successful run of the ktlint task. But not for errors that causes `ktlint` task to crash and never run. 

I'm not sure if this is technically possible but would be good to differentiate these two scenarios.

**Comment by Tapchicoma** [comment]
I doubt that it will be possible, but will try to investigate.

**Comment by tasomaniac** [comment]
I can also have a look if you agree that it's a good idea

**Comment by Tapchicoma** [comment]
Feel free to do it. I think it is a good idea to fail the build on ktlint crash when `ignoreFailures` is enabled.

**Comment by JLLeitschuh** [comment]
Is this still an issue? Has it been resolved?

**Comment by tasomaniac** [comment]
I believe this is technically still an issue. But not sure how important it is. 

One way to solve this would be to create an xml report and include the execution issues as errors there. I think Android Lint does that.

**Comment by JLLeitschuh** [comment]
Are you able to create a demo or, even better, a unit test that demonstrates this issue?
