### ISSUE TITLE
Add support for new incremental task api

### ISSUE THREAD

**Issue by Tapchicoma** [JLLeitschuh/ktlint-gradle#231]
Gradle `5.4.0` has introduced new Incremental task api: https://docs.gradle.org/5.4/release-notes.html

Plugin should use it to run ktlint checks only on changed files.

**Comment by JLLeitschuh** [comment]
@Tapchicoma Will this mean that we will be dropping support for Gradle versions below 5.4.0 or do we want to dual support both?
