### ISSUE TITLE
Run Windows CI Jobs

### ISSUE THREAD

**Issue by JLLeitschuh** [JLLeitschuh/ktlint-gradle#232]
Would be good to integrate Windows CI jobs into our pipeline to sanity check that everything still works regardless of OS.

https://azure.microsoft.com/en-us/services/devops/pipelines/

**Comment by Tapchicoma** [comment]
@JLLeitschuh what do you think about migrating this repo to [Github actions](https://github.com/JLLeitschuh/ktlint-gradle/actions)?

It has linux/windows/macos runners.
