### ISSUE TITLE
Fails to run ktlint on over 3000 kotlin files in sourceset

### ISSUE THREAD

**Issue by Tapchicoma** [JLLeitschuh/ktlint-gradle#233]
Plugin fails to run check/format tasks, when source set contains over 3000 kotlin files.

Currently plugin passes each file to `ktlint` and in this case may hit command line arguments limitation. (at least on Windows or MacOS).

Opened after discussion in #156

**Comment by Tapchicoma** [comment]
Possible solution would be leverage workers api and launch several javaexec tasks that checks limited amount of files.

**Comment by JLLeitschuh** [comment]
So, Spotless has avoided this by going the reflection route to call the ktlint process. Not totally certain that's the right route either.

RE the worker solution, can you force a certain number of workers to get generated?

Even without the worker API, couldn't you just fire off sequential formatters once we pass 3,000 files?

I know that Ktlint uses the Kotlin Compiler API under the hood, but does it also rely on the local Kotlin compiler daemon or is it all in-process?

**Comment by Tapchicoma** [comment]
I don't like to use reflection - kind of fragile.

> RE the worker solution, can you force a certain number of workers to get generated?

I guess (can't find it in documentation) it is limited to the number of available Gradle processes. 

Also problem with running ktlint multiple times is how then assemble the report into one? Possibly adding last task action that copies it from all generated reports into one file.

> I know that Ktlint uses the Kotlin Compiler API under the hood, but does it also rely on the local Kotlin compiler daemon or is it all in-process?

Have not idea, but I saw that https://github.com/jeremymailen/kotlinter-gradle already uses worker api: https://github.com/jeremymailen/kotlinter-gradle/blob/87d8196697b2c3d9cf31baf47b8077c0bf17912e/src/main/kotlin/org/jmailen/gradle/kotlinter/tasks/LintTask.kt#L82, so it should work.

**Comment by JLLeitschuh** [comment]
Alternatively, we could PR upstream Ktlint to support being fed a file with all of the file names to lint inside of it.

**Comment by r-ralph** [comment]
JFYI: the maximum length of command line arguments is little different by OS.
- Windows: 8,192 characters (http://support.microsoft.com/kb/830473)
- Mac: 262,214 characters (depend on `getconf ARG_MAX` and might be dieerent between machine)
- Ubuntu: 2,097,152 characters (depend on `getconf ARG_MAX` and might be dieerent between machin)

I've counted with my project that is showed in #156's comment, it require about 290,000 characters.

**Comment by Tapchicoma** [comment]
Actually adding such parameter type to ktlint should help in this case:
https://picocli.info/man/3.x/#AtFiles

**Comment by DemonWav** [comment]
Note that this can happen with considerably fewer files - happens to me with  523 Kotlin files https://ci.appveyor.com/project/DemonWav/minecraftdev#L352

**Comment by Tapchicoma** [comment]
@DemonWav I see your CI is working on Windows machine that has to smallest command line arguments limit. If you count full path to each kotlin file - most probably it is easy to reach the limit.

But yeah, this limitation is kind of annoying.

**Comment by DemonWav** [comment]
Yeah for now I'm just skipping the `ktlintMainSourceSetCheck` for my Windows build.
