### ISSUE TITLE
Execution failed for task ':ktlintMainSourceSetCheck'

### ISSUE THREAD

**Issue by ElenaSpb** [JLLeitschuh/ktlint-gradle#234]
[gradle build --stacktrace.txt](https://github.com/JLLeitschuh/ktlint-gradle/files/3116629/gradle.build.--stacktrace.txt)

Gradle 5.2.1

**Comment by ElenaSpb** [comment]
[build - Copy.gradle.txt](https://github.com/JLLeitschuh/ktlint-gradle/files/3116635/build.-.Copy.gradle.txt)

**Comment by ElenaSpb** [comment]
> Task :ktlintMainSourceSetCheck FAILED
C:\kotlin projects\kotlin_code_style\src\main\kotlin\Data.kt:1:1: class BankAccountData should be declared in a file named BankAccountData.kt (cannot be auto-corrected)
"plain" report written to C:\kotlin projects\kotlin_code_style\build\reports\ktlint\ktlintMainSourceSetCheck.txt

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ktlintMainSourceSetCheck'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_211\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ktlintMainSourceSetCheck'.

**Comment by Tapchicoma** [comment]
@ElenaSpb what task are you running - `ktlintCheck`?

**Comment by Tapchicoma** [comment]
Also task fails, because `ktlint` fails:
```
C:\kotlin projects\kotlin_code_style\src\main\kotlin\Data.kt:1:1: class BankAccountData should be declared in a file named BankAccountData.kt (cannot be auto-corrected)
```

Change class name from `Data` to `BankAccountData` and it should pass the check.

**Comment by Tapchicoma** [comment]
Feel free to reopen this issue, if you still have problems.

**Comment by irfanirawansukirman** [comment]
hi @Tapchicoma i'm getting error like this:

 What went wrong:
Execution failed for task ':mainapp:ktlintMainSourceSetCheck'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

**Comment by Tapchicoma** [comment]
@irfanirawansukirman check generated reports, most probably your code has code style violations (exit value 1).

Also please check this issue: https://github.com/JLLeitschuh/ktlint-gradle/issues/313
