### ISSUE TITLE
Latest version not published

### ISSUE THREAD

**Issue by manijshrestha** [JLLeitschuh/ktlint-gradle#24]
Latest version 2.2.0 is not yet published in the plugin repo. Can you please publish it?
https://plugins.gradle.org/plugin/org.jlleitschuh.gradle.ktlint

**Comment by JLLeitschuh** [comment]
What do you know. You are absolutely correct. Sorry about that.

**Comment by JLLeitschuh** [comment]
Still on my todo list.

**Comment by JLLeitschuh** [comment]
Published, sorry this took so long. This is something I absolutely need to automate with travis CI.
