### ISSUE TITLE
Can ktlint be applied to some of the modules?

### ISSUE THREAD

**Issue by apuli** [JLLeitschuh/ktlint-gradle#242]
I work in a multiple modules app, each module is handled by a different team. My team would like to apply ktlint to our module, but not to affect the others, is that possible?

**Comment by Tapchicoma** [comment]
Definitely!

In you main project `build.gradle.kts` add following:
```kotlin
plugins {
  id "org.jlleitschuh.gradle.ktlint" version "<current_version>" apply false
}
```

and then add following line to `build.gradle.kts` in that modules, where you want to use ktlint:
```kotlin
plugins {
    id("org.jlleitschuh.gradle.ktlint")
}
```

Then plugin tasks will run only on the modules where plugin has been applied.

**Comment by JLLeitschuh** [comment]
This is absolutely somethign we want and expect to work, if it doesn't please let us know.

**Comment by Tapchicoma** [comment]
Fell free to open new issue, if solution has not worked for you.

**Comment by ianbondoc** [comment]
This does not work for project that don't have kotlin plugin in the root, our project is multi module and only a single module is a using kotlin, the root project only has base as the gradle plugin, apply false then applying the plugin in the kotlin submodule result in the following:

`Unable to load class 'org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension'.`

**Comment by JLLeitschuh** [comment]
Are you able to create a minimal reproducer demonstrating this bug? I'm wondering if this is caused by some sort of classloader weirdness in Gradle. What version of Gradle are you encountering this with?
