### ISSUE TITLE
Possible to enforce code blocks?

### ISSUE THREAD

**Issue by mmeister1203** [JLLeitschuh/ktlint-gradle#243]
Hello, is it possible to use this plugin to enforce code blocks on if statements? For example, the following is valid syntax

`if (true) doSomething()`

However I'd like to enforce it so that we must write it as:

`if (true) {`
      `doSomething()`
`}`

Any help would be appreciated. Thanks!

This is for Android FYI. Kotlin.

**Comment by JLLeitschuh** [comment]
This project is purely the Gradle plugin for Ktlint, not Ktlint itself. Please open an issue against the upstream project https://github.com/pinterest/ktlint

You may want to look into creating a custom ruleset: https://github.com/pinterest/ktlint#creating-a-ruleset

Closing this as a question, if you have problems integrating a custom ruleset with this plugin, please feel free to open a new issue.
