### ISSUE TITLE
Global check for Multi-Project Builds

### ISSUE THREAD

**Issue by Globegitter** [JLLeitschuh/ktlint-gradle#248]
I am quite new to kotlin and gradle so maybe there is something I am misconfiguring but I would like to be able to apply the plugin "globally", i.e. that running `gradle check/ktlintCheck` runs on the sources of all my projects. I managed to define things in such a way that I get a `gradle project:check` task for each project but it is still quite tedious to have to run it for each project.

If I create a ktlint task myself, e.g.
```
task("execute", JavaExec::class) {
    group = "verification"
    description = "Check Kotlin code style."
    main = "com.pinterest.ktlint.Main"
    classpath(configurations.ktlint)
    args("--experimental")
}
```

it runs on all of my sources.

**Comment by JLLeitschuh** [comment]
If you have the plugin installed in your subprojects, you should always be able to execute it from the root and run all of the tasks with that name in all subprojects.

**Comment by Tapchicoma** [comment]
@Globegitter check this section of README: https://github.com/JLLeitschuh/ktlint-gradle#applying-to-subprojects

**Comment by Globegitter** [comment]
That for some reason does not work for me. I have the following root-level `build.gradle.kts`:

```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    base
    kotlin("jvm") version "1.3.11"
    id("org.jlleitschuh.gradle.ktlint") version "8.0.0"
}

allprojects {
    group = "somegroup"

    version = "1.0"

    repositories {
        jcenter()
        mavenCentral()
        maven("https://jitpack.io")
    }

    tasks.withType(KotlinCompile::class.java).all {
        kotlinOptions.jvmTarget = "1.8"
    }
}

subprojects {
    apply(plugin = "org.jlleitschuh.gradle.ktlint") // Version should be inherited from parent

    // Optionally configure plugin
    ktlint {
        version.set("0.33.0")
        enableExperimentalRules.set(true)
    }
}

dependencies {
    subprojects.forEach {
        archives(it)
    }
}
```

And running `gradle check` only runs in the top-level project and the `gradle subproject:check` commands of course only in the subprojects. Should `gradle check` run the check commands for all subprojects or is there something else I am missing?

**Comment by Tapchicoma** [comment]
Your `build.gradle` looks ok.

You can check what actual tasks will run by using following command:
```sh
$ ./gradlew -m check
```

Running `check` task should also trigger ktlint-gradle tasks.

**Comment by Globegitter** [comment]
Ahhh I found the issue. It does indeed run check on all subproject but what tripped me up is that it stops on the first project that errored. So I had an error on my root level project so it never showed any errors on the subprojects. Is there some way to tell gradle to keep going and just show all errors from all subprojects?

**Comment by Tapchicoma** [comment]
Pass yo Gradle `--continue` option

**Comment by Globegitter** [comment]
Yep that works - thanks for the responses.
