### ISSUE TITLE
Standard output is not closed

### ISSUE THREAD

**Issue by hmiyado** [JLLeitschuh/ktlint-gradle#25]
https://github.com/JLLeitschuh/ktlint-gradle/blob/6b6fca879980534c3de94c37a259c205fc44d235/src/main/kotlin/org/jlleitschuh/gradle/ktlint/Reporter.kt#L26

Standard output is opened at this code but this stream is not closed.

**Comment by JLLeitschuh** [comment]
Is it supposed to be? Doesn't Gradle do this for you?

**Comment by hmiyado** [comment]
I cannot delete ktlint.xml because of `java.io.IOException`.
I tried a little research, and found ktlint sample code(below).
In it, standardOutput is closed explicitly.

```kotlin
task ktlintGenerateCheckstyleXML(type: Exec) {
  commandLine 'java', '-cp', configurations.ktlint.join(System.getProperty('path.separator')),
    'com.github.shyiko.ktlint.Main', '--reporter=checkstyle', 'src/**/*.kt'
  standardOutput = new FileOutputStream(new File(buildDir, "ktlint-checkstyle-report.xml"))
  ignoreExitValue = true
  doLast {
    standardOutput.close()
    if (execResult.exitValue != 0) {
      throw new GradleException("ktlint finished with non-zero exit value ${execResult.exitValue}")
    }
  }
}
```

**Comment by Tapchicoma** [comment]
@hmiyado you are right, need to add explicit close.

I will fix it.
