### ISSUE TITLE
Plugin doesn't work for dynamic-feature modules

### ISSUE THREAD

**Issue by SergiyKorotun** [JLLeitschuh/ktlint-gradle#260]
In root build.gradle I have a configuration :

```gradle
dependencies {
    classpath "org.jlleitschuh.gradle:ktlint-gradle:8.1.0"
}
subprojects {
    apply plugin: "org.jlleitschuh.gradle.ktlint"

    // Optionally configure plugin
    ktlint {
        debug = true
        verbose = true
        outputToConsole = true
        android = true
    }
}
```

But kotlinCheck task works only for the main app module.
Seems the plugin skips sources for all non main modules.

Any suggestions?

**Comment by Tapchicoma** [comment]
Yes, currently plugin is missing support for `com.android.dynamic-feature` android plugin :+1:

**Comment by Tapchicoma** [comment]
@SergiyKorotun please try "8.2.0" version of plugin - it should now work with android dynamic modules.

**Comment by SergiyKorotun** [comment]
@Tapchicoma , thanks
