### ISSUE TITLE
Custom rules not working as expected

### ISSUE THREAD

**Issue by eschlenz** [JLLeitschuh/ktlint-gradle#261]
### High Level Description

Custom rules do not seem to be working, and I'm wondering if there was possibly a regression introduced at some point. I couldn't get custom rules to work in my own personal project, so I cloned this project to investigate. My testing has largely been done based on the work of PR #237

### Steps to Reproduce

1. Clone this project: `https://github.com/JLLeitschuh/ktlint-gradle.git`
1. Open the `main.kt` file in the `src` folder of the `kotlin-rulesets-using` subproject.
1. Per the comment on line 5, uncomment line 6 which uses a `var`. (https://github.com/JLLeitschuh/ktlint-gradle/blob/master/samples/kotlin-rulesets-using/src/main/kotlin/org/jlleitschuh/gradle/ktlint/sample/kotlin/main.kt)
1. From the root project, run `./gradlew clean ktlintCheck`.

**Observe:** The uncommented `var` is not flagged as a violation.
**Expectation:** The custom rule `NoVarRule.kt` defined in `kotlin-rulesets-creating` would be exercised, and would flag the `var` use violation.

Am I doing something incorrectly? It seems broken to me.

cc @Tapchicoma

**Comment by Tapchicoma** [comment]
Actually it is a bug in ruleset implementation - file https://github.com/JLLeitschuh/ktlint-gradle/blob/master/samples/kotlin-rulesets-creating/src/main/resources/META-INF/services/com.github.shyiko.ktlint.core.RuleSetProvider should be renamed to "com.pinterest.ktlint.core.RuleSetProvider"

After renaming `:samples:kotlin-ruleset-using:ktlintCheck` task starts to fail.

**Comment by eschlenz** [comment]
Aha! I can open a pr to fix it if you'd like.

**Comment by Tapchicoma** [comment]
Feel free to do it :+1:

**Comment by eschlenz** [comment]
Here it is: https://github.com/JLLeitschuh/ktlint-gradle/pull/262

**Comment by dondod** [comment]
This no longer works for me now.
