### ISSUE TITLE
Support `--disabled_rules`

### ISSUE THREAD

**Issue by dagguh** [JLLeitschuh/ktlint-gradle#267]
Please support `--disabled_rules`.

I need it to disable `no-wildcard-imports`, because IntelliJ keeps adding in the dreaded `java.util.*` due to its misguided `Packages to Use Import with '*'` feature.

**Comment by Tapchicoma** [comment]
I suppose, using `.editorconfig` (even external to repo) is not an option for you?

**Comment by dagguh** [comment]
`.editorconfig` is definitely an option, but I failed to find a working setting

**Comment by Tapchicoma** [comment]
If you put following `.editorconfig` file in your project root:
```editorconfig
[*.{kt,kts}]
disabled_rules=no-wildcard-imports
```
then it should automatically picked up by `ktlint`. No additional configuration to `ktlint-gradle` plugin is required.

**Comment by dagguh** [comment]
So `disabled_rules=no-wildcard-imports` works *iff* `ktlint.enableExperimentalRules.set(true)`. Thanks for the pointer!
I believe this is functionally done, so I'll close it.

**Comment by Tapchicoma** [comment]
Most probably in your previous attempts you've bumped into https://github.com/pinterest/ktlint/issues/555

**Comment by dagguh** [comment]
I didn't bump into that, but I simply didn't enable experimental features

**Comment by dagguh** [comment]
Hah, I ran into https://github.com/pinterest/ktlint/issues/555 right now 😆

**Comment by fpavageau** [comment]
As I have a Gradle plugin which configures `ktlint-gradle` (and some other plugins), I would definitely welcome the support of `--disabled_rules` to avoid repeating the same configuration via `.editorconfig` in each and every project (in my case, `import-ordering`).

**Comment by Tapchicoma** [comment]
@fpavageau this is valid reason to add such support for ktlint-gradle :+1:

**Comment by Globegitter** [comment]
Very strange, I just switched to the latest version of the plugin and disabling "no-wildcard-import" does not work. I have the following config:

```
ktlint {
    enableExperimentalRules.set(true)
    disabledRules.set(setOf("experimental:package-name", "no-wildcard-import"))
}
```

It disables the package name rule just fine (I can see package name errors otherwise), but I am still seeing

```
> Task :app:ktlintMainSourceSetCheck FAILED
/.../app/src/main/kotlin/name/app/App.kt:29:1: Wildcard import (cannot be auto-corrected)
```

Putting `disabled_rules = experimental:package-name,no-wildcard-imports` into the .editorconfig file  however is working just fine. It is working now, so ultimately it is fine but any idea what could be going on here?

**Comment by Tapchicoma** [comment]
@Globegitter you have a typo in rule id here:
```kotlin
    disabledRules.set(setOf("experimental:package-name", "no-wildcard-import"))
```

Correct id is "no-wildcard-imports".
