### ISSUE TITLE
Apply styles to multiple file extensions in one go

### ISSUE THREAD

**Issue by igorwojda** [JLLeitschuh/ktlint-gradle#269]
I am not 100% sure if this is ktlint-gradle problem, but it looks like `multiple file extensions` syntax (`[*.{kt, kts}]`) is ignored in the `.editorconfig` file:

This works
```
[*]
end_of_line = lf
insert_final_newline = true
indent_size = 4
max_line_length = 120
```

This does not work
```
[*.{kt, kts}]
end_of_line = lf
insert_final_newline = true
indent_size = 4
max_line_length = 120
```

More info https://github.com/editorconfig/editorconfig/issues/113#issuecomment-20853792

version `8.2.0`

**Comment by Tapchicoma** [comment]
Try to remove space in glob definition: `[*.{kt,kts}]`

**Comment by Tapchicoma** [comment]
Ktlint uses custom `.editorconfig` parser that is not working well, I've tried to address this problem in https://github.com/pinterest/ktlint/pull/561 PR.

**Comment by igorwojda** [comment]
Works without space.

BTW It's a bit tricky for me because my IDE reformats code on save...and add the space.
