### ISSUE TITLE
Failing github actions

### ISSUE THREAD

**Issue by JLLeitschuh** [JLLeitschuh/ktlint-gradle#274]
The Github Actions are failing with a class not found error:

https://github.com/JLLeitschuh/ktlint-gradle/commit/14aaba920a88feba178f1b304b64c2fdb316a692/checks#step:4:803

This may be related to this?
https://youtrack.jetbrains.com/issue/KT-29805

**Comment by Tapchicoma** [comment]
Possibly. At least, it is the only "related" ticket that I manager to found as well. Though ticket states that it is fixed.

Imho, better to open a separate Kotlin issue as the failure slightly different.

**Comment by Tapchicoma** [comment]
Updating Kotlin version seems solved this.
