### ISSUE TITLE
additionalEditorconfigFile does not seem to load configuration 

### ISSUE THREAD

**Issue by sannysinghs** [JLLeitschuh/ktlint-gradle#279]
```
ktlint {
    version = "0.34.2" //ktlint version
    debug = true
    verbose = true
    android = true
    outputToConsole = true
    reporters = [ReporterType.PLAIN_GROUP_BY_FILE, ReporterType.CHECKSTYLE]
    additionalEditorconfigFile = file(".editorconfig")
    ignoreFailures = false
    enableExperimentalRules = false
}
```
### console output 
```
[DEBUG] Discovered ruleset "standard"
[DEBUG] Discovered reporter "plain"
[DEBUG] Discovered reporter "json"
[DEBUG] Discovered reporter "checkstyle"
[DEBUG] Initializing "plain" reporter with {verbose=true, color=true}
```

### ..editorconfig (in same folder)
```[*.{kt,kts}]

insert_final_newline=false
``` 

I disabled `newline` at end of each file but rule is not applied

**Comment by Tapchicoma** [comment]
`.editorconfig` in same folder should be automatically picked up by ktlint. `additionalEditorconfigFile` exists to be able to provide `.editorconfig` files that are located outside project folder.

Your `.editorconfig` content should be:
```editorconfig
[*.{kt,kts}]
insert_final_newline=false
```

**Comment by sannysinghs** [comment]
I fixed my issue by defining complete path to `/home/...../proejct/.editorcofig` . Also added `[*.{kt,kts}]` in .editorconfig. Thanks @Tapchicoma  for prompt response
