### ISSUE TITLE
Unable to specify any reporter if ktlint version is bigger than "0.9.x"

### ISSUE THREAD

**Issue by leinardi** [JLLeitschuh/ktlint-gradle#28]
There seems to be a bug that prevents you from using a custom reporter when ktlint version is bigger than "0.9.x", eg. "0.10.1".

This is due to comparing strings instead of integers:

```
private fun isReportAvailable(version: String, availableSinceVersion: String): Boolean {
    val versionsNumbers = version.split('.')
    val reporterVersionNumbers = availableSinceVersion.split('.')
    return versionsNumbers[0] >= reporterVersionNumbers[0] &&
            versionsNumbers[1] >= reporterVersionNumbers[1] &&
            versionsNumbers[2] >= reporterVersionNumbers[2]
}
```
To reproduce the issue you can use this configuration:
```
ktlint {
    version = "0.10.1"
    debug = true
    verbose = false
    reporter = "json"
    ignoreFailures = true
}
```
The output is:
```
> Task :app:ktlintItalyCheck
[DEBUG] Discovered ruleset "standard"
[DEBUG] Discovered reporter "plain"
[DEBUG] Discovered reporter "json"
[DEBUG] Discovered reporter "checkstyle"
[DEBUG] Initializing "plain" reporter with {verbose=false}
[DEBUG] {} loaded from .editorconfig
[...]
```

**Comment by JLLeitschuh** [comment]
@Tapchicoma you want to take a crack at this one? Can you add some simple Junit tests that cover this too for us?

**Comment by Tapchicoma** [comment]
@JLLeitschuh yeah, I will take a look. 

In version `0.10.0` ktlint introduced multiple reporters support. I think this is the cause.

**Comment by JLLeitschuh** [comment]
@Tapchicoma Hijacking this issue for a second, come chat with me either in the [gitter chat](https://gitter.im/ktlint-gradle/Lobby) or find me in the [Kotlin Slack](http://slack.kotlinlang.org/).

**Comment by leinardi** [comment]
Quick and dirty fix:
```
private fun isReportAvailable(version: String, availableSinceVersion: String): Boolean {
    val versionsNumbers = version.split('.')
    val reporterVersionNumbers = availableSinceVersion.split('.')
    return versionsNumbers[0].toInt() >= reporterVersionNumbers[0].toInt() &&
            versionsNumbers[1].toInt() >= reporterVersionNumbers[1].toInt() &&
            versionsNumbers[2].toInt() >= reporterVersionNumbers[2].toInt()
}
```

**Comment by JLLeitschuh** [comment]
We may want to consider doing our parsing with this library:
https://github.com/zafarkhaja/jsemver.
Might be overkill though.

**Comment by Tapchicoma** [comment]
@leinardi little improve your fix, but solution is right.
