### ISSUE TITLE
ktlintCheck does not respect -P$FILTER_INCLUDE_PROPERTY_NAME

### ISSUE THREAD

**Issue by idiot-types** [JLLeitschuh/ktlint-gradle#287]
m@desktop:~/Workspace/Android/Sandbox/CasterIO/MVI/Users$ ./gradlew  ktlintCheck -P$FILTER_INCLUDE_PROPERTY_NAME="app/src/main/java/sandbox/users/model/UsersState.kt\n"

> Task :app:ktlintTestSourceSetCheck FAILED
/home/m/Workspace/Android/Sandbox/CasterIO/MVI/Users/app/src/test/java/sandbox/users/ExampleUnitTest.kt:17:40: Unnecessary space(s)
/home/m/Workspace/Android/Sandbox/CasterIO/MVI/Users/app/src/test/java/sandbox/users/ExampleUnitTest.kt:20:37: Unexpected spacing before ":"
/home/m/Workspace/Android/Sandbox/CasterIO/MVI/Users/app/src/test/java/sandbox/users/ExampleUnitTest.kt:29:32: Missing spacing after ","
/home/m/Workspace/Android/Sandbox/CasterIO/MVI/Users/app/src/test/java/sandbox/users/ExampleUnitTest.kt:31:1: Unexpected blank line(s) before "}"
/home/m/Workspace/Android/Sandbox/CasterIO/MVI/Users/app/src/test/java/sandbox/users/model/ModelStoreTest.kt:44:1: Unexpected blank line(s) before "}"

As it can be seen, it scans other files as well

**Comment by Tapchicoma** [comment]
Actually this parameter should only be used by git hook. Though correct invocation is:
```bash
$ ./gradlew ktlintCheck -PinternalKtlintGitFilter="app/src/main/java/sandbox/users/model/UserState.kt"
```

**Comment by idiot-types** [comment]
@Tapchicoma Indeed. Thank you. Actually the reason I asked this was I couldn't find addKtlintCheckGitPreCommitHook with the standard setup 

```
dependencies {
        classpath "org.jlleitschuh.gradle:ktlint-gradle:$ktlint_version"
}

plugins {
    id 'org.jlleitschuh.gradle.ktlint'
}

m@desktop:~/Workspace/Android/Sandbox/CasterIO/MVI/Users$ ./gradlew tasks | grep -i ktlint
ktlintDebugFormat - Runs ktlint formatter on all kotlin sources for android debug variant in this project.
ktlintFormat - Runs the ktlint formatter on all kotlin sources in this project.
ktlintReleaseFormat - Runs ktlint formatter on all kotlin sources for android release variant in this project.
ktlintCheck - Runs ktlint on all kotlin sources in this project.
ktlintDebugCheck - Runs ktlint on all kotlin sources for android debug variant in this project.
ktlintReleaseCheck - Runs ktlint on all kotlin sources for android release variant in this project.


```

Anyway, thanks!

**Comment by Tapchicoma** [comment]
`addKtlintCheckGitPreCommitHook` this task will be added when plugin is also applied to the gradle root project and root project directory has `.git/` subdirectory.

Possibly you may be affected by #284 issue.
