### ISSUE TITLE
Is it possible to pass our own command line arguments?

### ISSUE THREAD

**Issue by AdamMc331** [JLLeitschuh/ktlint-gradle#290]
I am uncertain if this is supported and I couldn't find anything in the README for it. The scenario I'm trying to account for is if ktlint bumps a version with a new command argument but this plugin hasn't updated yet. Thankfully we can specify the ktlint version ourselves, but I'm not sure I would be able to account for a new flag. The one in question, if it matters, is this PR that was just merged: https://github.com/pinterest/ktlint/pull/585#issue-318462724

I'm happy to contribute to the solution, I'm just not sure if:

- This is not possible, so I should wait until ktlint is updated (which I have to do regardless) and then submit a PR into the plugin.
- This is supported, and we should update the README to explain how we can do this.
- This is not supported, so I should explore ways we can implement such capabilities. 

Let me know what I can do to help. Thanks!

**Comment by AdamMc331** [comment]
Cool, thanks for the feedback! Should we close this and open a new ticket to support color-name when the time comes? That seems better than editing this so the question doesn't get lost.

**Comment by Tapchicoma** [comment]
> Should we close this and open a new ticket to support color-name when the time comes?

Yes, would be nice.
