### ISSUE TITLE
Name of the task `ktlint` and the extension `ktlint` collide

### ISSUE THREAD

**Issue by JLLeitschuh** [JLLeitschuh/ktlint-gradle#3]
The name of the task and the name of the extension collide causing problems with certain API's.
This should be fixed, unfortunately, it would be an API breaking change.

**Comment by erikthered** [comment]
Yeah this definitely causes failures for things like:

`check.dependsOn ktlint` 

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':check'.
> Cannot convert org.jlleitschuh.gradle.ktlint.KtlintExtension_Decorated@6402d76e to a task.
  The following types/formats are supported:
    - A String or CharSequence task name or path
    - A TaskReference instance
    - A Task instance
    - A Buildable instance
    - A TaskDependency instance
    - A Closure instance that returns any of the above types
    - A Callable instance that returns any of the above types
    - An Iterable, Collection, Map or array instance that contains any of the above types

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.514 secs

```

**Comment by JLLeitschuh** [comment]
For the time:
```groovy
tasks.getByName("ktlint")
```
should work I think.

**Comment by erikthered** [comment]
Thanks! I couldn't figure out the right way to do that.

**Comment by JLLeitschuh** [comment]
I'm thinking of renaming the task to `ktlintCheck`. But this will necessitate releasing 2.0.0

**Comment by jeremymailen** [comment]
This also works:

```groovy
check.dependsOn tasks.ktlint
```
👍  for `ktlintCheck`. Thanks for the plugin.

**Comment by tbroyer** [comment]
If you're going to introduce a breaking change, how about using the standard Gradle naming convention for tasks related to source sets?
Using `SourceSet#getTaskName`; with `ktlint`/`ktlintCheck` and `ktlintFormat` then only linting/formatting the `main` source set, and thus renaming the `ktlint` (`ktlintCheck`) and `ktlintFormat` to something like `ktlintCheckAll` and `ktlintFormatAll`.

**Comment by JLLeitschuh** [comment]
I should really fix this.
