### ISSUE TITLE
Reorganize project to allow for integration testing and sample projects

### ISSUE THREAD

**Issue by JLLeitschuh** [JLLeitschuh/ktlint-gradle#30]
It would be good to refactor the project to support integration testing of the plugins.

I kinda like the project structure I got working in my other plugin:
https://github.com/JLLeitschuh/gradle-kotlin-aspectj-weaver

But there may be a better way to do this kind of testing.

**Comment by Tapchicoma** [comment]
Nice idea, I am also missing this while testing changes, have to apply them to my side project.

I am thinking about having simple kotlin project, kotlin project with flavors, android project, android project with flavors.

Also would be nice to run plugin with applied PR on these example projects on the CI to see that it is not breaking the build. There can be more advanced scenarios, but I am not sure how to implement them 🤔

**Comment by Tapchicoma** [comment]
Do you want to have more samples or current setup is enough?

**Comment by JLLeitschuh** [comment]
This is enough. Nice job!
