### ISSUE TITLE
Running ktlintFormat twice deletes files

### ISSUE THREAD

**Issue by donaldchen** [JLLeitschuh/ktlint-gradle#302]
**Steps to reproduce the bug**
1) Use ktlint-gradle version `9.1.0` and ktlint version `0.35.0` with the following configuration:
```
ktlint {
    version = "0.35.0"
    debug = true
    verbose = true
    android = true
    outputToConsole = true
    outputColorName = "RED"
    enableExperimentalRules = false
}
```
2) Run `./gradlew ktlintFormat --continue` once. (Then run `git status`, and observe that the auto-formatted files were modified)
3) Run `./gradlew ktlintFormat --continue` a second time

**Expected Behavior**
Running `./gradlew ktlintFormat --continue` the second time should not making any additional changes. The previously modified files should still show up as modified in `git status`, and no files should be deleted.

**Actual Behavior**
All the files that were previously marked as modified are now `deleted` (observed via `git status`).

I also tried the gradle integration recommended in https://github.com/pinterest/ktlint without plugins, and running the non-plugin `ktlintFormat` task multiple times did not delete any files. This makes me suspect that the bug is in `ktlint-gradle`.

**Comment by Tapchicoma** [comment]
Thank you for the report, I've successfully reproduced it :thinking:

**Comment by Tapchicoma** [comment]
Most probably 9.0.0 version does not have such problem, as the issue in incremental task support.

**Comment by donaldchen** [comment]
@Tapchicoma , thanks for the suggestion! I tried version 9.0.0 for `ktlint-gradle`, and I can confirm that the files no longer get deleted when I run `./gradlew ktlinFormat --continue` multiple times.

**Comment by wolfs** [comment]
Gradle currently doesn't support tasks which have the input as the output very well (if at all). Can you add the incremental support only to the lint task and not the format task?

**Comment by Tapchicoma** [comment]
That is my plan I want to do tomorrow...
