### ISSUE TITLE
Rethink format task approach

### ISSUE THREAD

**Issue by Tapchicoma** [JLLeitschuh/ktlint-gradle#306]
Currently format tasks works the same as common lint tasks, except that they may modify inputs. This leads to the several problems with this tasks caching: #302 or #194 

Possible solutions to this problem:
- actually run lint tasks first, don't fail the tasks, then run format only on files with files violations. Format task is never cacheable, but uses lint tasks reports as input.
- something else?

@JLLeitschuh maybe something else comes to your mind how to solve it as well?

**Comment by JLLeitschuh** [comment]
Diffplug spotless solved this, somehow. @nedtwigg do you have any insights here?

**Comment by nedtwigg** [comment]
You can make the format task incremental / up-to-date-able, but there are a few tricky corner cases.  The high level is [here](https://discuss.gradle.org/t/two-cases-where-the-incremental-api-is-lacking/24266), the actual implementation is [everything that touches this little class](https://github.com/diffplug/spotless/blob/d4b9b8889d3f0cfbac5354b10d678922dc6b2cbd/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessTask.java#L257-L262).

**Comment by vlsi** [comment]
There's an alternative option for Gradle 5.4+ (it uses `org.gradle.work.InputChanges`): https://github.com/autostyle/autostyle/blob/90a40e3523a5344cdc127f031bc986bb4102bdb7/plugin-gradle/src/main/kotlin/com/github/autostyle/gradle/AutostyleApplyTask.kt#L65

**Comment by JLLeitschuh** [comment]
@Tapchicoma what are your thoughts on @vlsi's suggestion here?
