### ISSUE TITLE
KtlintFormat do not respect disabled rules

### ISSUE THREAD

**Issue by tasomaniac** [JLLeitschuh/ktlint-gradle#308]
I have the following config to disable `import-ordering` rule. 

```
    ktlint {
        outputToConsole = false
        disabledRules = ['import-ordering']
   }
```

When I run `ktlintFormat` task, it still formats the files and changes the order of my imports. I'm not sure if this is a bug in the plugin or in `ktlint` tool itself.

**Comment by Tapchicoma** [comment]
@tasomaniac could you paste here content of `build/ktlint/ktlintMainSourcesSetFormat.args` file (just top one, without actual files to be formatted)?

Imho it is a bug in ktlint itself as plugin just passes `disabledRules` to ktlint, but I want to confirm this first.

And what ktlint version are you using?

**Comment by tasomaniac** [comment]
Hi, thanks for the answer. I think I was in the middle of some changes and may have wrong configuration when I see this. I cannot reproduce it anymore. 

I can verify that even after fixing some other issues, `import-ordering` was not touched.

**Comment by marcardar** [comment]
In case it's useful to anyone - After adding disabledRules (and also experiencing this was being ignored), I discovered that my ktlint block was incorrectly in the project-level gradle build. Moving it to the app-level fixed the problem.
