### ISSUE TITLE
Support official HTML reporter

### ISSUE THREAD

**Issue by rudym87** [JLLeitschuh/ktlint-gradle#312]
Since the HTML reporter is now integrated in [ktlint 0.36.0](https://github.com/pinterest/ktlint/releases/tag/0.36.0), it should be added to the configurable ones.

Right now
````gradle
ktlint {
    reporters {
        reporter "html"
    }
}
````
produces
````
> Cannot convert string value 'html' to an enum value of type 'org.jlleitschuh.gradle.ktlint.reporter.ReporterType' (valid case insensitive values: PLAIN, PLAIN_GROUP_BY_FILE, CHECKSTYLE, JSON)
````

**Comment by smuga** [comment]
Before it'll be available, you still can use HTML reporter by adding this:
```
customReporters {
    "html" {
        fileExtension = "html"
        dependency = "com.pinterest.ktlint:ktlint-reporter-html:0:36:0"
    }
}
```

**Comment by saket** [comment]
@smuga I get this error when trying to add that custom reporter:

```
* What went wrong:
A problem occurred evaluating root project 'Press'.
> Supplied String module notation 'com.pinterest.ktlint:ktlint-reporter-html:0:36:0' is invalid. Example notations: 'org.gradle:gradle-core:2.2', 'org.mockito:mockito-core:1.9.5:javadoc'.
```

**Comment by smuga** [comment]
@saket  Sorry, version number should be 0.36.0, not 0:36:0 ;) I've updated previous post.

**Comment by ImMathanR** [comment]
Any plan on when the HTML support would be released?

**Comment by Tapchicoma** [comment]
@ImMathanR We are planning to do new release this week, worth case beginning of the next week.
