### ISSUE TITLE
Could not create task of type 'KtlintCheckTask'

### ISSUE THREAD

**Issue by DannyRyman** [JLLeitschuh/ktlint-gradle#319]
I am receiving the following error with the plug-in:

> Could not create task of type 'KtlintCheckTask'.
> Could not generate a decorated class for class org.jlleitschuh.gradle.ktlint.KtlintCheckTask.
> org/gradle/work/InputChanges

ktlint: 9.1.1
gradle: 5.2.1

Can anyone help please?

**Comment by Tapchicoma** [comment]
Latest versions of plugin require minimum Gradle 5.4.1: https://github.com/JLLeitschuh/ktlint-gradle#minimal-supported-versions

You could use 8.x.x versions with Gradle 5.2.1: https://github.com/JLLeitschuh/ktlint-gradle/blob/master/CHANGELOG.md#820---2019-07-18

**Comment by Tapchicoma** [comment]
Feel free to open new issue or comment in this one if solution has not worked for you.
