### ISSUE TITLE
Exposing output file for reporters in plugin ktlint properties

### ISSUE THREAD

**Issue by Verichev** [JLLeitschuh/ktlint-gradle#321]
We would like to have the option to choose the location for reporter, which in ktlint is optional, but in plugin it's hardcoded and not available for setting.

```
        project.layout.buildDirectory.file(project.provider {
            "reports/ktlint/${this@BaseKtlintCheckTask.name}.$fileExtension"
        })
```

**Comment by JLLeitschuh** [comment]
PRs are more than welcome to add this feature.
