### ISSUE TITLE
additionalEditorconfigFile doesn't seem to work

### ISSUE THREAD

**Issue by saket** [JLLeitschuh/ktlint-gradle#322]
Possibly a duplicate of #279, but I'm unable to specify a custom path for the `editorconfig`. This doesn't seem to work:

```
ktlint {
  ...
  additionalEditorconfigFile = file("/quality/.editorconfig")
}
```

If it's of any value, I put up a commit so that you can see the full code: https://github.com/saket/press/blob/5f83d1e65ead269c761b965493d6a615851f2734/quality/lint.gradle#L15

**Comment by Tapchicoma** [comment]
According to your configuration Gradle tries to use `.editorconfig` file that should be located under `/quality/.editorconfig` path on your machine.

Proper configuration will be:
```
additionalEditorconfigFile = rootProject.file("quality/.editorconfig")
```

**Comment by Tapchicoma** [comment]
Feel free to either add a comment here or open new issue if it is still the case for you.

**Comment by CRaFT4ik** [comment]
Version 10.0.0 does not find the ".editorconfig" file in the submodule folder and "additionalEditorconfigFile" also doesn't work for me.
It's not working on version 10.0.0, and working on 9.4.1. I just changed the version number.
