### ISSUE TITLE
Speed up Git Hook by running ktlint via command line

### ISSUE THREAD

**Issue by ZakTaccardi** [JLLeitschuh/ktlint-gradle#328]
From a developer experience perspective, it would be much better if `ktlint` was executed via the executable directly, to avoid having to start up Gradle.

Is there a way `addKtlintCheckGitPreCommitHook` could be modified to use the `ktlint` executable directly?

For example: I just committed via Sourcetree (which does not inherit Gradle JVM settings from the project) a single file

- no sourcetree Gradle JVM running: `1m49s` (likely due to memory thrashing with the project's Gradle daemon
- with sourcetree Gradle JVM running: `9s`
- using ktlint directly: `1s`

**Comment by Tapchicoma** [comment]
There is a problem with such approach - it is decoupled from any changes to extension configuration and how plugin handles ktlint itself.

I am not a Sourcetree user - could you explain why there is a difference between Gradle run with or without Sourcetree? Does Sourcetree starts own Gradle instance on commit to run hook?

For me `9s` vs `1s` is still fine difference to use current approach. Also there is a room for better integration with ktlint from this plugin side (though require some changed in ktlint first).

**Comment by ZakTaccardi** [comment]
> There is a problem with such approach - it is decoupled from any changes to extension configuration and how plugin handles ktlint itself.

I do agree - but maybe that would be an option - to run it through Gradle or the executable directly

> could you explain why there is a difference between Gradle run with or without Sourcetree? Does Sourcetree start own Gradle instance on commit to run hook?

Yes, because the JVM parameters will most likely be different (unless you launch Sourcetree from the command line and not the MacOS GUI). It causes a bunch of memory thrashing

**Comment by ZakTaccardi** [comment]
Note: could also be useful to have a `./gradlew ktLintCheckChangedFiles` or something, to easily access the precommit hooks

**Comment by Tapchicoma** [comment]
I see that SourceTree has embedded git and system git options - have you tried to use system git?

**Comment by ZakTaccardi** [comment]
> I am not a Sourcetree user - could you explain why there is a difference between Gradle run with or without Sourcetree? Does Sourcetree start own Gradle instance on commit to run hook?

Basically, a project might specify it’s own JVM parameters (such as heap size). This would have to be the same for the project and any IDE (or git client). For example, if IntelliJ was pointing to a different JVM than your command line, then IDE builds and your command line builds would each use a separate Gradle daemon. This is a common performance pain point that devs often don’t realize.

There are huge performance benefits to running `ktlint` via the executable directly. Maybe there could be a task that serializes the current Gradle configuration, installs the precommit hooks using that configuration, and runs that on precommit via the executable directly. The downside is that these precommit hooks could become out of date, but I think that is an acceptable tradeoff for 10x+ the performance.

**Comment by ZakTaccardi** [comment]
Main issue is that configuring multiple git clients to use the correct JVM parameters to share the gradle daemon will be very difficult

**Comment by Tapchicoma** [comment]
Sorry, but I think you your case is better to install your custom git-hook that uses `ktlint` directly. 

`ktlint` has a command-line option to do that.

Indeed current plugin performance is far from to be perfect, but this will be addressed in the future.

**Comment by JLLeitschuh** [comment]
I think that this should be closed as a wont-fix.
It seems like the ask is outside the scope of this project. (Unless I'm misunderstanding something).
