### ISSUE TITLE
Same output file for every task

### ISSUE THREAD

**Issue by leinardi** [JLLeitschuh/ktlint-gradle#33]
Currently the output of the all the ktlint*Check task is the same XML file:
![image](https://user-images.githubusercontent.com/273338/32050151-1dcbe704-ba50-11e7-9fcd-c1f427a3d74c.png)
This means that is not possible to have multiple tasks checking different variants in the same gradle execution (this is really common in CI).

My suggestion is to align the output to the one that Lint is using and generate one file per task:
![image](https://user-images.githubusercontent.com/273338/32092949-cc7e88ec-bafa-11e7-947f-81067fdbd524.png)

This way is possible to generate multiple reports with a single gradle execution.

I have already fixed this issue locally, if you want I can open a Pull Request.

**Comment by originx** [comment]
should we do it in this PR or a new one?
@leinardi what does the change affect?

https://github.com/JLLeitschuh/ktlint-gradle/pull/32
@Tapchicoma

**Comment by leinardi** [comment]
@originx I think a new one is better. The changes are not in the method touched by #32.
But before creating one I'd like to hear from @Tapchicoma or @JLLeitschuh if they are interested in this.

**Comment by JLLeitschuh** [comment]
I don't personally use the output report.

I'd say that we should make the output configurable on the task but keep the default a sane configuration.

**Comment by Tapchicoma** [comment]
It is a good idea, though checkstyle, for example, doesn't do this. It just aggregates everything in one file. Also this is more Android specific, though Gradle start to introduce [SoftwareModel](https://docs.gradle.org/current/userguide/software_model.html) that will allow to have flavors on the plain Kotlin projects.

Also this feature should be configurable and disabled by default.

**Comment by leinardi** [comment]
If you run the same task the output will be always the same file, and this file will be overwritten every time. I don't see what is the benefit of having it disabled by default. It will be useful if you execute different tasks and nothing will change if you only have one beside the name of the file itself.

**Comment by leinardi** [comment]
OK, I fear I've been misunderstood: I don't want to enable anything new related to the report output, I just want to generate the file name for the output in a different way. To make it more clear I have opened a pull request with my changes. This should have zero impact on non Android builds beside changing the name from reports/ktlint/ktlint.xml to reports/ktlint-reports-main.xml.

@Tapchicoma, @JLLeitschuh please have a look and if you have questions just let me know.

**Comment by Tapchicoma** [comment]
Closed via #22
