### ISSUE TITLE
The pre-commit Git hook adds files after checking them

### ISSUE THREAD

**Issue by petitJAM** [JLLeitschuh/ktlint-gradle#330]
This line of the pre-commit hook causes problems for me: https://github.com/JLLeitschuh/ktlint-gradle/blob/master/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt#L46

I frequently make commits that contain just hunks of a file using `git add --patch` (usually when I have several changes locally that I want to split into separate commits).  When the pre-commit runs on files where I've done that, it blindly stages the rest of the file, changing what I was committing.  

My guess is that this is needed for the `ktlintFormat` pre-commit hook to add any changes made into the commit.  However, I believe this is not needed for the `ktlintCheck` pre-commit hook (which is what I'm using), since it does not change any files.

I've fixed this for myself by simply removing that loop from the hook.

**Comment by Tapchicoma** [comment]
Makes sense, will remove `git add` call for `ktlintCheck` pre-commit hook.

**Comment by JLLeitschuh** [comment]
Was this resolved?

**Comment by Tapchicoma** [comment]
no, most probably in the next release
