### ISSUE TITLE
Allow programmatic access to report output files

### ISSUE THREAD

**Issue by cesar1000** [JLLeitschuh/ktlint-gradle#347]
I'm writing a plugin that collects task outputs (compilation, lint, ktlint...) and presents them in a summary at the end of the build. The plugin watches for failed tasks and parses out errors from the reports. Ideally, the location of the output report would be extracted programmatically from each one of the tasks. `BaseKtlintCheckTask`, however, doesn't expose the reports or the file locations, since all properties are internal. Would you be opposed to making some of these properties publicly available in the interface?

**Comment by Tapchicoma** [comment]
Actually there is a property you could use `allReportsOutputFiles`: https://github.com/JLLeitschuh/ktlint-gradle/blob/47099c575b605ec23be0848db8bb836379962906/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt#L265

Most probably you are only interested in map values - this will be the path to generated report files.

**Comment by cesar1000** [comment]
Ohh I missed that, that's exactly what I needed, thanks :)
