### ISSUE TITLE
Run klint after junit tests

### ISSUE THREAD

**Issue by qoomon** [JLLeitschuh/ktlint-gradle#355]
Is it possible to configure klint-gradle in a way to run klint checks after junit tests?

**Comment by Tapchicoma** [comment]
`check` task runs every check.

If you want to specificly run ktlint after unit tests, you could use task oredering - https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:ordering_tasks
or finalizer task - https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:finalizer_tasks

**Comment by qoomon** [comment]
Thanks
