### ISSUE TITLE
Html reporting with <> characters are not displayed

### ISSUE THREAD

**Issue by glureau-betclic** [JLLeitschuh/ktlint-gradle#360]
The webpage:

![image](https://user-images.githubusercontent.com/35920611/83040426-8603c800-a03f-11ea-842f-1fd0f57c9079.png)

The webpage source: 

![image](https://user-images.githubusercontent.com/35920611/83040299-653b7280-a03f-11ea-84af-2049e73e4646.png)

I presume an escaping is required. 

Is it depending of ktlint-gradle or ktlint directly?

**Comment by Tapchicoma** [comment]
Could you provide steps how to reproduce?

**Comment by glureau-betclic** [comment]
Here is a simple project: https://github.com/glureau-betclic/issue_ktlint_gradle_360/tree/master

I run **./gradlew ktlintCheck** and open the HTML report:

![image](https://user-images.githubusercontent.com/35920611/83785460-9fd18a80-a691-11ea-98fd-c3c2b745dcff.png)

Problem is when using **emit(1, "Foo List<Int> bar", false)**, the '<' and '>' are not properly escaped to be displayed on web. Should probably be replaced by &lt; and &gt; (as you can see in the text in parenthesis).

**Comment by JLLeitschuh** [comment]
@Tapchicoma We didn't write the HTML generator, did we?

**Comment by Tapchicoma** [comment]
@glureau-betclic I will check your project, generally ktlint-gradle just tells ktlint what reporter to use and where to write it.

**Comment by JLLeitschuh** [comment]
This is probably a failure to escape the `<`, `>`, & `&` character. If this was being used to render untrusted data, it would technically be a security vulnerability.

**Comment by glureau-betclic** [comment]
Thaanks @Tapchicoma , I suppose I can go open an issue for ktlint now 😄

**Comment by Tapchicoma** [comment]
I opened a new issue in ktlint, please follow it. This plugin does not control what ktlint writes to report file.
