### ISSUE TITLE
max_line_length for ktlintFormat task

### ISSUE THREAD

**Issue by pawlinsky** [JLLeitschuh/ktlint-gradle#363]
Hi,

I have a editorconfig file with the following content
`
[*.{kt,kts}]
max_line_length=150
indent_size=4
`

I've set max_line_length to 150. This works for the ktlintCheck task, but when I start the ktlintFormat tasks it line-breaks my code after 100 chars. Is it possible to set a custom rule for that as well?

**Comment by Tapchicoma** [comment]
Hi, `max_line_length` should be taken into consideration by ktlint formatting. If not, please open a new issue in ktlint project.

Also your `.editorconfig` should look following:
```editorconfig
[*.{kt,kts}]
max_line_length=150
indent_size=4
```
