### ISSUE TITLE
Ensure configuration cache is supported

### ISSUE THREAD

**Issue by ZakTaccardi** [JLLeitschuh/ktlint-gradle#364]
Gradle has a new feature called the [Configuration Cache](https://docs.gradle.org/nightly/userguide/configuration_cache.html). It was previously known as Instant Execution, and this greatly improves build speed.

Usage of the Configuration Cache has a stricter list of [requirements](https://docs.gradle.org/nightly/userguide/configuration_cache.html#requirements).

While the this plugin may already be compatible with the Configuration Cache, please investigate this to ensure support.

See https://github.com/gradle/gradle/issues/13490 for a list of all community plugins and whether they support the configuration cache.

**Comment by JLLeitschuh** [comment]
@ZakTaccardi Do you have the cycles to perform this exploration? A test that verifies compatibility with the configuration cache would be appreciated.

**Comment by ZakTaccardi** [comment]
Check out this issue

https://github.com/michel-kraemer/gradle-download-task/issues/156

@eskatos I'm not sure how to generate the problems report - may be useful to include that in the example issue

It looks like if you [enable the configuration cache](https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:usage:enable), the build will automatically fail if issues are encountered.

There's also flags for ignoring configuration cache issues or issui g warnings

https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:usage:ignore_problems

@eskatos is there currently a way to test or set a plugin specific flag to ensure (fail the build) if **only** the plugin you are authoring violates the configuration cache rules? I would imagine many plugins may rely on other plugins that do not support the configuration cache yet (like the [Kotlin Gradle plugin](https://youtrack.jetbrains.com/issue/KT-33908)), but would want to fail the build if the plugin that is being authored breaks configuration cache rules

**Comment by eskatos** [comment]
@JLLeitschuh testing for the configuration cache is documented at https://docs.gradle.org/nightly/userguide/configuration_cache.html#config_cache:testing

@ZakTaccardi the report is generated as soon as at least one problem is detected. There's currently no way to filter problems by provenance.

**Comment by JLLeitschuh** [comment]
@ZakTaccardi let us know if you have additional issues with this. The Kotlin plugin is the biggest limiter here for supporting the configuration cache for this plugin.
