### ISSUE TITLE
How to auto format code with ktlint?

### ISSUE THREAD

**Issue by PavPip** [JLLeitschuh/ktlint-gradle#376]
In my Android App project, I added 
```
plugins {
    id "org.jlleitschuh.gradle.ktlint" version "9.3.0"
}
```
to root level and 
`apply plugin: 'org.jlleitschuh.gradle.ktlint'`
to module level build.gradle

Furtheron I have a lot of declarations with/without spaces before the colon:

```
var var1: Int = 0 // 1. style
var var2 : Int = 0 // 2. style
```

When I rebuild my project, I was expecting that these kind of code styles are standardized by one preferred style choosen by ktlint by default? Obviously the code were not auto formatted in my case. 

What do I have to do, to auto format my code?

**Comment by CarlosEsco** [comment]
you can add something like this

```
tasks.preBuild {
    dependsOn(tasks.ktlintFormat)
}
```

**Comment by JLLeitschuh** [comment]
@PavPip you need to execute the Gradle task to get the formatting to happen `ktlintFormat`.
