### ISSUE TITLE
Cannot disable multiline-if-else rule

### ISSUE THREAD

**Issue by LordMZTE** [JLLeitschuh/ktlint-gradle#378]
i tried to disable said rule through the configuration of my build file however adding it to the disabledRules had no effect.
```kt
ktlint {
    enableExperimentalRules.set(true)
    disabledRules.set(
        setOf(
            "multiline-if-else",
            "comment-spacing",
            "curly-spacing",
            "keyword-spacing",
            "no-wildcard-imports"
        )
    )
}
```
im still gettting `Missing { ... }` messages in the console and after checking the source code of ktlint, those are coming from multiline-if-else

im using version 9.3.0 of this plugin

the report can be found [here](https://pastebin.com/iZNEtxEg)

**Comment by JLLeitschuh** [comment]
This sounds like it's more likely a bug in `ktlint` not this plugin. Either that, or you're passing the wrong rule name.

**Comment by LordMZTE** [comment]
according to ktlint's github source code, the rule is registered with that exact name. i copied it from there

**Comment by JLLeitschuh** [comment]
Can you provide an example/reproduction of the issue?

**Comment by LordMZTE** [comment]
the build script i took this from is [here](https://github.com/Anvilcraft/modpacktools/blob/master/build.gradle.kts)

**Comment by LordMZTE** [comment]
it looks like the issue was that i had to specify `experimental:multiline-if-else` insead of `multiline-if-else` with this changed, everything works as expected
