### ISSUE TITLE
KtlintCheckTask not cacheable due to overlapping outputs

### ISSUE THREAD

**Issue by 3flex** [JLLeitschuh/ktlint-gradle#379]
From my build scan:
> Overlapping outputs: Gradle does not know how file 'build\reports\ktlint\ktlintAndroidTestSourceSetCheck.txt' was created (output property 'reporterOutputDir'). Task output caching requires exclusive access to output paths to guarantee correctness.

I have several `KtlintCheckTask` tasks in my build, and all are noncacheable for this reason. The tasks run every time even when Gradle runs with `--build-cache`.

ktlint-gradle version 9.3.0

**Comment by 3flex** [comment]
Just to update, I've downgraded to 9.2.1, and task output caching works on that version. I suspect the issue was introduced in https://github.com/JLLeitschuh/ktlint-gradle/pull/346

**Comment by Tapchicoma** [comment]
Yes, can confirm. Will try to fix it.

**Comment by Tapchicoma** [comment]
Problem that output dir could be created by another source set check task that run before. Will fix it for the next release.
