### ISSUE TITLE
Option to fail for any violations, but run all the checks

### ISSUE THREAD

**Issue by dalewking** [JLLeitschuh/ktlint-gradle#391]
As I understand it we have the ignoreFailures to fail the build if there are any violations, My problem with it is that once there is a violation in one source set (I am applying to a multiplatform build) it does not then run on remaining source sets. I want the task to fail if there are violations but i want the check to be run on all source sets.

**Comment by Tapchicoma** [comment]
`ignoreFailure` option when enabled don't set task to failed state even if ktlint found issues.

You should use `--continue` Gradle option to continue build even if some task failed, check first question in https://github.com/JLLeitschuh/ktlint-gradle#faq.
