### ISSUE TITLE
filter not working (Kotlin MPP)

### ISSUE THREAD

**Issue by dalewking** [JLLeitschuh/ktlint-gradle#392]
I have added the plugin to my Kotlin MPP project using this configuration:
```
ktlint {
    debug = true
    verbose = true
    android = false
    outputToConsole = true
    outputColorName = "RED"
    ignoreFailures = false
    enableExperimentalRules = true
    disabledRules = ["multiline-if-else"]
    reporters {
        reporter "plain"
        reporter "checkstyle"
    }
    filter {
        exclude("**/generated/**")
    }
}
```

Yet I am getting failures from files under build/generated like this:
```
Checking <path_to_project>/build/generated/moko/androidMain/src/<classpath>/MR.kt
Resolving .editorconfig files for <path_to_project>/build/generated/moko/androidMain/src/<classpath>/MR.kt file path
<path_to_project>/build/generated/moko/androidMain/src/<classpath>/MR.kt:3:1: Unnecessary import (no-unused-imports)
```

**Comment by Tapchicoma** [comment]
Please check 3rd question in faq: https://github.com/JLLeitschuh/ktlint-gradle#faq

If it will not help - is it possible to share project that has this issue?

**Comment by dalewking** [comment]
I'll try that, but may be a day or two before I can get to it.

**Comment by xetra11** [comment]
Doesn't work for me either.

```

ktlint {
    filter {
        exclude("**/generated/**")
    }
}
```
It still is mad about my files in the build generated directory

```
/build/generated/source/graphql/main/com/company/gate/network/graphql/PalletProductSearch.kt:107:1: Unexpected indentation (4) (should be 8)
/build/generated/source/graphql/main/com/company/gate/network/graphql/PalletProductSearch.kt:108:1: Unexpected indentation (2) (should be 4)
```

**Comment by Tapchicoma** [comment]
@xetra11 could you provide link to your repo or create small project to reproduce the issue?

**Comment by xetra11** [comment]
@Tapchicoma 
Sorry after a while I found the FAQ entry for filtering source outside src/main. It's working with the mentioned workaround now

**Comment by dalewking** [comment]
Yeah, I'm going to go ahead and close this. The answer in the FAQ did solve the issue. In the end I decided against using the plugin and just stayed with our handwritten ktlint tasks due to the whole need to use --continue to run it on all source sets making it harder to use and thus did not see any real value to switching to the plugin.

**Comment by PaulWoitaschek** [comment]
If someone is looking for this, a possible solution to filter on mpp projects could look like this:
```kotlin
  configure<KtlintExtension> {
    version.set(Dependencies.ktLintVersion)
    filter {
      exclude { tree ->
        val path = tree.file.path
        listOf(".gradle/", "cache/", "build/generated/").any {
          path.contains(it)
        }
      }
    }
  }
```
