### ISSUE TITLE
ktlintCheck task does not fail on Windows 

### ISSUE THREAD

**Issue by santelos** [JLLeitschuh/ktlint-gradle#399]
Hello Ktlint-Gradle team.

I'm facing the strange issue.
When I'm running the local ktlint check via `./gradlew clean ktlintCheck` the _"mainSourceSetCheck"_ task completes successfully.
But when I'm running the same process in `docker build` environment the result is different and it fails.

I've found the same problem on StackOverflow: 
[https://stackoverflow.com/questions/63863368/ktlint-check-doesnt-work-locally-anymore-it-works-tho-in-my-docker-image-buil](https://stackoverflow.com/questions/63863368/ktlint-check-doesnt-work-locally-anymore-it-works-tho-in-my-docker-image-buil)

Versions I'm using:
 - Gradle wrapper 6.6.1-bin.zip
 - OpenJDK 14.0.2
 - Kotlin version 1.4.10
 - Ktlint-gradle plugin 9.4.0

The `java --version` output in the local and docker environment is the same:
```
openjdk 14.0.2 2020-07-14 
OpenJDK Runtime Environment (build 14.0.2+12-46) 
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
```

Local environment check outputs the following message `[DEBUG] <...>ms / 0 file(s) / 0 error(s)`
whereas the docker environment outputs the `[DEBUG] <...>ms / 1 file(s) / 1 error(s)`

I've also made a minimum reproducible example. You may found it here: 
[https://github.com/santelos/ktlint-mre](https://github.com/santelos/ktlint-mre)

---

build.gradle.kts
```
repositories {
    mavenCentral()
}

plugins {
    kotlin("jvm") version "1.4.10"
    id("org.jlleitschuh.gradle.ktlint") version "9.4.0"
}

ktlint {
    debug.set(true)
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "14"
}
```

Dockerfile
```
FROM openjdk:14.0.2
WORKDIR /build
COPY . .
RUN java --version
RUN ./gradlew clean ktlintCheck
```

**Comment by Tapchicoma** [comment]
Hi, thank you for the project to reproduce your issue.

I've tried to do it on my machine with openjdk 14, but for me it always fails both locally and in docker image. Maybe there are some additional steps to reproduce?

**Comment by santelos** [comment]
Thank you for the response.

Just figured out that this is reproducible only on the Windows OS.
I've tested my scenario on WSL2 based Ubuntu 20.04 and yes, the local build failed as expected.

May be you can try it on Windows OS?

**Comment by craigatk** [comment]
In case it helps, I am experiencing similar behavior where the source set check tasks are passing on my Windows laptop with plugin `9.4.0` but failing in GitHub actions with Linux. The formatting tasks also have no effect when running on Windows locally - probably the same underlying cause.

Downgrading to the previous version of the plugin I was using (`9.1.1`) fixes the issue - the format tasks catch and correct the formatting issues on Windows locally.

This is the project I'm using: https://github.com/craigatk/projektor

Other versions:

* Kotlin 1.4.10
* Java 11
* Gradle 6.6.1
* ktlint 0.39.0

I imagine not everyone has a Windows machine lying around to try to diagnose this :) I'll try out the plugin code locally on my Windows machine and see if I can find out what's happening.

**Comment by xetra11** [comment]
> In case it helps, I am experiencing similar behavior where the source set check tasks are passing on my Windows laptop with plugin `9.4.0` but failing in GitHub actions with Linux. The formatting tasks also have no effect when running on Windows locally - probably the same underlying cause.
> 
> Downgrading to the previous version of the plugin I was using (`9.1.1`) fixes the issue - the format tasks catch and correct the formatting issues on Windows locally.
> 
> This is the project I'm using: https://github.com/craigatk/projektor
> 
> Other versions:
> 
> * Kotlin 1.4.10
> * Java 11
> * Gradle 6.6.1
> * ktlint 0.39.0
> 
> I imagine not everyone has a Windows machine lying around to try to diagnose this :) I'll try out the plugin code locally on my Windows machine and see if I can find out what's happening.

Hey there!
I have a similar issue. Here are my setups and their results:

**Setup 1** 
* Windows 10
* Java `11`
* Gradle `6.6.1`
* gradle ktlint plugin `9.3.0`
* Kotlin `1.3.72`
> *Works*: `ktlintCheck` finds the issues

**Setup 2** 
* Windows 10
* Java `11`
* Gradle `6.6.1`
* gradle ktlint plugin `9.4.0`
* Kotlin `1.4.10`
>*Fails*: The `ktlintCheck` commands just runs through without any errors even tho the previous setup yielded issues. `ktlintFormat` has no effect either.
```
> Task :ktlintTestSourceSetCheck UP-TO-DATE
> Task :ktlintMainSourceSetCheck
> Task :ktlintKotlinScriptCheck
> Task :ktlintCheck
```
**Setup 3** @craigatk your example with plugin `9.1.1` 
* Windows 10
* Java `11`
* Gradle `6.6.1`
* gradle ktlint plugin `9.1.1`
* Kotlin `1.4.10`
>*Fails*: Exception in thread "main" java.lang.NoSuchFieldError: FUN_KEYWORD

For me it turns out I can not use Kotlin `1.4.10` with the current build :(

**Comment by Tapchicoma** [comment]
I could reproduce it on the windows machine using sample project. Looking into it :eyes:

**Comment by santelos** [comment]
Thank's, @Tapchicoma 
The Windows community is happy now :grin:
