### ISSUE TITLE
Depend on kotlin 1.1.1

### ISSUE THREAD

**Issue by rrva** [JLLeitschuh/ktlint-gradle#4]
This project depends on kotlin-stdlib 1.1.0-rc-91.

Now that kotlin 1.1.1 is released, isn't it better to depend on a stable version?

**Comment by JLLeitschuh** [comment]
Yes! Absolutely!
PR's are welcome.
If you don't have the time I will try to get around to this myself.

**Comment by JLLeitschuh** [comment]
This has been resolved. Thanks for the feedback!
