### ISSUE TITLE
ktlint and idea, intellij import order

### ISSUE THREAD

**Issue by daniel-tailored** [JLLeitschuh/ktlint-gradle#402]
Hi,

since ktlint 0.37.0 the default import order is set to match the idea style afaik.
how and is it also possible to configure the plugin to match the idea style **and** enable android mode (since it seems to change after enabling android)?

thx in advance

**Comment by Tapchicoma** [comment]
You should configure it via `.editorconfig` file, please check this section: https://github.com/pinterest/ktlint/#custom-ktlint-specific-editorconfig-properties

**Comment by daniel-tailored** [comment]
oh thank you very much. sry I overlooked that.
