### ISSUE TITLE
Any way to run both ktlintFormat and ktlintCheck before creating a commit?

### ISSUE THREAD

**Issue by tatsuyafujisaki** [JLLeitschuh/ktlint-gradle#404]
Is there any way to run both `ktlintFormat` and `ktlintCheck` before creating a commit?

I know that both `gradle addKtlintFormatGitPreCommitHook` and `gradle addKtlintCheckGitPreCommitHook` override `.git/hooks/pre-commit` for `ktlintFormat` and `ktlintCheck` respectively, but I'd like do both of them.

**Comment by Tapchicoma** [comment]
Install githook via one of the tasks, open `.git/hooks/pre-commit` in some editor and add missing either check or format command.

Place where it is generated in code:
https://github.com/JLLeitschuh/ktlint-gradle/blob/9c1a140051b42939e4fb53a5e0a31c171fa3f289/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt#L34

Example how it will look for format (replace `ktlintFormat` with `ktlintCheck` for just check the sources):
```
./gradlew --quiet ktlintFormat -PinternalKtlintGitFilter="$CHANGED_FILES"
```
