### ISSUE TITLE
Request for one pre-commit hook that run both check & format

### ISSUE THREAD

**Issue by anticafe** [JLLeitschuh/ktlint-gradle#406]
For now we have pre-commit hooks `addKtlintCheckGitPreCommitHook` and `addKtlintFormatGitPreCommitHook` which run CHECK and FORMAT task. I wonder if you can provide a single hook like `addKtlintCheckThenFormatGitPreCommitHook` that will run the check first, if failed, then run the format after.

**Comment by Tapchicoma** [comment]
What is your use-case?

This will double the time of the hook run. Also usually running format should be enough, format also validates style before doing format.

**Comment by anticafe** [comment]
@Tapchicoma Ah, understand. Before I though `addKtlintFormatGitPreCommitHook` doesn't validate style, but as you said it does in order to optimize the process. Sound good 💯
