### ISSUE TITLE
Groovy not applying version within ktlint block

### ISSUE THREAD

**Issue by sklinefelter** [JLLeitschuh/ktlint-gradle#412]
I am trying to lock my version of ktlint at 0.36.0 to avoid this issue: https://github.com/pinterest/ktlint/issues/764 until there is a more permanent solution.

```groovy
plugins {
    id "org.jlleitschuh.gradle.ktlint" version "9.4.1"
}
```

```groovy
import org.jlleitschuh.gradle.ktlint.reporter.ReporterType

ktlint {
    version = "0.36.0"
    debug = true
    verbose = true
    android = true
    reporters {
        reporter(ReporterType.PLAIN)
        reporter(ReporterType.CHECKSTYLE)
    }
    ignoreFailures = false
}
```

I have tried several different syntax combinations but I have been unsuccessful in having 0.36.0 applied.  Can someone guide me on what I am doing wrong?

**Comment by JLLeitschuh** [comment]
Try `version.set("0.36.0")`

That should work. If it doesn't what's the issue you're seeing? An exception? Something else?

**Comment by sklinefelter** [comment]
It's not an exception, but it's failing on a new lint check that was added in ktlint 0.37.x.

Klint error:

`Missing newline after "("`
`Missing newline before ")"`

Example code causing it:

```
foo1.bar(Foo2(
    param1 = ...,
    param2 =  ...
))
```

Rolling the ktlint-gradle plugin back to 9.2.1 works (this version has 0.36.0).  That's why I believe the version in the configuration is not being adhered to.

**Comment by JLLeitschuh** [comment]
@sklinefelter can you use the dependency insight task and send us the output for the `ktlint` configuration? I'm guessing that you have some external version constraint that's being applied here. Alternatively, can you provide a sample application?

**Comment by sklinefelter** [comment]
@JLLeitschuh I revisited this and noticed the ktlint configuration was outside of the subprojects block.  Once moved to the subproject configuration in the project's gradle it behaved as I expected.  I don't believe this to be an actual issue after all so we can close this.  Maybe I did not read the documentation well enough :)

**Comment by JLLeitschuh** [comment]
Cool glad this was resolved.
