### ISSUE TITLE
Unexpected indentation - parameter-list-wrapping expects wrong indentation  

### ISSUE THREAD

**Issue by KylerWitting** [JLLeitschuh/ktlint-gradle#415]
I am trying to enable experimental features but running into an issue around parameter formatting. I have the code, error, build.gradle, and the attempted solution below. If I turn off experimental rules there are no more errors thrown but I was not able to disable the rule I believe is causing the issue.   

[This](https://github.com/pinterest/ktlint/issues/864) seems to be the issue getting resolved in `0.39.0` but when I manually specify the version the error persists. 

## Code:
```kotlin
fun T.exampleFun(first: String, other: String): String {
    return if (first.equals(
            other = other,
            ignoreCase = true
        ) ||
        <SECOND_CONDITIONAL>
    ) {
        first
    } else {
        null
    }
}
```

## Error: 
```bash
> Task :ktlintMainSourceSetFormat FAILED
/path/to/Example.kt:98:13: Unexpected indentation (expected 8, actual 12)
/path/to/Example.kt:99:13: Unexpected indentation (expected 8, actual 12)
/path/to/Example.kt:100:9: Unexpected indentation (expected 4, actual 8)
```

## `build.gradle`
```groovy
plugins {
    id 'org.jlleitschuh.gradle.ktlint' version '9.4.1'
}

ktlint {
    enableExperimentalRules = true
    filter {
        exclude { element -> element.file.path.contains("generated/") }
    }
}
```

## Attempted Solutions 
`disabledRules = ["experimental:argument-list-wrapping"]`
`version = "0.39.0"`

## Working Solution 
`enableExperimentalRules = false`

**Comment by Tapchicoma** [comment]
Fix hasn't been yet released and should be in `0.40.0` ktlint version that is planned to be released today.
