### ISSUE TITLE
Customize classpath

### ISSUE THREAD

**Issue by marcbowes** [JLLeitschuh/ktlint-gradle#416]
I'm upgrading from an older version of the plugin where I used to be able to set the classpath (that was used by JavaExec):

```
def ktLintConfig = project.configurations.maybeCreate("ktlint")
ktLintConfig.dependencies.add(project.dependencies.create(project.files(klasspath.getFiles())))
```

That doesn't seem to work anymore. https://github.com/JLLeitschuh/ktlint-gradle/blob/0a47536b2640952d32a69a38873e12a6db73f02c/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintBasePlugin.kt#L29 flips the runner based on the Gradle version. The new runner is this guy: https://github.com/JLLeitschuh/ktlint-gradle/blob/0a47536b2640952d32a69a38873e12a6db73f02c/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/WorkerApiKtLintRunner.kt#L14, which is called from https://github.com/JLLeitschuh/ktlint-gradle/blob/0a47536b2640952d32a69a38873e12a6db73f02c/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt#L170.

That leads me to believe I should be able to do something like:

```
project.tasks.withType(BaseKtlintCheckTask) { BaseKtlintCheckTask check ->
    check.classpath.setFrom(project.files(klasspath.getFiles()))
}
```
but it doesn't work:

```
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'classpath' for task ':ktlintKotlinScriptCheck' of type org.jlleitschuh.gradle.ktlint.KtlintCheckTask.
```

I'm not sure if that's because `classpath` [is internal](https://github.com/JLLeitschuh/ktlint-gradle/blob/0a47536b2640952d32a69a38873e12a6db73f02c/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt#L41), or what. I don't know my way around Gradle plugins at all!

**Comment by Tapchicoma** [comment]
Why do you want to modify ktlint classpath? :thinking: 

It is intentionally set to be `internal` as it should only be used by plugin itself.

**Comment by marcbowes** [comment]
Corporate build system - we can't pull from Maven directly. So, we have to unhitch the [dependency added here](https://github.com/JLLeitschuh/ktlint-gradle/blob/0a47536b2640952d32a69a38873e12a6db73f02c/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/Configurations.kt#L24) and then add back our own dependency.

I haven't figured this out yet, but I do now suspect that something between 0.31 and the version I'm upgrading to (0.37) has either changed initialization order or cached something or..

**Comment by marcbowes** [comment]
Definitely part of the issue is ordering, e.g. I added this:

```
if (project.configurations.findByName("ktlint") != null) {
    throw RuntimeException("cannot configure ktlint because the configuration already exists; \n" +
            "this configuration is cached inside the ktlint plugin and can no longer be changed.")
}
```

and it failed. Then, I moved my hacky code around until it didn't fail. So, at this point I'm pretty sure that I will be injecting a configuration named `ktlint` early enough that your code's call to `maybeCreate` will not make a new one. However, the tasks that are created still don't have the right classpath. The classpath is copied [using ktlintConfiguration as a FileCollection](https://github.com/JLLeitschuh/ktlint-gradle/blob/0a47536b2640952d32a69a38873e12a6db73f02c/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/KtlintPlugin.kt#L214). If I do something like

```
println project.configurations.getByName("ktlint").getFiles().size()
```

then I do see the jars I added. So, that's where I'm stuck. Probably time for a debugger.

**Comment by Tapchicoma** [comment]
@marcbowes have you tried to define exclusively where Gradle should find ktlint dependencies via https://docs.gradle.org/current/userguide/declaring_repositories.html#declaring_content_exclusively_found_in_one_repository?

Something like this should work:
```kotlin
repositories {
    exclusiveContent {
        forRepository {
            maven {
                url = uri("https://repo.mycompany.com/maven2")
            }
        }
        filter {
            includeGroup("com.pinterest.ktlint")
        }
    }
}
```

This plugin does not add any repository by itself to locate ktlint artifacts.
