### ISSUE TITLE
Cannot run ktlint on buildSrc folder

### ISSUE THREAD

**Issue by LandonPatmore** [JLLeitschuh/ktlint-gradle#422]
I am trying to run the linter on the `buildSrc` folder since it contains Kotlin files for dependencies, versions, etc.

The project structure is like such:

```
<root>
buildSrc/
-> src/
    -> main/
        -> kotlin/
            - Dependencies.kt
            - Versions.kt
```

In my root `build.gradle.kts` file, I have tried:

```
ktlint {
    version.set("0.40.0")
    reporters {
        reporter(ReporterType.JSON)
    }
    kotlinScriptAdditionalPaths {
        include(fileTree("buildSrc/"))
    }
    filter {
        exclude("**/generated/**")
        include("**/kotlin/**")
    }
}
```

and 

```
ktlint {
    version.set("0.40.0")
    reporters {
        reporter(ReporterType.JSON)
    }
    kotlinScriptAdditionalPaths {
        include(fileTree("buildSrc/"))
    }
    filter {
        exclude("**/generated/**")
        include("../buildSrc/**/kotlin/**")
    }
}
```

and

```
ktlint {
    version.set("0.40.0")
    reporters {
        reporter(ReporterType.JSON)
    }
    kotlinScriptAdditionalPaths {
        include(fileTree("buildSrc/"))
    }
    filter {
        exclude("**/generated/**")
        include("buildSrc/**/kotlin/**")
    }
}
```

These work for the `build.gradle.kts` file inside the `buildSrc` folder, but they do not pick up the kotlin files in the `kotlin` folder. Am I missing something?

**Comment by Tapchicoma** [comment]
Probably your `include` should be following:
```kotlin
include("buildSrc/**/kotlin/**/*.kt")
```

**Comment by LandonPatmore** [comment]
@Tapchicoma That still didn't work, got the same output that nothing was wrong even though I deliberately "broke" the files.

**Comment by JLLeitschuh** [comment]
Simply apply the plugin to your `buildSrc/build.gradle`

**Comment by LandonPatmore** [comment]
@JLLeitschuh Hmm that does make sense, didn't think of that, thanks! However, is there a reason the `include()` filter isn't picking up that folder with the specified folder path?
