### ISSUE TITLE
ktlintFormat creates directories under src

### ISSUE THREAD

**Issue by red-avtovo** [JLLeitschuh/ktlint-gradle#423]
When I run `ktlintFormat` there are the following directories, which are created under `src` directory:
- src/main/java
- src/main/kotlin
- src/test/java
- src/test/kotlin

It is pretty annoying seeing java directory all the time and have no chance to get rid of it when you write a 100% Kotlin project. Is there a way to ask ktlint not to create these directories?

**Comment by Tapchicoma** [comment]
Are you sure that it is `ktlint-gradle` who creates this directories?

Generally this plugin only modifies files without creating any `SourceSet` and related directories, plus I haven't seen such behaviour in my other projects that apply this plugin.

Maybe you could create some project to reproduce it or share your project?

**Comment by red-avtovo** [comment]
Here you go: https://github.com/red-avtovo/ktlintTest
If you will pull the repo and run `./gradlew ktlintFormat` it will create a java directory under src

**Comment by red-avtovo** [comment]
Some additional info: when you run `ktlintFormat` these tasks are being executed as dependencies
```
./gradlew ktlintFormat --dry-run
:ktlintKotlinScriptFormat SKIPPED
:ktlintMainSourceSetFormat SKIPPED
:ktlintTestSourceSetFormat SKIPPED
:ktlintFormat SKIPPED
```

**Comment by JLLeitschuh** [comment]
This may be because we are declaring the source sets to be both inputs and outputs. As such, Gradle has a `CreateOutputsStep` processor that runs on tasks to automatically generate the output directories for the task.


Semi-related:
https://github.com/gradle/gradle/issues/15679

**Comment by Tapchicoma** [comment]
Could reproduce this issue with sample project :+1:

Relates to #306

**Comment by ed0906** [comment]
We also have this issue
Temporary workaround is to just delete the extra folders immediately after

```
tasks {
    ktLintFormat {
        doLast {
            delete("src/whatever")
        }
    }
}
```
