### ISSUE TITLE
GIT Pre Commit Gradle Tasks Not Created

### ISSUE THREAD

**Issue by StuStirling** [JLLeitschuh/ktlint-gradle#430]
When using version of `9.4.1` of the plugin and applying it using this following, I don't get the pre commit GIT tasks created.

`apply plugin: "org.jlleitschuh.gradle.ktlint-idea"`

I do, however, have the "Idea" tasks available:

* ktlintApplyToIdea
* ktlintApplyToIdeaGlobally

**Comment by Tapchicoma** [comment]
Do you have `.git/` folder inside root project?

**Comment by StuStirling** [comment]
Yes I have have a `.git` folder. This is my project root

![Screenshot 2021-02-01 at 15 48 55](https://user-images.githubusercontent.com/4354927/106482096-05864880-64a5-11eb-8f45-50bd136b3e0b.png)

I do already have a file `hooks/pre-commit` but any content is commented out. Could this be contributing?

**Comment by Tapchicoma** [comment]
> Could this be contributing?

No it should not affect it.

> apply plugin: "org.jlleitschuh.gradle.ktlint-idea"

Sorry missed it in your first comment. You need to apply "org.jlleitschuh.gradle.ktlint" into root project to see git hook tasks.

**Comment by StuStirling** [comment]
Thanks this has done it. I think the documentation misled me.

> Use the same buildscript logic as above, but with this instead of the above suggested apply line.

**Comment by Tapchicoma** [comment]
Closed via #431
