### ISSUE TITLE
runKtlintCheckOverKotlinScripts & runKtlintFormatOverKotlinScripts process too many files

### ISSUE THREAD

**Issue by JLLeitschuh** [JLLeitschuh/ktlint-gradle#434]
Currently,  when you utilize the `runKtlintCheckOverKotlinScripts` and `runKtlintFormatOverKotlinScripts` tasks, they, by default configure a file tree with the wildcard `**/*.kts`.

Given the following file structure, where `ktlint-gradle` is configured on the root project and all sub-projects.

```
parent-build.gradle.kts
subproject
  - child-build.gradle.kts
```

In this situation, `child-build.gradle.kts` is linted/formatted twice. Once by the root project, and once by the child project.

This has further implications.

In Gradle 7, some checks were introduced to check if two tasks have overlapping inputs/outputs that are undeclared.

If we specify that the `ktlint-gradle` input is `**/*.kts`, we suddenly have a `FileTree` that is rooted in the root, and all subdirectories, including the `build` directory, become inputs to our task. Thus our plugin will have input overlap with all tasks.

---

I believe that the fix here is to change the input wildcard to simply be `*.kts`. This forces users to manually specify sub-directories that contain script files, for example if scripts are in the `gradle` directory. But I think this change brings us closer to being correct.

CC: @Tapchicoma 

Credit to @wolfs for helping explain this to me.

**Comment by Tapchicoma** [comment]
@wolfs could you provide more information how to reproduce this issue?

I could not reproduce it via test in #435 (even with `7.0-milestone-1` Gradle version).

**Comment by wolfs** [comment]
It seems like I misread `**/*.kts`, while the include is actually only `*.kts`. So everything seems to be good!
