### ISSUE TITLE
Publish the plugin also to jcenter and mavenCentral

### ISSUE THREAD

**Issue by leinardi** [JLLeitschuh/ktlint-gradle#44]
Please consider publishing the plugin also to jcenter and mavenCentral. This will allow Android developers to use it without adding any additional repository to their project.

You can find an example of gradle configuration for publishing to Gradle Plugin, jcenter and mavenCentral here the same artifact here: https://github.com/leinardi/android-findbugs-plugin/blob/master/build.gradle

**Comment by JLLeitschuh** [comment]
You shouldn't need to add any additional repositories to your gradle project if you use the `plugin` syntax.
```kotlin
plugins {
  id "org.jlleitschuh.gradle.ktlint" version "2.3.0"
}
```

**Comment by leinardi** [comment]
If I'm not wrong that only works for the main build.gradle, but cannot be used in multi module projects. In Android

**Comment by JLLeitschuh** [comment]
In multi project builds you can do this:
```groovy
plugins {
  id "org.jlleitschuh.gradle.ktlint" version "2.3.0"
}

subprojects {
    apply plugin: "org.jlleitschuh.gradle.ktlint" // Version should be inherited from parent
}
```

**Comment by leinardi** [comment]
Thanks, it seems to work.

**Comment by Tapchicoma** [comment]
I think we should update README with how-to apply to subprojects using new plugins api.
