### ISSUE TITLE
What is debug.set(true) does?

### ISSUE THREAD

**Issue by tomkoptel** [JLLeitschuh/ktlint-gradle#448]
Hello,

Sorry for opening an issue when it is a more docs-related question, but I can not figure out what is the `debug.set(true)` means. I am ok to update documentation for the project by contributing to the PR. Though, I don't follow the debug flag?

Thank you for the awesome job!

**Comment by Tapchicoma** [comment]
in `9.*` releases it enabled KtLint CLI `--debug` option. In latest release it does not so much - prints some debug messages and passes `debug` flag to `KtLint`.

**Comment by tomkoptel** [comment]
@Tapchicoma thank you for the answer. Do you know any use case that will take advantage of `debug` flag? (for example, if debug=true then you will be able to verify X, Y, Z happening?)

So far it looks more like an option for the maintainers of the ktlint than something me as a dummy consumer would be interested in 🤷‍♂️ .

**Comment by Tapchicoma** [comment]
yes, usually it is used to debug issues with KtLint.
