### ISSUE TITLE
additionalEditorconfigFile doesn't seem to work

### ISSUE THREAD

**Issue by nuhkoca** [JLLeitschuh/ktlint-gradle#450]
Possible duplicate of #322 but I couldn't find a solution yet.

**Versions:**

- Pluging: 10.0.0
- ktlint: 0.40.0

### Current Behavior
Ktlint doesn't seem to stick by `.editorconfig` properties. I am getting `max line length` error for test classes.

### Expected Behavior
Ktlint should stick by `.editorconfig` properties. I shouldn't get `max line length` error for test classes.

I have below setup of `ktlint`.

```groovy
ktlint {
    android = true
    ignoreFailures = false
    additionalEditorconfigFile = rootProject.file(".editorconfig")
    version = "0.40.0"
    disabledRules = [
        'import-ordering',
        'chain-wrapping',
        'no-blank-line-before-rbrace'
    ]
}
```

`.editorconfig` file(located under rootProject)

```yml
[*]
insert_final_newline = true

[*.{kt,kts}]
max_line_length=120

[**/test/**.kt]
max_line_length=1000
```

However still getting;

`/path/to/test/class.kt:321:1` Exceeded max line length (120) (cannot be auto-corrected)`

Am I missing something here?

**Comment by Tapchicoma** [comment]
> .editorconfig file(located under rootProject)

Note that you don't need to use `additionalEditorconfigFile` for `.editorconfig` files located inside source file parents directories.

Regarding your problem - could you try to reproduce it with KtLint `0.39.0` version?

**Comment by Tapchicoma** [comment]
`/path/to/test/class.kt/` - is it typo or file has `/` in the end?

**Comment by nuhkoca** [comment]
@Tapchicoma indeed, it is working well with ktlint `0.39.0.` 😮  For instance;

For any `.kt` files except ones under test, I am getting the below debug info

**Loaded .editorconfig: [charset: utf-8, insert_final_newline: true, indent_style: space, end_of_line: lf, trim_trailing_whitespace: true, disabled_rules: import-ordering,chain-wrapping, max_line_length: 120]**

But for any `.kt` files under `test` directory, which is correct.

**Loaded .editorconfig: [charset: utf-8, insert_final_newline: true, indent_style: space, end_of_line: lf, trim_trailing_whitespace: true, disabled_rules: import-ordering,chain-wrapping, max_line_length: 1000]**

As it seems, it is an issue in ktlint itself, right? In fact, I went through all changelog and README but couldn't see any improvements impacting on this key. Do you predict anything about it?

BTW, I fixed the `/` typo, thanks for informing!

**Comment by Tapchicoma** [comment]
I would suggest to wait for next `0.41.0` KtLint release that should be released next week and has some fixes from `.editorconfig` handling. It may fix your issue as well.

But yeah, the issue in KtLint itself.

**Comment by nuhkoca** [comment]
Thanks a lot @Tapchicoma! I'll wait for it then. Hope to have it fixing this issue. Otherwise, I'll ping them and update this issue.
