### ISSUE TITLE
Changes in .editorconfig file are ignored on subsequent reruns

### ISSUE THREAD

**Issue by G00fY2** [JLLeitschuh/ktlint-gradle#456]
After updating to ktlint 0.41.0 I get:
```
A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   java.lang.RuntimeException: Unexpected imports layout: "*,java.**,javax.**,kotlin.**,^"
```

I know about the changes made regarding https://github.com/pinterest/ktlint/pull/1018 and tried different configurations in my .editorconfig. But non of these seems to work:

> kotlin_imports_layout=idea
> ij_kotlin_imports_layout=*
> ij_kotlin_imports_layout=*,java.**,javax.**,kotlin.**,^

Not sure if this is an incompatibility with the plugin oder a general ktlint issue.

Plugin Version: 10.0.0
Ktlint Version: 0.41.0
Gradle Version: 6.8.3
Android Studio: 4.1.2

**Comment by G00fY2** [comment]
Thats the project where I tried to update ktlint: https://github.com/G00fY2/quickie

**Comment by romtsn** [comment]
@G00fY2 I've just tried your project, and it works fine for me. You probably ran into some internal caching of ktlint, hence were facing the old error, even though the imports_layout has been changed to the correct one.

Just to reinforce, this is how it should be defined in the `.editorconfig` to comply with IDEA and ktlint:
```editorconfig
ij_kotlin_imports_layout=*,java.**,javax.**,kotlin.**,^
```
and then `./gradlew ktlintCheck --rerun-tasks` to make sure you're not hitting the invalid cache.

**Comment by G00fY2** [comment]
Hmm, yeah you are right. Has to be some caching issue. I just updated everything and the[ CI builds run fine](https://github.com/G00fY2/quickie/runs/2140066962?check_suite_focus=true).

I also used the correct import regex (copy and pasted it from ktlint readme, not sure why the one in my description is different.

Sorry for  bringing this up.

**Comment by Tapchicoma** [comment]
Actually it is a bug in the plugin and how handles KtLint `.editorconfig` cache. Should be fixed for the next release.

**Comment by Tapchicoma** [comment]
Just FYI: as workaround you have to stop Gradle daemon (so it will kill workers) after any `.editorconfig` changes.

**Comment by amatkivskiy** [comment]
Thanks @Tapchicoma 

⚠️  For anyone facing an issue that ktlint ignores any changes in `.editorconfig` -> run `./gradlew --stop` and then rerun ktlint task.
