### ISSUE TITLE
JCenter Dependency Removal before JCenter Service Brown-Out Periods

### ISSUE THREAD

**Issue by james-kan-shopify** [JLLeitschuh/ktlint-gradle#460]
JCenter has announced it will no longer be available in the near future. Their timeline specifies that they will have service brown-out  outages between April 12th to April 26th, 2021. During this period, there will be various outages that can cause various build failures.

I've been testing to find dependencies and plugins that still use JCenter by re-routing JCenter connections to local host cause a resolution failure, and came across this dependency running into an error. (My repo uses MavenCentral)
<img width="951" alt="Screen Shot 2021-03-26 at 1 42 42 PM" src="https://user-images.githubusercontent.com/77418940/112690536-2fbb0d80-8e39-11eb-95bc-ebfb7406e9a9.png">

I've noticed in this repository, a recent commit has been made to remove JCenter: https://github.com/JLLeitschuh/ktlint-gradle/commit/09fcfa7d91cdbe1ed853a78ee6ac59fcdf318774

I was wondering if there's a timeline for when this change will be released? Or if there's a solution that could be suggested for the time being. I'm currently using an older version of this plugin.

Thanks!

**Comment by Tapchicoma** [comment]
You don't need to wait for this commit to be published in some release. Plugin itself shadows its dependencies inside jar. Only dependency that is not shadowed - another Gradle plugins (Kotlin, AGP). Plugin portal should already migrate plugins into internal repository: https://blog.gradle.org/jcenter-shutdown

Unfortunately Kotlin compiler uses `trove4j` dependency that hasn't been yet republished to Maven Central: https://youtrack.jetbrains.com/issue/IDEA-261387. After it will be moved - you will not need `jcenter()`.
