### ISSUE TITLE
Document how to execute it on Java 16

### ISSUE THREAD

**Issue by lukas-krecan** [JLLeitschuh/ktlint-gradle#461]
Can you please document how to execute the plugin on Java 16 with stricter module check. It's necessary to pass a JVM argument to open java.base module, but I could not find how to do it. See this [SO question](https://stackoverflow.com/questions/66806195/gradle-ktlint-plugin-fails-on-java-16).

**Comment by Tapchicoma** [comment]
I think you have to use Gradle 7 as it only in this release have added [JDK 16 support](https://docs.gradle.org/7.0-rc-1/release-notes.html#java-16).

If it will not help, please let me know.

**Comment by lukas-krecan** [comment]
That's a pity. It seems that the rest of the ecosystem works with Gradle 6 and Java 16 (Kotlin compiler, Koltin DSL, ...). I would expect that somehow passing `org.gradle.jvmargs` to the Gradle plugin execution should help, but my knowledge of Gradle plugins is limited.

**Comment by Tapchicoma** [comment]
Interesting, I will see if it can be fixed from the plugin side :thinking: 

/cc @JLLeitschuh

**Comment by JLLeitschuh** [comment]
Supposedly, support for Java 16 is only in Gradle 7. I'd advise that we add it to the matrix for CI and see what fails.

**Comment by ZacSweers** [comment]
Kotlin itself doesn't really support JDK 16 until Kotlin 1.5
