### ISSUE TITLE
[Question] no additional tasks have been added to the project

### ISSUE THREAD

**Issue by ispite** [JLLeitschuh/ktlint-gradle#466]
Hello, no additional tasks have been added to the project
```
addKtlintCheckGitPreCommitHook 
addKtlintFormatGitPreCommitHook
```
but there are other tasks added, what should I do to add them?

**Comment by Tapchicoma** [comment]
They are only added when plugin is applied to the Gradle root project.

Please use Github discussions next time for such questions.
