### ISSUE TITLE
Having difficulty installing/using on an offline machine

### ISSUE THREAD

**Issue by jonapoul** [JLLeitschuh/ktlint-gradle#478]
So I have an offline Maven repository where I host all of my project's dependencies. I've got ktlint-gradle hosted on there, specifically the following as pulled from [plugins.gradle.org](https://plugins.gradle.org/m2/org/jlleitschuh/gradle/ktlint-gradle/9.4.1/):
```
ktlint-gradle-9.4.1.pom
ktlint-gradle-9.4.1-sources.jar
ktlint-gradle-9.4.1-javadoc.jar
ktlint-gradle-9.4.1.jar
```

When I try to sync my project with this setup, I get an error saying:
```
Could not GET 'http://path/to/my/repo/org/jlleitschuh/gradle/ktlint-gradle/9.4.1/ktlint-gradle-9.4.1.module'. Received status code 500 from server: Unable to fetch artifact resource.
```
The POM file includes the following commented-out snippet:
```xml
  <!-- This module was also published with a richer model, Gradle metadata,  -->
  <!-- which should be used instead. Do not delete the following line which  -->
  <!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
  <!-- that they should prefer consuming it instead. -->
  <!-- do_not_remove: published-with-gradle-metadata -->
```
However I've not been able to find this richer Gradle metadata anywhere, which I assume is the `.module` file referenced in the error message. Not on plugins.gradle, not on maven central, nowhere. Could someone please point me in the right direction here?

**Comment by Tapchicoma** [comment]
Sorry, I have no idea how Gradle Plugin portal is working and why `.module` files is not there, maybe @JLLeitschuh  could help here more.

As alternative solution - you could fork this repo and publish it manually to your local maven directory.

**Comment by JLLeitschuh** [comment]
The Gradle Plugin Portal doesn't support `.module` files yet.

@jonapoul, can you send us the top couple of lines from the `ktlint-gradle-9.4.1.pom` file?

**Comment by jonapoul** [comment]
@JLLeitschuh 

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- This module was also published with a richer model, Gradle metadata,  -->
  <!-- which should be used instead. Do not delete the following line which  -->
  <!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
  <!-- that they should prefer consuming it instead. -->
  <!-- do_not_remove: published-with-gradle-metadata -->
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.jlleitschuh.gradle</groupId>
  <artifactId>ktlint-gradle</artifactId>
  <version>9.4.1</version>
</project>
```

**Comment by JLLeitschuh** [comment]
🤔 This is interesting. The plugin portal doesn't support this file, but we publish a POM asking Gradle to look for it.

**Comment by jonapoul** [comment]
I know. When I grab it directly from plugins.gradle.org it works a-OK, but when I mirror that on my local repo it doesn't go.

**Comment by JLLeitschuh** [comment]
Can you open a bug against `gradle/gradle` and link to this issue? This is a bug with the Gradle Plugin Portal Publish plugin publish plugin.

**Comment by miguelflores1993** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':amplify_core'.
> Could not resolve all artifacts for configuration ':amplify_core:classpath'.
   > Could not resolve org.jlleitschuh.gradle:ktlint-gradle:9.4.1.
     Required by:
         project :amplify_core
      > Could not resolve org.jlleitschuh.gradle:ktlint-gradle:9.4.1.
         > Could not get resource 'https://plugins.gradle.org/m2/org/jlleitschuh/gradle/ktlint-gradle/9.4.1/ktlint-gradle-9.4.1.module'.
            > Could not GET 'https://jcenter.bintray.com/org/jlleitschuh/gradle/ktlint-gradle/9.4.1/ktlint-gradle-9.4.1.module'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 59s
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Running Gradle task 'assembleDevDebug'...
[flutter_background_geolocation] Purging debug resources in release build
[flutter_background_geolocation] Purging debug resources in release build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':amplify_core'.
> Could not resolve all artifacts for configuration ':amplify_core:classpath'.
   > Could not resolve org.jlleitschuh.gradle:ktlint-gradle:9.4.1.
     Required by:
         project :amplify_core
      > Could not resolve org.jlleitschuh.gradle:ktlint-gradle:9.4.1.
         > Could not get resource 'https://plugins.gradle.org/m2/org/jlleitschuh/gradle/ktlint-gradle/9.4.1/ktlint-gradle-9.4.1.module'.
            > Could not GET 'https://jcenter.bintray.com/org/jlleitschuh/gradle/ktlint-gradle/9.4.1/ktlint-gradle-9.4.1.module'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 9s
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
Exception: Gradle task assembleDevDebug failed with exit code 1

**Comment by JLLeitschuh** [comment]
This was due to the JCenter outage.

I'm going to close this issue as not our bug. This is a bug upstream in Gradle. Please open issues of this nature aginst https://github.com/gradle/gradle
