### ISSUE TITLE
Publish releases after every PR is merged

### ISSUE THREAD

**Issue by JLLeitschuh** [JLLeitschuh/ktlint-gradle#48]
This is just a practice that I need to start doing myself.

I need to remember to do this so I don't end up having people wait on me to get things released.

Maybe I can automate this but for now this is just a practice I need to get into the habit of doing.

**Comment by Tapchicoma** [comment]
I think this can be closed :wink:

**Comment by wolfs** [comment]
Please publish a new release given that some PRs have been merged. I am especially interested in #84 😀

**Comment by JLLeitschuh** [comment]
I've been meaning to. I just wanted to close #82 before releasing. So as soon as #87 is merged, I'll make a release.

**Comment by wolfs** [comment]
Awesome! Thanks!

**Comment by JLLeitschuh** [comment]
`3.3.0` is out.

**Comment by Tapchicoma** [comment]
Closing this as autopublishing is now working :tada:
