### ISSUE TITLE
KtlintExtension file filter ignored

### ISSUE THREAD

**Issue by Synesso** [JLLeitschuh/ktlint-gradle#484]
In my `build.gradle.kts` I have:

```
  configure<KtlintExtension> {
    additionalEditorconfigFile.set(file(".editorconfig"))
    filter {
      exclude("client/build/", "public-protos/", "server/build/")
    }
  }
```

Files under those three paths are not being excluded.

I have also tried globs such as `"**/generated/"`. They don't work either.

v10.0.0 with ktlint 0.40.0

**Comment by Synesso** [comment]
My bad. Gradle is hard.

**Comment by Synesso** [comment]
The values client, public-protos and server are subprojects, so it makes sense that those values would not work.
But I've retried with

```exclude("**/generated/")```

and generated sources are still evaluated.

**Comment by Synesso** [comment]
Also ```      exclude("**/build/generated/**/*.kt")```
and ```      exclude("**/build/generated/**")```

Nothing has any effect.

**Comment by Tapchicoma** [comment]
Please check 3rd question in [faq](https://github.com/JLLeitschuh/ktlint-gradle#faq). Otherwise please provide reproduction project.

**Comment by Synesso** [comment]
TY
