### ISSUE TITLE
Ktlint check pre-commit hook includes unstaged changes

### ISSUE THREAD

**Issue by Kantis** [JLLeitschuh/ktlint-gradle#490]
Reproduction:
1. Add an unused import to a file
2. Stage the file and try to commit -> precommit hook will fail the commit
3. Remove the import
4. Without staging the file, try to commit -> commit will be allowed with unused import being commited

Behaviour is inconsistent with manually running `./gradlew ktlintCheck` while having unstaged fixes, which will correctly complain about the unused import.

**Comment by Kantis** [comment]
Could probably be solved similar to #470

**Comment by KotlinIsland** [comment]
This is exactly the issue that was fixed in #470.

**Comment by Kantis** [comment]
Thanks for the info @KotlinIsland! `10.10` came out after the issue was created and I haven't gotten around to testing it. Thanks for fixing it 👍🏼
