### ISSUE TITLE
Any support for non-incremental ktlintCheck?

### ISSUE THREAD

**Issue by abubics** [JLLeitschuh/ktlint-gradle#491]
I've looked through the readme and open/closed issues, but can't find anything relevant :)

Is there any option to make ktlint not show incremental violations only? (short of also running `clean` (slow), or manually deleting the `build/intermediates/ktlint` directory / contents)

This behaviour is great for CI, where it will always start from a clean build, but locally if I run the lint check, fix some files manually, then run it again, it will pass while there are still outstanding issues.

The only other workflow I can think of is to always use the `ktlintFormat` task instead, which is ok (if inflexible) except where fixes aren't automatic.

**Comment by gustavkarlsson** [comment]
The incremental nature of `ktlintCheck` seems like a very weird behavior in general. I thought it's a bug until I found the section in the README that explains it. Or am I misunderstanding this?

Isn't the whole point of any "check" that it's a pure function? I.e. produces the same result every time given the same inputs?
