### ISSUE TITLE
Baseline file not created

### ISSUE THREAD

**Issue by ebrowne72** [JLLeitschuh/ktlint-gradle#496]
Using v10.1.0.

I have an Android project with many modules. In the main project build script we have the following:

```
subprojects {
    apply plugin: 'org.jlleitschuh.gradle.ktlint'

    // Global ktlint config
    ktlint {
        enableExperimentalRules.set(true)
        baseline.set(file("my-project-ktlint-baseline.xml"))
        outputColorName = "RED"
        outputToConsole = true
        verbose = true
        reporters {
            reporter "checkstyle"
        }
        filter {
            // Exclude generated files
            exclude("**/build/**")
            exclude("**/KtAnalyticsEvents.kt")
        }
    }
}
```

When I run the `ktlintCheck` task, the baseline file is not created.

**Comment by Tapchicoma** [comment]
Baseline is generated using special task - `ktlintGenerateBaseline`. Will add it to project readme.

**Comment by ebrowne72** [comment]
Cool, that worked.

But why did it create an empty baseline file in config/ktlint?

**Comment by Tapchicoma** [comment]
If you don't have any codestyle violations baseline will be empty.

**Comment by ebrowne72** [comment]
But why does it create the config/ktlint folder just to put an empty baseline file in it?

**Comment by Tapchicoma** [comment]
Yes, make sense to not generate baseline file if there are no lint errors present.

**Comment by JLLeitschuh** [comment]
@gabitheiss please open a new issue and include a stack trace
