### ISSUE TITLE
Precommit hook causes conflicts and doesn't commit changes

### ISSUE THREAD

**Issue by GrahamBorland** [JLLeitschuh/ktlint-gradle#497]
With 10.1.0, and the latest precommit hook from 10.1.0.

1. Make a badly-formatted change to a file.
2. Stage the change.
3. Commit.
4. Observe that the change has not been committed, and the file is now showing a conflict.

<img width="636" alt="CleanShot 2021-06-07 at 11 34 40@2x" src="https://user-images.githubusercontent.com/5768767/121002882-bfa7fc80-c784-11eb-8cfb-84ca58a13c6c.png">

**Comment by gabrielittner** [comment]
I'm also seeing this
<img width="1896" alt="Screenshot 2021-06-08 at 18 17 54" src="https://user-images.githubusercontent.com/1358105/121221510-edc13580-c885-11eb-8029-164bf5db47d5.png">

**Comment by KotlinIsland** [comment]
This is because the hook is using `git stash push --keep-index` which keeps the index, but also adds it to the stash.

I'm going to implement a fix for this that will use a temp diff file instead. expect a pr soon.
