### ISSUE TITLE
Incorrect xml settings after plugin application

### ISSUE THREAD

**Issue by stMayhem** [JLLeitschuh/ktlint-gradle#519]
All xml rules were removed in code style settings after I used `applyToIDEAProject` task.
Before:
![image](https://user-images.githubusercontent.com/16138832/127985023-63a264e7-0994-4485-a51e-f92eafcd32a1.png)
After:
![image](https://user-images.githubusercontent.com/16138832/127985076-845a0665-517e-437e-835a-71d9f14d3530.png)

**Comment by Tapchicoma** [comment]
This functionality comes from KtLint itself, though it is not actively supported there. Please open a new issue in KtLint project.
