### ISSUE TITLE
Cannot exclude generated code

### ISSUE THREAD

**Issue by NikolayMetchev** [JLLeitschuh/ktlint-gradle#522]
We are using the jooq gradle plugin to generate some kotlin code (https://github.com/etiennestuder/gradle-jooq-plugin)
Obviously I would like to exclude this code from ktlint. 
Code gets generated in <project>/build/generated-src
It seems this is impossible.
Here is the attempt I made:
```
ktlint {
    version = libs.versions.ktlint.get()
    debug = true
    verbose = true
    filter {
        include { element ->
            println(element.file.path)
            println(!element.file.path.contains("generated-src"))
            !element.file.path.contains("generated-src")
        }
        exclude { element ->
            println(element.file.path)
            println(element.file.path.contains("generated-src"))
            element.file.path.contains("generated-src")
        }
    }
}
```

With the above kode ktlint still fails on the generated code.

**Comment by dlurton** [comment]
I have a similar setup with a `generated-src` directory and for the life of me I could not make the plugin exclude that directory.  

However, I found that if I: `rm -rf .gradle` and then `./gradlew ktlintCheck` the exclusions worked just fine.  This suggests to me that the plugin is simply re-running `ktlint` on the same files it failed on previously without re-applying exclude filter, which is likely to change after fails.

Seems like a legit bug.

**Comment by KacperKenjiLesniak** [comment]
> I have a similar setup with a `generated-src` directory and for the life of me I could not make the plugin exclude that directory.
> 
> However, I found that if I: `rm -rf .gradle` and then `./gradlew ktlintCheck` the exclusions worked just fine. This suggests to me that the plugin is simply re-running `ktlint` on the same files it failed on previously without re-applying the exclude filter.
> 
> Seems like a legit bug.

That did the trick for me, thanks!

**Comment by OckyKristanto-TomTom** [comment]
I can also confirm that we also face same issue in our company.
remove `.gradle` in root project folder indeed does the trick. 

PS: it will be great if we can have a fix for this issue

**Comment by NickTomlin** [comment]
Just ran into this as well; I have generated Kojos from `graphql` schema and this makes this plugin unusable. I'm exploring `spotless` which wraps `ktlint` and seems to work fine.

**Comment by JLLeitschuh** [comment]
Have you tried `exclude("**/generated-src/**")`?

**Comment by NikolayMetchev** [comment]
Here is how I got it to work:
```
ktlint {
    filter {
        exclude { entry ->
            entry.file.toString().contains("generated")
        }
    }
}
```

**Comment by miikeat** [comment]
@NikolayMetchev your solution didn't work for me, but after i added these clean... tasks it works:

```
import org.jlleitschuh.gradle.ktlint.tasks.GenerateReportsTask
import org.jlleitschuh.gradle.ktlint.tasks.KtLintCheckTask

tasks {
    withType<GenerateReportsTask> {
        dependsOn("clean${name.capitalize()}")
    }
    withType<KtLintCheckTask> {
        dependsOn("clean${name.capitalize()}")
    }
}
```
This way ktlint is executed every time over all source files when ktlintCheck is executed

**Comment by Klewerro** [comment]
It doesn't work with all libraries.
In my case I'm using SqlDelight, which generates code independent of gradle (as far as I understand it), so using `./gradlew --no-build-cache ktlintCheck` is still failing, because code is already generated. Before when I had problems with linting generated files, that command used to work.
