### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by SumeraMartin** [JLLeitschuh/ktlint-gradle#53]
Hi, can you release new version of this library? Readme already contains changes like `outputToConsole = true` and `reporters = ["PLAIN", "CHECKSTYLE"]` but latest version doesn't implement them which is confusing. Thank you

**Comment by JLLeitschuh** [comment]
I'll try to get to it during Friday. remind me if I forget.

**Comment by SumeraMartin** [comment]
I'm reminding you that you wanted release a new version

**Comment by JLLeitschuh** [comment]
`3.0.1` has been released. Thanks for your patience!
