### ISSUE TITLE
Multi project configuration

### ISSUE THREAD

**Issue by mreigosa** [JLLeitschuh/ktlint-gradle#537]
I'd like to configure the plugin in an external config repo to include the same configuration among different projects. I'm trying to configure the plugin in a .gradle file different than `build.gradle` but I'm not sure this is possible.

The idea is to have the ktlint plugin configuration in a `ktlint.gradle` and then use the gradle `apply from: 'ktlint.gradle'` in the projects I wan to apply that configuration.

**Comment by mreigosa** [comment]
I'm closing the issue as we finally solved it by adding the classpath part in the build.gradle.

**Comment by Tapchicoma** [comment]
FYI check Gradle convention plugins. You could also publish them. Probably would better suit your needs.
