### ISSUE TITLE
Problem with setting the report output directory

### ISSUE THREAD

**Issue by taynagualbertoimpacta** [JLLeitschuh/ktlint-gradle#546]
Hi,

I'm trying to change the report output directory, but I'm getting an error when I include the configuration on my grade file:

```
plugins {
    id "org.jlleitschuh.gradle.ktlint" version "10.2.0"
}

subprojects {
    apply plugin: "org.jlleitschuh.gradle.ktlint"

    repositories {
        // Required to download KtLint
        mavenCentral()
    }

    ktlint {
        debug = true
        android = true
        baseline = file("ktlint-baseline.xml")
        ignoreFailures = false
        reporters {
            reporter "plain"
        }
    }

    tasks.withType(org.jlleitschuh.gradle.ktlint.tasks.GenerateReportsTask) {
        reportsOutputDirectory = project.layout.buildDirectory.dir("/reports/kotlin-lint/${project.name}-lint-report.txt")
    }
}
```

Error:
```
groovy.lang.MissingPropertyException: Could not get unknown property 'org' for project ':base' of type org.gradle.api.Project.
```

Kotlin Version: 1.5.31
Gradle Version: 7.0.2

Am I including the `tasks` configuration in the right place? 

Thanks in advance.

**Comment by taynagualbertoimpacta** [comment]
I just move the below block to the end of the root project's build.gradle and now the error is gone. 🙌 

```
tasks.withType(org.jlleitschuh.gradle.ktlint.tasks.GenerateReportsTask) {
    reportsOutputDirectory = project.layout.buildDirectory.dir("/reports/kotlin-lint/${project.name}-lint-report.txt")
}
``

**Comment by nuhkoca** [comment]
Not %100 sure but I think it is because of that you are trying to create a `txt` file not a directory. Either replace `dir` with `file` as following

> tasks.withType(org.jlleitschuh.gradle.ktlint.tasks.GenerateReportsTask) {
>     reportsOutputDirectory = project.layout.buildDirectory.file("reports/kotlin-lint/${project.name}-lint-report.txt")
> }

or modify your current code by

> tasks.withType(org.jlleitschuh.gradle.ktlint.tasks.GenerateReportsTask) {
>     reportsOutputDirectory = project.layout.buildDirectory.dir("reports/kotlin-lint")
> }
