### ISSUE TITLE
Please upd for new fixed version of ktlint after fix https://github.com/pinterest/ktlint/issues/1256

### ISSUE THREAD

**Issue by YauheniPo** [JLLeitschuh/ktlint-gradle#547]

**Comment by JLLeitschuh** [comment]
https://github.com/pinterest/ktlint/issues/1256

**Comment by JLLeitschuh** [comment]
You can also specify a custom ktlint version

```kotlin
configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
    version.set("0.22.0")
}
```

**Comment by YauheniPo** [comment]
@JLLeitschuh 
`
BUILD FAILED in 2s
1 actionable task: 1 executed
epopovich@MacBook-Pro-Yauheni ft % ./gradlew ktlintCheck
> Task :loadKtlintReporters FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':loadKtlintReporters'.
> KtLint versions less than 0.34.0 are not supported. Detected KtLint version: 0.22.0.

`

**Comment by JLLeitschuh** [comment]
What version did you specify?

**Comment by YauheniPo** [comment]
we use
`
buildscript {
    dependencies {
        classpath("com.google.protobuf:protobuf-gradle-plugin:${Versions.protobufPlugin}")
        classpath("org.jlleitschuh.gradle:ktlint-gradle:${Versions.ktlintPlugin}")
    }
    repositories {
        maven {
            url = uri("https://plugins.gradle.org/m2/")
        }
    }
}

apply(plugin = "org.jlleitschuh.gradle.ktlint")

plugins {
    kotlin("jvm") version Versions.kotlin
    id("java")
}

tasks.build {
    dependsOn("ktlintFormat")
}

subprojects {
    // Run ktlint check './gradlew ktlintCheck' for returning list of issues
    // Run ktlint format './gradlew ktlintFormat' for fixing issues
    // Add '--continue' option if you don't want to stop task execution in case of some of the subprojects tasks failed
    apply(plugin = "org.jlleitschuh.gradle.ktlint")

    configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
        debug.set(true)
        verbose.set(true)
        android.set(false)
        outputToConsole.set(true)
        outputColorName.set("RED")
        ignoreFailures.set(false)
        enableExperimentalRules.set(true)
        reporters {
            reporter(org.jlleitschuh.gradle.ktlint.reporter.ReporterType.HTML)
            reporter(org.jlleitschuh.gradle.ktlint.reporter.ReporterType.CHECKSTYLE)
        }
    }

    task("printVersion") {
        doLast {
            println(version)
        }
    }
}`

const val ktlintPlugin = "10.2.0"

**Comment by JLLeitschuh** [comment]
Try adding:

```kotlin
allprojects {
    configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
        version.set("0.42.1")
    }
}
```
