### ISSUE TITLE
Task :app:runKtlintCheckOverMainSourceSet FAILED

### ISSUE THREAD

**Issue by shalva97** [JLLeitschuh/ktlint-gradle#578]
Hi, I have added this plugin to Gradle, everything works except `ktlintGenerateBaseline` task

Here is what happens when I apply the plugin to only `app` module:

```
* What went wrong:
Execution failed for task ':app:runKtlintCheckOverMainSourceSet'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   > Java heap space
```

It is an Android project so I have tried to increase memory with `org.gradle.jvmargs=-Xmx8000m` line inside `gradle.properties` but it did not solve the issue.

Same error shows up when applying it to all projects. Also it seems to have generated few xml files for some small modules... 

Maybe it is because of too many lint errors? the project is like 5-6 years old.

And another error, I forgot how I caused but here it is:
```
Execution failed for task ':app:runKtlintCheckOverMainSourceSet'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   > Java heap space: failed reallocation of scalar replaced objects
```

**Comment by andrewaac** [comment]
I am experiencing the same issue with a large and messy project

**Comment by vidsag** [comment]
increase heap size.

`tasks.withType(org.jlleitschuh.gradle.ktlint.tasks.BaseKtLintCheckTask).configureEach {
    it.workerMaxHeapSize.set("2048m")
}`

Add the above to your gradle file.

**Comment by wakingrufus** [comment]
configuring the worker heap is a good solution to this problem, and since this issue depends on the complexity of the project, I don't think a different default would be ideal, so I'll leave it there.
