### ISSUE TITLE
Add a way to run check for non-JVM projects

### ISSUE THREAD

**Issue by mverleg** [JLLeitschuh/ktlint-gradle#58]
Feature request: _Could some way be added to check code for other platforms than JVM?_

I have a multiplatform module but the kotlin-common and kotlin-javascript code is skipped. Most of the code is kotlin-common, which should be a subset of kotlin-JVM I think.

I'm not sure how hard this is but I'll just suggest it (I'm not really sure how the platform relates to style checks).

**Comment by mverleg** [comment]
(I'm afraid I can't be much help implementing the feature because I'm not great with Gradle, and Gradle hates me).

**Comment by mverleg** [comment]
I found there's another solution I can use. I'll leave the issue for others to evaluate the usefulness (I feel like most other people are on JVM).

**Comment by JLLeitschuh** [comment]
Do you want to share the alternative solution you came up with?

**Comment by mverleg** [comment]
Thanks for the suggestions :-) I spent some time with Gradle stuff but I still get stuck a lot.

I wasn't sure if it was considered impolite to mention 'competing' libraries here... The solution was that I'm using Spotless because of the non-JVM code.

**Comment by Tapchicoma** [comment]
Indeed would be nice to add such support. Should be not difficult - just add `kotlin2js` and other types plugins to supported one.

Actually we can start with js support and and the introduce it for native (version `0.6` introduces Gradle plugin).

@mverleg would be really nice if you can introduce some multiplatform sample for this project.

**Comment by JLLeitschuh** [comment]
> I wasn't sure if it was considered impolite to mention 'competing' libraries here...

I'm one of the maintainers of Spotless and I use it at my company over my own plugin (blasphemous, I know 😆).
You're amongst friends here.

**Comment by mverleg** [comment]
@Tapchicoma Do you mean a sample project to try this on? I happen to have a demo project for multiplatform Kotlin Gradle setup with some subprojects, interdependencies and actual/expect. It has no real code, it's just to experiment with multiplatform setup. Welcome to try with that. https://github.com/mverleg/kotlin_multiplatform_gradle_demo . It doesn't have Kotlin Native yet, but I might add it when it's more officially compatible with kotlin-common.

**Comment by Tapchicoma** [comment]
@mverleg this project has some samples and it would be nice to also add some multiplatform sample, so we can test plugin setup and see that it works correctly.

**Comment by Tapchicoma** [comment]
Missing plugins:
- kotlin2js (javascript)
- konan (native)
- kotlin-platform-common
- kotlin-platform-js
- kotlin-platform-jvm

Samples inspirational repo: https://github.com/JetBrains/KotlinMultiplatformPlayground

**Comment by Tapchicoma** [comment]
Should work with `3.1.0` version of the plugin.
