### ISSUE TITLE
The plugin does not work when using Ktlint 0.46.0

### ISSUE THREAD

**Issue by mars885** [JLLeitschuh/ktlint-gradle#589]
The Ktlint [0.46.0](https://github.com/pinterest/ktlint/releases/tag/0.46.0) has been released recently with breaking API changes that make using the plugin impossible. One such change is that Ktlint.Params class has been renamed into the [ExperimentalParams](https://github.com/pinterest/ktlint/blob/master/ktlint-core/src/main/kotlin/com/pinterest/ktlint/core/KtLint.kt#L61).

As a result of this, when I run the `./gradlew ktlintCheck --continue` command, I get the following:
```
> Task :app:runKtlintCheckOverKotlinScripts FAILED
> Task :app:runKtlintCheckOverMainSourceSet FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:runKtlintCheckOverKotlinScripts'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   > com/pinterest/ktlint/core/KtLint$Params

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:runKtlintCheckOverMainSourceSet'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   > com/pinterest/ktlint/core/KtLint$Params

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
10 actionable tasks: 3 executed, 7 up-to-date
```
The versions used are the following:
- ktlint-gradle: `10.3.0`
- ktlint: `0.46.0`

**Comment by JLLeitschuh** [comment]
@scana could you do so in such a way that preserves backwards compatibility by using reflection to call the old APIs?

**Comment by scana** [comment]
@JLLeitschuh unfortunately not, because they have also changed `ReporterProvider` signature to `ReporterProvider<T : Reporter>`

**Comment by jzeferino** [comment]
with:

tlint-gradle: 10.3.0
ktlint: 0.46.1

still getting the following exception:

<img width="672" alt="Screenshot 2022-08-17 at 13 07 28" src="https://user-images.githubusercontent.com/10722952/185114538-dc0ba776-0e25-4552-b131-1308ec605a12.png">

**Comment by mikehardy** [comment]
Please take this in the light-hearted spirit it is intended but: change all the things, issue a major version (semantic-version-wise) and sleep well at night :-)

**Comment by G00fY2** [comment]
As stated [here](https://github.com/JLLeitschuh/ktlint-gradle/pull/595#issuecomment-1226902692) I think even though there was the 11.0.0 major release, this issue is still unchanged.

**Comment by DmitriyZaitsev** [comment]
Same shit with all ktlint versions >0.45.2, including 0.47.0

**Comment by mikehardy** [comment]
@DmitriyZaitsev that's a :hankey: comment, good sir. Were I the maintainer, I'd wager it's demotivating. In your 3 public contributions on github in the last year, it's a shame you have not found time to fix this :hankey:. I guess we'll have to wait then

**Comment by scottkennedy** [comment]
> Please take this in the light-hearted spirit it is intended but: change all the things, issue a major version (semantic-version-wise) and sleep well at night :-)

Given how long this issue has been open and unresolved, is this something we could do?  Create a 12.0.0 and just say that as of that version of this plugin, only ktlint 0.46.0 and newer are supported?

**Comment by konstantin-rudoi** [comment]
The same problem
```
Execution failed for task ':app:runKtlintCheckOverKotlinScripts'.
Execution failed for task ':app:runKtlintCheckOverMainSourceSet'.
Execution failed for task ':app:runKtlintCheckOverTestSourceSet'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   > com/pinterest/ktlint/core/KtLint$Params
```

**Comment by wakingrufus** [comment]
My pr #620 will resolve this issue. I am putting the finishing touches on it and will hopefully merge it later this week

**Comment by JLLeitschuh** [comment]
https://github.com/JLLeitschuh/ktlint-gradle/releases/tag/v11.1.0
