### ISSUE TITLE
Indentation bug on 10.3.0

### ISSUE THREAD

**Issue by erdaldogan** [JLLeitschuh/ktlint-gradle#590]
Hi,

When I run`gradle :ktlintCheck` on the file with following piece of code;

```
        val rowMapper: RowMapper<Pair<String, String>> = RowMapper<Pair<String, String>> {
                resultSet: ResultSet, rowIndex: Int ->
            Pair(resultSet.getString("version"), resultSet.getString("description"))
        }
```

I'll get the error
``` 
> Task :ktlintTestSourceSetCheck FAILED
**/configuration/FlywayConfigurationIT.kt:65:1 Unexpected indentation (16) (should be 12)
```
Line 65 is the one right after function signature, `resultSet: ResultSet, rowIndex: Int ->`.

We are using `version "10.2.0"` (same issue w/ `10.3.0`). This is neither the case with `ktlint 0.46.0` nor the [ktlint-intellij-plugin 0.9.1](https://github.com/nbadal/ktlint-intellij-plugin)

**Comment by balakzde** [comment]
Similar problem
`fun Activity.turnScreenOnAndKeyguardOff() {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O_MR1) {
        setShowWhenLocked(true)
        setTurnScreenOn(true)
    } else {
        window.addFlags(
            WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON or
                    WindowManager.LayoutParams.FLAG_ALLOW_LOCK_WHILE_SCREEN_ON or
                    WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED or
                    WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON
        )
    }

    with(getSystemService(Context.KEYGUARD_SERVICE) as KeyguardManager) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            requestDismissKeyguard(this@turnScreenOnAndKeyguardOff, null)
        }
    }
}`

Unexpected indentation (20) (should be 16)
for these lines:
WindowManager.LayoutParams.FLAG_ALLOW_LOCK_WHILE_SCREEN_ON or
WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED or
WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON


I use official kotlin style formatter and it always corrects it back from 16 to 20

**Comment by AleksanderBrzozowski** [comment]
@erdaldogan can you provide the minimum example of a project that replicates the issue?
I am not sure if the reason is in plugin or it is in ktlint :)

**Comment by wakingrufus** [comment]
11.2.0 is now released which will allow you to use a newer ktlint version
