### ISSUE TITLE
Context Receivers...

### ISSUE THREAD

**Issue by caeus** [JLLeitschuh/ktlint-gradle#599]
This plugin doesn't work with context receivers, so I'm wondering if theres a way I can use the snapshot version of pinterest/ktlint...

**Comment by AleksanderBrzozowski** [comment]
what do you mean? Which version of ktlint plugin supports context receivers?

**Comment by osoykan** [comment]
Having the same issue, I think we need a snapshot version of the plugin that uses pinterest/ktlint's snapshot.

**Comment by rcd27** [comment]
> what do you mean? Which version of ktlint plugin supports context receivers?

![image](https://user-images.githubusercontent.com/20042955/203790848-b42d4c0b-8c31-42f5-89cd-f7d3150b2094.png)

**Comment by AleksanderBrzozowski** [comment]
> > what do you mean? Which version of ktlint plugin supports context receivers?
> 
> ![image](https://user-images.githubusercontent.com/20042955/203790848-b42d4c0b-8c31-42f5-89cd-f7d3150b2094.png)
> 
> He means when we use context receivers, `ktlint-gradle` fails with parsing files.

Yep, that's true, I suggest to switch to other plugin - https://github.com/jeremymailen/kotlinter-gradle

**Comment by wakingrufus** [comment]
try with 11.1.0, this plugin now supports newer versions of ktlint (https://github.com/JLLeitschuh/ktlint-gradle/pull/620)
