### ISSUE TITLE
Why does this lint differ from the plugin version in Android Studio?

### ISSUE THREAD

**Issue by dessalines** [JLLeitschuh/ktlint-gradle#614]
When I run `./gradlew ktlintCheck` on my repo, I get no issues.

When I go to Android studio, it has a bunch of ktlint issues, such as commas should not be included on the last list item.

These are both using full defaults, with no special config, just fresh installs.

What's the reason these lints are different, and is there any way to get them to match?

**Comment by RBusarow** [comment]
This plugin is pretty out of date, and using an older version of KtLint by default.  The IDE plugin is current.  The current version of KtLint has additional rules.

**Comment by dessalines** [comment]
Dang.... is there a fork that stays more updated, that we could pull from? I'm seeing a lot of open PRs here.

**Comment by RBusarow** [comment]
You can just use Kotlinter: https://github.com/jeremymailen/kotlinter-gradle

**Comment by dessalines** [comment]
Worked perfectly, thanks!
