### ISSUE TITLE
I would like ktlintFormat to not fail on the CI

### ISSUE THREAD

**Issue by jmfayard** [JLLeitschuh/ktlint-gradle#615]
Bonjour,
I have a GitHub workflow that runs ktlintFormat once a week
but it's super annoying because the smallest error prevent the workflow to work
and for my side I would be happy if ktlintFormat can solve 95% of my problems even if that's not 100%
rather than failing at the first error.

Is there a way to not have the task fail on the CI?

I'm not sure what `--continue` does but that's not what I have in mind.

See https://scans.gradle.com/s/lsgi5bx5vlhwg/console-log?anchor=44&page=1

Related to https://github.com/JLLeitschuh/ktlint-gradle/issues/613

**Comment by scottyab** [comment]
Does setting `ignoreFailures = false` work for you? you could have something like `ignoreFailures = {$!isCI}` if you wanted it to fail locally but not on the CI - maybe I've misunderstood what your after.

**Comment by wakingrufus** [comment]
I agree with @scottyab that `ignoreFailures` is the correct way to control this behavior.
