### ISSUE TITLE
Disable rule on a file 

### ISSUE THREAD

**Issue by Shahroz16** [JLLeitschuh/ktlint-gradle#617]
Hey there, I am looking for a way to disable a ktlint rule on file.

I have tried this but doesn't work

```
/* ktlint-disable filename */
```

Is there any way I can achieve this?

**Comment by wakingrufus** [comment]
this can be done using ktlint's built-in .editorconfig support:
https://pinterest.github.io/ktlint/rules/configuration-ktlint/#overriding-editorconfig-properties-for-specific-directories
