### ISSUE TITLE
Problem in 11.0.0 (wildcard imports)

### ISSUE THREAD

**Issue by TarasOryshhij** [JLLeitschuh/ktlint-gradle#619]
When updated from 10.2.1 to 11.0.0 receive a lot of FAILED tasks with Unnecessary import. 
`disabled_rules = no-wildcard-imports` - doesn't work in 11.0.0 version. 
I tried use latest ktlint version:
`
ktlint {
    version = "0.48.0"
    android = true
}
`
but then i received error:
1: Task failed with an exception.
What went wrong:
Execution failed for task ':app:runKtlintCheckOverMainSourceSet'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   > Could not create an instance of type org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction.
      > Could not generate a decorated class for type KtLintWorkAction.
         > com/pinterest/ktlint/core/ParseException

Thanks!

**Comment by 417-72KI** [comment]
I had a same issue, and temporary resolved by setting ktlint 0.45.2
```
ktlint { 
  version = "0.45.2"
}
```

**Comment by wakingrufus** [comment]
try with 11.1.0, this plugin now supports newer versions of ktlint (#620)
