### ISSUE TITLE
it doesn't support gradle 8.1.0-alpha01 - Android Studio Giraffe

### ISSUE THREAD

**Issue by LubosSytensky-cen86208** [JLLeitschuh/ktlint-gradle#621]
New Gradle has new method and the library is not compatible

**Comment by nuhkoca** [comment]
Same issue. `ktlintFormat` task constantly fails

**Comment by wakingrufus** [comment]
Since this version is not released yet, it could be a bug they will fix before release. Once gradle 8.1.0 is released, I will add it to the list of gradle versions we test against and see if the error reproduces.

**Comment by JLLeitschuh** [comment]
Regardless, it would help if you could provide the stack trace with the report.
