### ISSUE TITLE
kitlint 0.48.1 and "Property 'ktlint_disabled_rules' is deprecated" warning

### ISSUE THREAD

**Issue by nikclayton** [JLLeitschuh/ktlint-gradle#622]
Running `11.1.0` of the plugin, with this config block:

```
    ktlint {
        version = '0.48.1'
        android = true
    }
```

Generates hundreds of the following warnings (wrapped to two lines here, appears as one line in the output).

```
Property 'ktlint_disabled_rules' is deprecated: Update all your all '.editorconfig' files.
   See https://pinterest.github.io/ktlint/faq/#why-is-editorconfig-property-disabled_rules-deprecated-and-how-do-i-resolve-this for more information
```

Per that link, instead of a single `disabled_rules` line:

```
disabled_rules=rule-1,rule-2
```

the new approach is:

```
ktlint_<rulesetId>_rule-1=disabled
ktlint_<rulesetId>_rule-2=disabled
```

This confused the hell out of me because my project has no `.editorconfig` file. After digging through the plugin code I think the culprit is https://github.com/JLLeitschuh/ktlint-gradle/blob/main/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintInvocation.kt#L171, which inserts a "fake" editorconfig with a `disabled_rules` entry.

That will need to change.

This will probably be a breaking change for users, because if they have e.g.:

```
    disabledRules = [
        'import-ordering',
        'chain-wrapping',
        'no-blank-line-before-rbrace'
    ]
```

they will need to prepend the ruleset ID to each of those rule names.

**Comment by 417-72KI** [comment]
Same issue, and also `.editorconfig` with new approach does not work.

```.editorconfig
# (I couldn't concern which one is the correct key.)
ktlint_no-wildcard-imports = disabled
ktlint_standard_no-wildcard-imports = disabled
ktlint_experimental_no-wildcard-imports = disabled
```

```sh
> Task :common:ktlintTestSourceSetCheck
/path/to/file.kt:7:1 Wildcard import (cannot be auto-corrected)
/path/to/file.kt:10:1 Wildcard import (cannot be auto-corrected)
```

**Comment by hanrw** [comment]
same issue
```
Property 'ktlint_disabled_rules' is deprecated: Update all your all '.editorconfig' files. See https://pinterest.github.io/ktlint/faq/#why-is-editorconfig-property-disabled_rules-deprecated-and-how-do-i-resolve-this for more information
Property 'ktlint_disabled_rules' is deprecated: Update all your all '.editorconfig' files. See https://pinterest.github.io/ktlint/faq/#why-is-editorconfig-property-disabled_rules-deprecated-and-how-do-i-resolve-this for more information
Property 'ktlint_disabled_rules' is deprecated: Update all your all '.editorconfig' files. See https://pinterest.github.io/ktlint/faq/#why-is-editorconfig-property-disabled_rules-deprecated-and-how-do-i-resolve-this for more information
```

**Comment by scottkennedy** [comment]
I'm very happy the plugin now works with the latest ktlint, but this might actually be a blocker for me to upgrade to 0.48.1.  It's basically impossible to see the true output now.

**Comment by wakingrufus** [comment]
Thank you for the bug report. I will investigate this issue with 0.48.x compatibility

**Comment by wakingrufus** [comment]
please use ktlint 0.47.1 for now, while I investigate this. I hope to have a solution some time next week

**Comment by mikehardy** [comment]
Just wanted to say thanks in the first part for *allowing* the use of newer ktlint, that was a big step in the v11.1.0 release. Hopefully catching up to the breaking change they put in 0.48.x isn't too hard now that ktlint-gradle is unstuck. Cheers

**Comment by wakingrufus** [comment]
In my testing, i was able to set a disabled rule in .editorconfig, and ktlint will pick it up in 0.48+
for example:
```               
root = true

 [*.kt]
ktlint_standard_final-newline = disabled
```
however, when I do this, the warnings still print.
I am going to propose a fix which will avoid the warnings as long as you don't set the "disabled_rules" extension properties while using 0.48.x.

**Comment by wbonnefond** [comment]
Any chance of getting a release with this fix this week? I'd love to upgrade to latest versions of both ktlint and this plugin, but this is a blocker for us

**Comment by wakingrufus** [comment]
yes, @JLLeitschuh should be pushing the release in the next day or two

**Comment by scottkennedy** [comment]
With 11.2.0 and 0.48.1, I'm still getting a slew of these warnings, and the string "ktlint_disabled_rules" does not appear anywhere in my project.

**Comment by matsudamper** [comment]
Still happening on 11.2.0. Anyone have the same problems?

**Comment by krisgerhard** [comment]
Deprecated warnings disappeared for us with 11.2.0
