### ISSUE TITLE
java.lang.NoClassDefFoundError: com.pinterest.ktlint.core.internal.BaselineSupportKt

### ISSUE THREAD

**Issue by logi-nilsson** [JLLeitschuh/ktlint-gradle#626]
The file `com.pinterest.ktlint.core.internal.BaselineSupport` was renamed in this commit: [https://github.com/pinterest/ktlint/commit/1b0e5353437a85362ec01168c82632b6646895e7](https://github.com/pinterest/ktlint/commit/1b0e5353437a85362ec01168c82632b6646895e7)

The change was introduced in ktlint 0.46.0 and fails `org.jlleitschuh.gradle.ktlint.worker.GenerateReportsWorkAction`.

Temporary solution: use ktlint 0.45.2

Partial build log:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:ktlintMainSourceSetCheck'.
> Multiple task action failures occurred:
   > A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.GenerateReportsWorkAction
      > com.pinterest.ktlint.core.internal.BaselineSupportKt
   > A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.GenerateReportsWorkAction
      > com.pinterest.ktlint.core.internal.BaselineSupportKt
   > A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.ConsoleReportWorkAction
      > com.pinterest.ktlint.core.internal.BaselineSupportKt
```

**Comment by wakingrufus** [comment]
Thanks for the report!
This was fixed in https://github.com/JLLeitschuh/ktlint-gradle/commit/34e39afe40a505eb7601c56592e5cad78ce6bf90 and will be in the next release

**Comment by wakingrufus** [comment]
11.2.0 is now released with this fix

**Comment by logi-nilsson** [comment]
Thank you @wakingrufus <3
