### ISSUE TITLE
`.editorconfig` is not respected when running ktlint 0.46.1

### ISSUE THREAD

**Issue by stkent** [JLLeitschuh/ktlint-gradle#627]
Plugin version: 11.1.0

Rules disabled by an `.editorconfig` file when running ktlint 0.45.2 using this plugin are **no longer disabled when running ktlint 0.46.1** using this plugin.

Please see https://github.com/stkent/ktlint-debugging for a minimal reproduction.

I have verified that the rules are correctly disabled for both ktlint versions when run from the command line.

**Comment by stkent** [comment]
I believe this also affects newer-than-0.46.1 versions of ktlint when run using this plugin.

**Comment by wakingrufus** [comment]
I believe this was fixed in https://github.com/JLLeitschuh/ktlint-gradle/commit/2e3085062deca4f552b7d15af1a72344191d5b43 which has not been released yet. 
i opened a PR https://github.com/JLLeitschuh/ktlint-gradle/pull/628 to add a test to show that this is now working.

**Comment by stkent** [comment]
Thanks for the response, and the additional tests! Left a very minor comment over there.

**Comment by wakingrufus** [comment]
11.2.0 is now released with this fix

**Comment by stkent** [comment]
Thank you!

**Comment by hrules6872** [comment]
I don't know if it's related but since 0.48.+ `additionalEditorconfigFile` has stopped working.
The plugin only pay attention to the .editconfig file located in the root of the project (which I had to do as a workaround).

**Comment by wakingrufus** [comment]
> I don't know if it's related but since 0.48.+ `additionalEditorconfigFile` has stopped working.
> The plugin only pay attention to the `.editconfig` file located in the root of the project (which I had to do as a workaround).

This sounds like it might be a totally different issue. Will you please open a seperate ticket fir this? I will investigate
