### ISSUE TITLE
Support v11.2.0

### ISSUE THREAD

**Issue by hblab-tiendv** [JLLeitschuh/ktlint-gradle#630]
Version in Project
Kotlin : 1.6.21
Gradle 7.5.1
I want to ask if v11.2.0 is supported in my project

**Comment by wakingrufus** [comment]
our compatibility is stated here: https://github.com/JLLeitschuh/ktlint-gradle#minimal-supported-versions
for kotlin version, it will be based on the version of ktlint you use.

**Comment by PaulWoitaschek** [comment]
I can't find a statement that 0.48.2 is not supported in the readme.
