### ISSUE TITLE
additionalEditorconfigFile config has stopped working

### ISSUE THREAD

**Issue by hrules6872** [JLLeitschuh/ktlint-gradle#633]
We had to upgrade the plugin to 11.2.0 to be able to use ktlint 0.48.2 but since then `additionalEditorconfigFile` has stopped working.
The plugin only pays attention to the `.editconfig` file located in the root of the project (where we were eventually forced to move it as a workaround).

**Comment by wakingrufus** [comment]
Would you mind checking if it is working for you with ktlint 0.47.1? I suspect that this is specifically related to 0.48, and would like to confirm

**Comment by hrules6872** [comment]
I just tried it and it still happens

**Comment by wakingrufus** [comment]
OK, i just verified with ktlint upstream maintainer that this feature was removed in upstream ktlint 0.47+.
Would you mind explaining your usecase for this in more detail so that I can assess what kind of workarounds we might be able to provide in this plugin?

**Comment by hrules6872** [comment]
TBH we only use this configuration to better organise the project so it may not be worth working on a solution, but it would be great to at least remove that option from the documentation :)
