### ISSUE TITLE
How long do you keep compatibility?

### ISSUE THREAD

**Issue by matsudamper** [JLLeitschuh/ktlint-gradle#639]
I'm trying to support ktlint 0.49.x. (snapshot)

But There are many changes.
- ReporterProviderV2 -> ReporterProviderV3
- RuleSetProviderV2 -> RuleSetProviderV3
- move package
  - com.pinterest.ktlint.core.api.editorconfig
  - -> com.pinterest.ktlint.rule.engine.core.api.editorconfig
  - com.pinterest.ktlint.core.api
  - -> com.pinterest.ktlint.rule.engine.api

How long and to what extent will this project preserve backward compatibility?
It's already hard to touch with Reflection.

**Comment by wakingrufus** [comment]
Once ktlint stabilizes its API in the 1.0 release, we will move up our minimal supported version to get rid of this reflection stuff. According to the ktlint devs, 1.0 should be next after 0.49

**Comment by matsudamper** [comment]
I was almost able to implement it with reflection, but there was a problem with the different output path of the baseline rules.
https://github.com/matsudamper/ktlint-gradle/tree/feature/damper/backward-compatible-ktlint-0.49

see `KtlintBaselineSupportTest`.
before
```
C:\Users\matsudamper\AppData\Local\Temp\junit6911958547393289814\plugin-test\src\main\kotlin\FailSource.kt
```

0.49
```
C:\Users\matsudamper\Documents\GitHub\ktlint-gradle\plugin\.gradle-test-kit\test-kit-daemon\7.6\src\main\kotlin\FailSource.kt
```
