### ISSUE TITLE
When shuold you apply the plugin to all project modules?

### ISSUE THREAD

**Issue by mobilekosmos** [JLLeitschuh/ktlint-gradle#640]
In the documentaion you state "Optionally apply plugin to all project modules:"
When should we apply the plugin to all modules rather than only to the root? What would be the difference?

**Comment by wakingrufus** [comment]
if you do not have kotlin sourceSets on your root project, the plugin should not be applied there at all.
in a multiproject setup, usually source sets only exist within subprojects.
In this case, you should apply this plugin to each subproject individually, or to all subprojects as you saw in the documentation. I recommend the former option.
