### ISSUE TITLE
Why cannot the latest ktlint version be used?

### ISSUE THREAD

**Issue by mobilekosmos** [JLLeitschuh/ktlint-gradle#641]
Why cannot a plug-in use the latest version of ktlint, I mean normally you just need to run it, what does this Plug-In do that it needs adaptions for the newest ktlint versions?

**Comment by wakingrufus** [comment]
ktlint 0.48 is supported by ktlint-gradle 11.2.0. if you are experiencing an issue, please open a bug report with your project setup and error you are encountering.

**Comment by mobilekosmos** [comment]
Hm, but in the release notes you state: 

change compile target to 0.45.2
change default ktlint version applied by plugin to 0.47.1

How to understand this?

**Comment by wakingrufus** [comment]
by default, the plugin uses ktlint 0.47.1, but this is configurable.
see: https://github.com/JLLeitschuh/ktlint-gradle#configuration

**Comment by mobilekosmos** [comment]
Thanks, but 2 questions remains:

1. Why is the compile target 0.45.2?
2. Why is the default not the latest one? (Because it's not tested yet?) Does this mean that there will be features missing despite I set it manually to 0.48.2?

**Comment by JLLeitschuh** [comment]
Annoyijgly, ktlint keeps breaking their API requiring us to manually craft reflection based adapters for certain version.

We want to support a range of ktlint versions, so we are somewhat forced to do it this way.

We'd like to be compiling against the latest version always, but the ideal isn't always possible.

Hopefully, this should be less of a problem after Ktlint releases 1.0 and their API hopefully stabilizes

**Comment by mobilekosmos** [comment]
Sorry to ask so many questions, but as a developer wanting to integrate this plugin I must be able to explain many details to management, etc. How to understand target compilation in this context? I don't understand how a project can "target" version xy and at the same time "support" higher versions :S

**Comment by JLLeitschuh** [comment]
> How to understand target compilation in this context? I don't understand how a project can "target" version xy and at the same time "support" higher versions

Primarily, using reflection to dynamically call methods/classes/interfaces that aren't available at compile time but will be at runtime.

Most of the reflection lives in this file if you're curious:
https://github.com/JLLeitschuh/ktlint-gradle/blob/main/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/worker/KtLintInvocation.kt
