### ISSUE TITLE
Wildcard import (cannot be auto-corrected)

### ISSUE THREAD

**Issue by L040639** [JLLeitschuh/ktlint-gradle#659]
For ./gradlew Format throwing this error

> Task :app:ktlintTestSourceSetFormat FAILED
/Users/L040639/Documents/helloall/app/src/test/java/com/androidsample/helloall/ExampleUnitTest.kt:3:1 Wildcard import (cannot be auto-corrected)

> Task :app:ktlintAndroidTestSourceSetFormat FAILED
/Users/L040639/Documents/helloall/app/src/androidTest/java/com/androidsample/helloall/ExampleInstrumentedTest.kt:5:1 Wildcard import (cannot be auto-corrected)

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:ktlintTestSourceSetFormat'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.ConsoleReportWorkAction
   > KtLint found code style violations. Please see the following reports:
     - /Users/L040639/Documents/helloall/app/build/reports/ktlint/ktlintTestSourceSetFormat/ktlintTestSourceSetFormat.txt

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:ktlintAndroidTestSourceSetFormat'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.ConsoleReportWorkAction
   > KtLint found code style violations. Please see the following reports:
     - /Users/L040639/Documents/helloall/app/build/reports/ktlint/ktlintAndroidTestSourceSetFormat/ktlintAndroidTestSourceSetFormat.txt

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
7 actionable tasks: 5 executed, 2 up-to-date
L040639@RDQTXDW65N helloall %

**Comment by wakingrufus** [comment]
Thank you for the report. What is your expected output in this case? At first glance this all looks like expected behavior
