### ISSUE TITLE
ktlint check tasks should be cacheable

### ISSUE THREAD

**Issue by eskatos** [JLLeitschuh/ktlint-gradle#67]
The ktlint check tasks created by this plugin don't have any output registered, so they are never up to date and cannot be cached by the [Gradle build cache](https://docs.gradle.org/current/userguide/build_cache.html).

The report files generated by those tasks should be registered as outputs and the task marked as cacheable.

Other tasks contributed by this plugin might be good candidates for build cache too, I just didn't look at them closely.

**Comment by JLLeitschuh** [comment]
This is generally a hard problem given the API that Gradle exposes.
See the forum post by @nedtwigg about it in Spotless:
https://discuss.gradle.org/t/two-cases-where-the-incremental-api-is-lacking/24266

**Comment by Tapchicoma** [comment]
I think there is no reason to make `ktlintFormat` type tasks cacheable, but definitely worth for `ktlintCheck` tasks!

**Comment by wolfs** [comment]
The check task is now cacheable since #90 has been merged.

**Comment by JLLeitschuh** [comment]
@wolfs Thank you for the great work!

**Comment by Tapchicoma** [comment]
Closing this as @wolfs implemented it.
