### ISSUE TITLE
ktlint_ editorconfig settings don't seem to be applied

### ISSUE THREAD

**Issue by system1-dersek** [JLLeitschuh/ktlint-gradle#684]
plugin:
`id("org.jlleitschuh.gradle.ktlint") version "11.4.1"`

`.editorconfig` file:
```
root = true

[*]
charset = utf-8
insert_final_newline = true
trim_trailing_whitespace = true

[*.{kt,kts}]
ktlint_standard_no-wildcard-imports = disabled
indent_size = 2
ij_kotlin_allow_trailing_comma = true
ij_kotlin_allow_trailing_comma_on_call_site = false
```

with `./gradlew ktlintCheck` still fails on `Wildcard import (cannot be auto-corrected) (no-wildcard-imports)` lines. I've tried various things like deleting .gradle, running `clean` first, using `--no-daemon` and `--rerun-tasks`, etc.

**Comment by system1-dersek** [comment]
The curse of finally opening a ticket after a while of looking into it...

Seems like a solution is to add the following to the build.gradle.kts:
```
ktlint {
    version.set("0.49.1")
}
```

**Comment by Azamat989** [comment]
> The curse of finally opening a ticket after a while of looking into it...

Did it work for you? Beacause it didn't for me

**Comment by luis-alves** [comment]
I've the same issue. And using the solution provided by @system1-dersek didn't work either.

**Comment by jonsmithers** [comment]
seems related to https://github.com/JLLeitschuh/ktlint-gradle/issues/663

**Comment by idunnololz** [comment]
> 

I got to work by also applying it to subprojects. 

Eg. in the top level build.gradle:
```


subprojects {
  apply(plugin = "org.jlleitschuh.gradle.ktlint")

  configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
    version.set("0.50.0")
    android.set(true)
  }
}

configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
  version.set("0.50.0")
}
```

**Comment by wakingrufus** [comment]
Thank you @idunnololz for providing the answer
