### ISSUE TITLE
`rangeUntil` operator results in `ParseException`

### ISSUE THREAD

**Issue by vanshg** [JLLeitschuh/ktlint-gradle#692]
### Description
Using the `operator fun rangeUntil` (i.e `1..<10`) results in a `ParseException`

### Stack Trace
```
Caused by: com.pinterest.ktlint.core.ParseException: 162:24 Expecting an element
	at com.pinterest.ktlint.core.internal.PreparedCodeKt.prepareCodeForLinting(PreparedCode.kt:40)
	at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:170)
	at org.jlleitschuh.gradle.ktlint.worker.KtLintInvocation47.invokeLint(KtLintInvocation47.kt:57)
	at org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction.execute(KtLintWorkAction.kt:111)
	... 22 more
```

### Minimum Reproducible Example
```kotlin
@OptIn(ExperimentalStdlibApi::class)
val test = 0..<10
```

### Workarounds
Using the function instead of the operator overload works okay (i.e. using `0.rangeUntil(10)`). 
Using the `until` infix function works okay (i.e. `0 until 10`)
Using the `rangeTo` function and operator overload (`..`) works okay (i.e. `1..10`)
Using ktlint via the CLI directly, I don't have any issues, and lint passes on the rangeUntil operator function

### Note
I do understand that this is an Experimental API and hence the opt-in annotation, so just wanted to bring it to attention. I have no expectations for an imminent fix until it is stabilized. But it is strange that the CLI works fine but the gradle plugin has issues.

### Versions
ktlint version: 0.50
ktlint-gradle version: 11.5.0

**Comment by JLLeitschuh** [comment]
I was going to say this looked like a bug in Ktlint not this plugin, until I saw "But it is strange that the CLI works fine but the gradle plugin has issues"

🤔

**Comment by vanshg** [comment]
@JLLeitschuh This went stable with the recent release of Kotlin 1.9: https://kotlinlang.org/docs/whatsnew19.html#stable-operator-for-open-ended-ranges

**Comment by wakingrufus** [comment]
I don't believe ktlint supported kotlin 1.9 until 1.0 (according to ktlint's release notes), can you retry with that ktlint version?
