### ISSUE TITLE
Support for `@Suppress` annotation

### ISSUE THREAD

**Issue by vanshg** [JLLeitschuh/ktlint-gradle#693]
### Description
Previously, I used to use `// ktlint-disable max-line-length` to disable the Max Line Length rule. As of ktlint 0.50.0, support for this was dropped in favor of an annotation based approach.

After migrating to using the `@Suppress` annotation (e.g. `@Suppress("ktlint:standard:max-line-length")`):
1.  If I use the ktlint CLI, everything passes
2. The gradle plugin does not seem to respect the annotation

### Error Message
```
> Task :sample:ktlintMainSourceSetCheck FAILED

<filename>:268:1 Exceeded max line length (100) (cannot be auto-corrected)
```

### Versions
ktlint version: 0.50
ktlint-gradle version: 11.5.0

I also tried explicitly setting the ktlint version in the build.gradle.kts:
```kotlin
ktlint {
    android = true
    version = "0.50.0"
}
```

**Comment by Matthew5716** [comment]
It appears that the `@Suppress` annotation now works with the latest versions.

### Versions
ktlint version: 1.0.0
ktlint-gradle version: 11.6.0

**Comment by wakingrufus** [comment]
Thanks  @Matthew5716 for confirming that this is now working with newer versions of ktlint
