### ISSUE TITLE
Plugin is incompatible with IntelliJ 2023.2

### ISSUE THREAD

**Issue by IvanPizhenko** [JLLeitschuh/ktlint-gradle#696]
Following error is displayed:
Plugin 'Ktlint (unofficial)' (version '0.12.0') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IC-232.8660.185

**Comment by wakingrufus** [comment]
This sounds like an issue with some type of intellij plugin, but this project is for the gradle plugin

**Comment by IvanPizhenko** [comment]
oops. yes, really, it is about IntelliJ plugin. So I'm closing it.
