### ISSUE TITLE
Allow to use custom rule sets

### ISSUE THREAD

**Issue by Tapchicoma** [JLLeitschuh/ktlint-gradle#71]
Ktlint provides an ability to use custom [rulesets](https://github.com/shyiko/ktlint#creating-a-ruleset). There are two ways to load them:
```bash
$ ktlint -R /path/to/custom/rulseset.jar "src/test/**/*.kt"
$ ktlint -R com.github.username:rulseset:master-SNAPSHOT
```

Plugin should allow to define custom rulesets and apply it when running check/fortmatting tasks.

**Comment by Tapchicoma** [comment]
> As a general idea, I love it.
> The question I have is that maybe it would be better if implemented using > the dependency API.
> For example:
> You'd do the following to add a ruleset:
>```gradle
>dependencies {
>    ktlintRuleset(file("/path/to/custom/rulseset.jar"))
>    ktlintRuleset("com.github.username:rulseset:master-SNAPSHOT")
>}
>

Keep this issue open for the idea to provide rulesets using Gradle dependencies.

**Comment by mkobit** [comment]
This is a use case we would use - multi-project builds where the ruleset comes from a local `project` dependency
