### ISSUE TITLE
Cannot disable rule using `additionalEditorConfig`

### ISSUE THREAD

**Issue by pdb-stripe** [JLLeitschuh/ktlint-gradle#713]
## Version info

* ktlint-gradle 11.6.0
* ktlint 0.50.0

## Steps to reproduce

Disable the rule from the `additionalEditorconfig` section on a `.kts` buildscript. For example:

````kotlin
configure<KtlintExtension> {
    additionalEditorconfig.set(
        mapOf(
            "ktlint_standard_indent" to "disabled"
         )
    )
}
````

## Expected result

The rule should be applied

## Actual result

The rule is not found. This error shows:

`Property with name 'ktlint_standard_indent' is not found in any of given rules. Available properties: ...`

-----

It is likely that the intent of this property is _not_ an extension of the `.editorconfig` file, but is rather meant only to apply specific properties. Since `disabledRules` is not supported at this level, is there no way short of creating more `.editorconfig` files to disable rules, or [overriding specific directories](https://pinterest.github.io/ktlint/0.49.1/rules/configuration-ktlint/#overriding-editorconfig-properties-for-specific-directories)?

**Comment by wakingrufus** [comment]
This a known shortcoming of the underlying ktkint implementation in 0.50. If you want to provide additional editorconfig to disable standard rules, try with ktkint 1.0+

**Comment by ymka** [comment]
Hi @wakingrufus 
I have next config
```
ktlint {
    version = "1.0.1"
    android = true
    additionalEditorconfig.set(
        mapOf(
            "ij_kotlin_allow_trailing_comma" to "true",
            "ij_kotlin_allow_trailing_comma_on_call_site" to "true"
        )
    )
}
```

As an experiment I've added `"max_line_length" to "20",` but it didn't have any impact.

**Comment by wakingrufus** [comment]
> Hi @wakingrufus I have next config
> 
> ```
> ktlint {
>     version = "1.0.1"
>     android = true
>     additionalEditorconfig.set(
>         mapOf(
>             "ij_kotlin_allow_trailing_comma" to "true",
>             "ij_kotlin_allow_trailing_comma_on_call_site" to "true"
>         )
>     )
> }
> ```
> 
> As an experiment I've added `"max_line_length" to "20",` but it didn't have any impact.

interesting. this test confirms this specific setup: https://github.com/JLLeitschuh/ktlint-gradle/blob/main/plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/KtLintSupportedVersionsTest.kt#L152

I wonder if this is related to `android = true`?
