### ISSUE TITLE
How to Remove `ktlintCheck` from `gradle build`

### ISSUE THREAD

**Issue by akshatjain-beam** [JLLeitschuh/ktlint-gradle#719]
Is there a way to remove the `KtlintCheck`, when running the `cradle build` command.
I don't want to `ktlint` commands to run automatically. And only should run, when wrote manually on terminal.

**Comment by wakingrufus** [comment]
this is not specific to the plugin, and is just general gradle stuff, but
```
tasks.named("ktlintCheck"){
    onlyIf { gradle.startParameter.taskNames.contains("ktlintCheck") }
}
```
should do what you want
