### ISSUE TITLE
Configuration cache broken with relative set to true

### ISSUE THREAD

**Issue by rschattauer** [JLLeitschuh/ktlint-gradle#721]
Hello there.

When we set `relative.set(true)` our configuration cache breaks with something along the line of
```
855 problems were found storing the configuration cache, 285 of which seem unique.
- Task `:app:ktlintBenchmarkSourceSetFormat` of type `org.jlleitschuh.gradle.ktlint.tasks.GenerateReportsTask`: invocation of 'Task.project' at execution time is unsupported.
```

This is probably because
https://github.com/JLLeitschuh/ktlint-gradle/blob/431af6b838915abc874c63e92955c9272c5d08dd/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/GenerateReportsTask.kt#L144-L146
is using project directly.

According to the table on https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements project.rootDir should be replaced with `A task input or output property or a script variable to capture the result of using project.rootDir to calculate the actual parameter.`

Thanks in advance!

**Comment by JLLeitschuh** [comment]
More than happy to accept a pull request that fixes the problem as long as it comes with an associated test that demonstrates the bug 🙂

**Comment by rschattauer** [comment]
@JLLeitschuh , will do, but have to grab my Intel Mac as my Apple Silicon Mac can't sync this project, is this known?

**Comment by JLLeitschuh** [comment]
I develop the project on one of the new M1 MBP laptops perfectly fine. I'm not familiar with any issues in this area
