### ISSUE TITLE
Disable rule for file pattern

### ISSUE THREAD

**Issue by hbb20** [JLLeitschuh/ktlint-gradle#727]
I need to enforce 120 line length for code files but need to disable this rule for my test files  (if file ends with *Test.kt).

Earlier, I had `.editorconfig` like this

```
[*.kt]
max_line_length=120
ij_visual_guides =100,120

[*Test.kt]
max_line_length=off
```

and then linked this config to ktlint using
```
ktlint {
    version.set(Versions.KTLINT)
    additionalEditorconfigFile.set(file("./.editorconfig"))
}
```

Now that `additionalEditorconfigFile` is removed and recommended way is to 
```

ktlint {
    version.set(Versions.KTLINT)
    additionalEditorconfig.set( // not supported until ktlint 0.49
        mapOf(
            "max_line_length" to "120",
        ),
    )
}
```

How can I specify file patterns to exclude?

**Comment by wakingrufus** [comment]
Ktlint now has built-in .editorconfig detection, so it should see your file with no special configuration. Have you tried that? What version of ktlint are you using now?

**Comment by wakingrufus** [comment]
Since there has been no response on this, I will close
