### ISSUE TITLE
Unexpected indentation (4) (should be 8)

### ISSUE THREAD

**Issue by nininea** [JLLeitschuh/ktlint-gradle#734]
this is my .editorConfig file
<img width="983" alt="Screenshot 2023-12-22 at 16 19 01" src="https://github.com/JLLeitschuh/ktlint-gradle/assets/82098854/4fe8ecab-f9cc-43ed-bedc-722d4ce6713a">
```

`root = true

[*.{kt,kts}]
max_line_length = 100
ktlint_standard_no-wildcard-imports = disabled
ktlint_standard_package-name = disabled
`
```
`>    id("org.jlleitschuh.gradle.ktlint") version "12.0.2"
`

**Comment by wakingrufus** [comment]
this is probably due to the new default code style in ktlint: https://pinterest.github.io/ktlint/0.49.1/rules/code-styles/
Closing this, as the plugin is working in this case, but it is ktlint behavior in question
