### ISSUE TITLE
Multiline-expression-wrapping rule breaks ktlintFormat

### ISSUE THREAD

**Issue by DemD10** [JLLeitschuh/ktlint-gradle#735]
i just add to .editconfig
`ktlint_standard_multiline-expression-wrapping = disabled`, after that task ktlintFormat failed. Another rules, like `ktlint_standard_no-empty-first-line-in-class-body = disabled` working fine.

> `Execution failed for task ':feature:account-reserve:runKtlintFormatOverKotlinScripts'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
`

**Comment by hanrw** [comment]
+1

**Comment by p0058781** [comment]
+1

```
Caused by: java.lang.IllegalStateException: Skipping rule(s) which are depending on a rule which is not loaded. Please check if you need to add additional rule sets before creating an issue.
  - Rule with id 'RuleId(value=standard:string-template-indent)' requires rule with id 'RuleId(value=standard:multiline-expression-wrapping)' to be loaded
```
But if you also disable that mentioned rule then it works again
`ktlint_standard_string-template-indent = disabled`

**Comment by wakingrufus** [comment]
this is likely a bug in the underlying ktlint logic, not the plugin. Make sure to specify the latest version of ktlint (currently 1.1.1), and if it still does not work, I recommend opening a ticket in [pinterest/ktlint ](https://github.com/pinterest/ktlint) or the #ktlint channel in kotlin Slack
