### ISSUE TITLE
Override rules for in-line comments and variables starting with underscore

### ISSUE THREAD

**Issue by a-bresler** [JLLeitschuh/ktlint-gradle#737]
I have recently upgraded to Gradle version `8.2.0` and ktlint version `12.0.3`. 

Post upgrade, some of the linting rules have changed and I'd like to override them or disable them. But I am unsure what rules need to be added to the `.editorconfig` file.

**First**
I want to allow inline comments.

e.g.
```
data class Something(
  val someValue: String // comment about someValue
)
```

Ktlint error: A comment in a 'value_argument_list' is only allowed when placed on a separate line (cannot be auto-corrected)

**Second**
I want to allow variables to start with an underscore `_`.

e.g. 
```
val _binding = ViewBinding? = null
```

Ktlint error: Property name should start with a lowercase letter and use camel case (cannot be auto-corrected)

---

Could you please assist in providing the rules or settings needed to override these?

**Comment by wakingrufus** [comment]
I think this has to do with how ktlint is applying rules. Take a look at https://pinterest.github.io/ktlint/dev-snapshot/rules/code-styles/ and https://pinterest.github.io/ktlint/dev-snapshot/rules/standard/ I think these docs will give you some insight on how to configure ktlint the way you want.
