### ISSUE TITLE
Failing my builds if code isn't formatted

### ISSUE THREAD

**Issue by falOn-Dev** [JLLeitschuh/ktlint-gradle#739]
My builds are failing if the code isn't properly formatted, even though I never added a check to the build. I only want it to happen during commits using a precommit hook.

My code is here: [https://github.com/Team2537/2024Crescendo](https://github.com/Team2537/2024Crescendo)

**Comment by wakingrufus** [comment]
You likely want to configure the plugin to ignoreFailures:
https://github.com/JLLeitschuh/ktlint-gradle#configuration

**Comment by falOn-Dev** [comment]
This is not a solution, as this just disables all checking, I want to be able to check for formatting, I just want it to only be manual, rather than be automatic when building

**Comment by wakingrufus** [comment]
This flag set to true will allow the checks to run and reports to generate, but the build to still succeed even if the check finds lint errors. It does not disable checking.

The fact that the check task runs as dependency of gradle build and gradle check is a standard gradle convention. If you wish to not run checks as part of your build, you can run gradle test to just build and test
