### ISSUE TITLE
Using this plugin with the official IntelliJ IDE plugin

### ISSUE THREAD

**Issue by wejrox** [JLLeitschuh/ktlint-gradle#744]
# Summary

I've got a few projects that use this plugin to format our code before commit.
We also use the [Ktlint IntelliJ plugin](https://plugins.jetbrains.com/plugin/15057-ktlint) with auto formatting to fix code violations on-save before commit.

## Problem

Currently, the rules applied by that plugin don't align with the rules applied by this plugin.
I'd like to make the IDE plugin use the rules in use by this plugin.

## Environment

ktlint-gradle version `11.6.1`
Android Studio `2023.1.1`
Android Studio ktlint plugin (According to the docs, the plugin currently runs with ktlint version 1.1.0 and can use `.editorconfig`)

## What I've tried

I've tried to use the `ktlintApplyToIdea` to export the rules and apply them to the IDE, but I'm receiving
```
> Task :ktlintApplyToIdea
Skipping ktlintApplyToIdea. The applyToIDEA functionality was removed from ktlint in 0.47.0. Use .editorconfig to synchronize formatting rules between IDEA and ktlint.

BUILD SUCCESSFUL in 219ms
1 actionable task: 1 executed
```

Because I don't know the default rules, I don't have the information required to `Use .editorconfig to synchronize formatting rules between IDEA and ktlint.`.

## Request

Is there some documentation on how I can export an xml ruleset, or guidance on this?

**Comment by wakingrufus** [comment]
I think this page will help you: https://pinterest.github.io/ktlint/1.1.1/rules/code-styles/

**Comment by wejrox** [comment]
Unfortunately, that page tells me how I can override the code style rules, but I don't know which rules `ktlint-gradle` uses by default.

I want to force my IDE to use the same rules as `ktlint-gradle` is applying, so I need to konw what those default rules are.

**Comment by wakingrufus** [comment]
the code _style_ used by default is whichever the underlying version of ktlint is using. So for ktlint version < 1 it is intellij style, and for >=1 it is ktlint_official.

as for the configuration of specfic rules, again, this is tied to the version of ktlint being used.

since you are using ktlint-gradle 11.6.1, the version of ktlint it is using by default is `0.47.1`. I recommend [changing](https://github.com/JLLeitschuh/ktlint-gradle?tab=readme-ov-file#configuration) this to match the version of ktlint your intellij plugin is using.

**Comment by wejrox** [comment]
Thanks, and sorry for the late response. 

As of now, the `ktlint` IntelliJ/Android Studio plugin allows you to specify the version of the ktlint ruleset to apply, which I have set to align with the version specified by this plugin in the plugins `build.gradle` file.
