### ISSUE TITLE
import checks

### ISSUE THREAD

**Issue by Dambldore** [JLLeitschuh/ktlint-gradle#749]
Hi, I am interesting is there a way to fail lint on that code:

```kotlin
fun test() {
    println(java.time.Instant.now())
}

```
i want that linter forced me to use explicit import in imports section or using typealias 

may be it is already implemented and i need some changes in my editorconfig file or something like that

**Comment by JLLeitschuh** [comment]
This is likely a question for the maintainers of Ktlint, not this Gradle Plugin.

Consider asking here:

https://github.com/pinterest/ktlint
