### ISSUE TITLE
Caches work incorrectly: additionalEditorconfig should be @Input instead of @Internal

### ISSUE THREAD

**Issue by m-burst** [JLLeitschuh/ktlint-gradle#750]
Steps to reproduce:

1. Write some code with ktlint violations
2. Run ktlint via plugin with enabled build cache
3. Disable the violated rule using `additionalEditorconfig`
4. Run ktlint again with enabled build cache

Expected behaviour: ktlint will be re-run with updated editorconfig and will not report the violations

Actual behaviour: ktlint will use the cached result

As far as I understand, the cause of this is that `BaseKtLintCheckTask.additionalEditorconfig` is not checked when computing cache keys for the task because it is marked as `@Internal`, and should be `@Input` instead.

Unless there are any reasons for this property being `@Internal`, I would gladly submit a PR changing it to `@Input`.

**Comment by wakingrufus** [comment]
I would love a PR for this. There should be some tests already that are fairly similar you can copy from to get started on your test. Let me know if you get stuck and I can assist.

**Comment by m-burst** [comment]
I finally got around to this and opened #758. Could you please take a look?

**Comment by m-burst** [comment]
Thanks for reviewing and merging!
Do you have any plans to cut a release sometime soon?
