### ISSUE TITLE
unknown ktlint version

### ISSUE THREAD

**Issue by david-claimer** [JLLeitschuh/ktlint-gradle#760]
How do I know which version of ktlint the plugin is using? I want to use whatever the default is for the version of the plugin I use (currently 12.1.0) but I can't find anything in docs or code.

**Comment by wakingrufus** [comment]
The default is set in the extension: https://github.com/JLLeitschuh/ktlint-gradle/blob/main/plugin%2Fsrc%2Fmain%2Fkotlin%2Forg%2Fjlleitschuh%2Fgradle%2Fktlint%2FKtlintExtension.kt#L39

**Comment by david-claimer** [comment]
perfect thanks.
