### ISSUE TITLE
Upgrade ktlint-cli  -> `VULNERALIBILTY` on logback-classic

### ISSUE THREAD

**Issue by zelyon** [JLLeitschuh/ktlint-gradle#764]
Need upgrade dependencies com.pinterest.ktlint:ktlint-cli:1.0.1 to 1.1.0 
in order to upgrade dependencie ch.qos.logback:logback-classic:1.3.5 to 1.3.14

dependencie ch.qos.logback:logback-classic:1.3.5 contains vulnerability : 
CWE-502 | Deserialization of Untrusted Data

**Comment by wakingrufus** [comment]
ktlint-gradle does not have a transitive dependency on ktlint (or logback). For projects using ktlint-gradle, the versions of those libraries used in the buildscript classpath is determined by the plugin's configuration of the ktlint version. eg. 
```
ktlint {
    version.set("1.1.0")
}
```
