### ISSUE TITLE
Single baseline file for multi-module project

### ISSUE THREAD

**Issue by rafsanjani** [JLLeitschuh/ktlint-gradle#789]
Is there a way to generate a single baseline file for a multi-module project? This is especially useful when running ktlint using the CLI tool on a CI environment where only a single baseline file can be passed as an argument.

**Comment by tevincent** [comment]
Hey there, @rafsanjani  how did you solve this issue ? Did you find a way to generate a single baseline file for a multi-module project ?

**Comment by rafsanjani** [comment]
we ended up using the ktlint cli to do it. This meant that on our CI environment we also run ktlint using the cli tool.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
