### ISSUE TITLE
Format does not actually seem to format?

### ISSUE THREAD

**Issue by Syrou** [JLLeitschuh/ktlint-gradle#83]
So the tasks are in, they are reporting the klint error, but as far as I understand it
should not the format task format the code in such a way that the lint error dissapears?

Cause for instance i now get `RANDOMFILE.kt:10:1: Exceeded max line length (100) (max-line-length)`

I expect it to look for a pattern where it should divide it, or is there some of these klint errors
that the formatter does not support?

**Comment by Tapchicoma** [comment]
From my experience not everything is fixed with KtLint format, some issues you have to fix manually.

**Comment by Tapchicoma** [comment]
Closing this issue as it is more related to parent KtLint project. Feel free to reopen it if you considering it wrong.
