### ISSUE TITLE
Add support for apply-to-idea-project formating command

### ISSUE THREAD

**Issue by igorwojda** [JLLeitschuh/ktlint-gradle#91]
I added a plugin to the project.
Now every developer in the team must manually run this ktlint command 
`./ktlint --apply-to-idea-project --android`

This is fine, but I wonder can it be achieved without separatley downloading (and keeping) ktlint binaries? I would be nice to provide ability to configure IDE out of the box.

hmm Maybe plugin could somehow link `./ktlint` command to project root or add new gradle task that would allow passing parameters to ktlint script `./gradlew ktlint` 🤔

(we could, of course, add new grade task but I feel this would not be flexible enough if new ktlint parameters will be added in future)

**Comment by JLLeitschuh** [comment]
Oooooh. I really like this idea. @Tapchicoma What do you think?

**Comment by Tapchicoma** [comment]
I don't have strong opinion on it, but I don't think that adding some generic task that will passes parameters to ktlint is a good idea. Then better to use ktlint directly.

Regarding the `--apply-to-idea-project` - plugin can add one separate task to root project `ktlintApplyToIDEA` that will use extension configuration to apply rules to IDEA.

**Comment by igorwojda** [comment]
You are right, this makes perfect sense

**Comment by igorwojda** [comment]
Thanks for implementing this 👍

**Comment by Tapchicoma** [comment]
Reopening this as implementation is slightly wrong: https://github.com/shyiko/ktlint/issues/178

I am thinking of introducing second task `ktlintApplyToIdeaGlobally` and adding the current one if ktlint version is >=0.22.0
