### ISSUE TITLE
“max_line_length”

### ISSUE THREAD

**Issue by proying** [JLLeitschuh/ktlint-gradle#93]
Hi，could ktlint-gradle support the modification of max_line_length?

**Comment by JLLeitschuh** [comment]
@shyiko Is there something special we have to do to make this work??

**Comment by shyiko** [comment]
nope. ktlint loads .editorconfig automatically. If it doesn't work - check that .editorconfig is inside the workdir (or in one of the parent dirs) ([for now](https://github.com/shyiko/ktlint/pull/207)).

**Comment by Tapchicoma** [comment]
Confirm that using `.editorconfig` should solve this issue.

**Comment by Tapchicoma** [comment]
Closing this, @proying feel free to reopen if you still think that this this plugin job.
