### ISSUE TITLE
Add a task to check project kotlin dsl files

### ISSUE THREAD

**Issue by Tapchicoma** [JLLeitschuh/ktlint-gradle#98]
Currently, while `KtlintCheck` task supports checking `kts` files, plugin itself doesn't add any task for this files.

Plugin should add task that checks project kotlin gradle dsl files.

**Comment by lordcodes** [comment]
Should it be a separate task, or should you just be able to include Kotlin DSL *.gradle.kts files via the include filter in ktlint extension?

**Comment by Tapchicoma** [comment]
It will be separate tasks (something like `ktlintGradleKotlinDSLCheck` and `ktlintGradleKotlinDSLFormat`), that will also be triggered by `ktlintCheck` (or `ktlintFormat` accordingly) task.

As there is not way to get all build files for the project - current plan is to check all `*.kts` files in the project main directory and add property to extension, that will allow to provide additional directories related to project main directory.

**Comment by lordcodes** [comment]
Sure, sounds great. Thanks for explaining. I came to similar conclusion at
reading into the code a little too find out why it wasn't ashtray possible.
